var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]


/*--------------------------------Spanish--------------------------------*/

var pistaES1 = [
        {"start": "0.181","text": "En" },
        {"start": "0.465","text": "Yogópolis" },
        {"start": "1.414","text": "no" },
        {"start": "1.661","text": "todo" },
        {"start": "1.970","text": "es" },
        {"start": "2.154","text": "paz" },
        {"start": "2.397","text": "y" },
        {"start": "2.511","text": "tranquilidad" },
        {"start": "4.101","text": "Algunas" },
        {"start": "4.696","text": "veces" },
        {"start": "5.282","text": "hay" },
        {"start": "5.512","text": "problemas" },
        {"start": "6.050","text": "mayores" },
        {"start": "6.654","text": "que" },
        {"start": "6.753","text": "nuestros" },
        {"start": "7.153","text": "héroes" },
        {"start": "7.572","text": "deben" },
        {"start": "7.802","text": "atender" }
]
  
var pistaES2 = [
        {"start": "0.162","text": "El" },
        {"start": "0.396","text": "día" },
        {"start": "0.666","text": "de" },
        {"start": "0.768","text": "la" },
        {"start": "0.954","text": "invasión" },
        {"start": "1.823","text": "los" },
        {"start": "2.087","text": "Yogotars" },
        {"start": "2.777","text": "actuaron" },
        {"start": "3.515","text": "rápidamente" },
        {"start": "5.872","text": "Luna" },
        {"start": "6.831","text": "Activa" },
        {"start": "7.383","text": "tu" },
        {"start": "7.557","text": "campo" },
        {"start": "7.887","text": "de" },
        {"start": "7.983","text": "defensa" },
        {"start": "9.758","text": "gritó" },
        {"start": "10.496","text": "Eagle" },
        {"start": "12.000","text": "Oye" },
        {"start": "12.691","text": "ya" },
        {"start": "12.931","text": "lo" },
        {"start": "13.051","text": "hice" },
        {"start": "14.071","text": "no" },
        {"start": "14.376","text": "tienes" },
        {"start": "14.778","text": "que" },
        {"start": "14.904","text": "gritarme" },
        {"start": "16.644","text": "dijo" },
        {"start": "17.111","text": "Luna" },
        {"start": "17.429","text": "molesta" }
];
  
var pistaES3 = [
        {"start": "0.200","text": "Oof" },
        {"start": "1.189","text": "salta" },
        {"start": "1.675","text": "y" },
        {"start": "1.810","text": "derriba" },
        {"start": "2.209","text": "su" },
        {"start": "2.382","text": "rayo" },
        {"start": "2.795","text": "paralizador" },
        {"start": "4.691","text": "gritó" },
        {"start": "5.377","text": "Eagle" },
        {"start": "7.182","text": "Oof" },
        {"start": "7.820","text": "no" },
        {"start": "7.989","text": "dijo" },
        {"start": "8.302","text": "nada" },
        {"start": "9.152","text": "pero" },
        {"start": "9.352","text": "algo" },
        {"start": "9.690","text": "en" },
        {"start": "9.808","text": "la" },
        {"start": "9.864","text": "actitud" },
        {"start": "10.333","text": "de" },
        {"start": "10.437","text": "su" },
        {"start": "10.632","text": "compañero" },
        {"start": "11.366","text": "le" },
        {"start": "11.504","text": "molestó" }
]

var pistaES4 = [
        {"start": "0.215","text": "Eres" },
        {"start": "0.537","text": "muy" },
        {"start": "0.788","text": "lento" },
        {"start": "1.354","text": "Dinamita" },
        {"start": "2.390","text": "déjame" },
        {"start": "2.892","text": "eso" },
        {"start": "3.114","text": "a" },
        {"start": "3.201","text": "mi" },
        {"start": "4.819","text": "Eagle" },
        {"start": "5.619","text": "le" },
        {"start": "5.730","text": "arrebató" },
        {"start": "6.262","text": "el" },
        {"start": "6.408","text": "cañón" },
        {"start": "6.809","text": "de" },
        {"start": "6.989","text": "patos" },
        {"start": "7.306","text": "de" },
        {"start": "7.393","text": "hule" },
        {"start": "8.076","text": "a" },
        {"start": "8.191","text": "Dinamita" },
        {"start": "9.954","text": "él" },
        {"start": "10.428","text": "no" },
        {"start": "10.771","text": "dijo" },
        {"start": "10.957","text": "nada" },
        {"start": "11.945","text": "pero" },
        {"start": "12.168","text": "los" },
        {"start": "12.365","text": "modales" },
        {"start": "12.810","text": "de" },
        {"start": "13.015","text": "Eagle" },
        {"start": "13.524","text": "no" },
        {"start": "13.711","text": "le" },
        {"start": "13.908","text": "parecieron" },
        {"start": "14.532","text": "los" },
        {"start": "14.729","text": "correctos" }
]
 
var pistaES5 = [
        {"start": "0.158","text": "Al" },
        {"start": "0.352","text": "final" },
        {"start": "1.176","text": "los" },
        {"start": "1.516","text": "Yogotars" },
        {"start": "2.179","text": "lograron" },
        {"start": "2.828","text": "detener" },
        {"start": "3.344","text": "la" },
        {"start": "3.513","text": "invasión" },
        {"start": "3.974","text": "a" },
        {"start": "4.102","text": "Yogópolis" },
        {"start": "5.480","text": "Eagle" },
        {"start": "6.011","text": "parecía" },
        {"start": "6.524","text": "muy" },
        {"start": "6.967","text": "contento" },
        {"start": "8.139","text": "pero" },
        {"start": "8.311","text": "el" },
        {"start": "8.428","text": "resto" },
        {"start": "8.729","text": "de" },
        {"start": "8.897","text": "sus" },
        {"start": "9.135","text": "compañeros" },
        {"start": "10.073","text": "no" },
        {"start": "10.428","text": "lo" },
        {"start": "10.533","text": "estaban" },
        {"start": "12.450","text": "Lo" },
        {"start": "12.637","text": "logramos" },
        {"start": "13.992","text": "Que" },
        {"start": "14.139","text": "les" },
        {"start": "14.289","text": "parece" },
        {"start": "14.600","text": "si" },
        {"start": "14.802","text": "celebramos" },
        {"start": "16.553","text": "dijo" },
        {"start": "17.065","text": "Eagle" },
        {"start": "17.765","text": "muy" },
        {"start": "18.025","text": "emocionado" },
        {"start": "19.684","text": "Sus" },
        {"start": "19.955","text": "compañeros" },
        {"start": "20.992","text": "no" },
        {"start": "21.344","text": "le" },
        {"start": "21.523","text": "hicieron" },
        {"start": "22.073","text": "caso" }
]
   
var pistaES6 = [
        {"start": "0.145","text": "Amigos" },
        {"start": "2.162","text": "dijo" },
        {"start": "2.651","text": "Eagle" },
        {"start": "4.407","text": "El" },
        {"start": "4.641","text": "resto" },
        {"start": "5.089","text": "de" },
        {"start": "5.233","text": "los" },
        {"start": "5.440","text": "Yogotars" },
        {"start": "6.177","text": "lo" },
        {"start": "6.390","text": "dejaron" },
        {"start": "6.962","text": "solo" },
        {"start": "8.373","text": "Eagle" },
        {"start": "8.972","text": "estaba" },
        {"start": "9.537","text": "desconcertado" },
        {"start": "11.228","text": "no" },
        {"start": "11.555","text": "sabía" },
        {"start": "12.402","text": "qué" },
        {"start": "12.711","text": "había" },
        {"start": "13.111","text": "hecho" },
        {"start": "13.400","text": "mal" },
        {"start": "15.982","text": "Lo" },
        {"start": "16.182","text": "siento" },
        {"start": "16.747","text": "Eagle" },
        {"start": "17.573","text": "el" },
        {"start": "17.717","text": "equipo" },
        {"start": "18.144","text": "no" },
        {"start": "18.255","text": "está" },
        {"start": "18.489","text": "muy" },
        {"start": "18.764","text": "contento" },
        {"start": "19.260","text": "contigo" },
        {"start": "21.119","text": "dijo" },
        {"start": "21.491","text": "Luna" },
        {"start": "23.336","text": "Que" },
        {"start": "23.729","text": "fue" },
        {"start": "23.908","text": "lo" },
        {"start": "24.108","text": "que" },
        {"start": "24.328","text": "hice" },
        {"start": "26.504","text": "Son" },
        {"start": "26.876","text": "tus" },
        {"start": "27.089","text": "modales" },
        {"start": "28.150","text": "no" },
        {"start": "28.418","text": "hubo" },
        {"start": "28.680","text": "un" },
        {"start": "28.886","text": "por" },
        {"start": "29.107","text": "favor" },
        {"start": "29.816","text": "ni" },
        {"start": "30.000","text": "un" },
        {"start": "30.326","text": "gracias" },
        {"start": "31.923","text": "respondió" },
        {"start": "32.715","text": "Luna" },
        {"start": "33.459","text": "algo" },
        {"start": "33.858","text": "molesta" },
        {"start": "36.358","text": "Pero" },
        {"start": "37.397","text": "yo" },
        {"start": "39.222","text": "dijo" },
        {"start": "39.890","text": "Eagle" },
        {"start": "41.522","text": "CONTINUARÁ" }
]

/*--------------------------------English--------------------------------*/
 
var pistaEN1 = [
        {"start": "0.637","text": "Yogopolis" },
        {"start": "1.563","text": "is" },
        {"start": "1.768","text": "not" },
        {"start": "2.167","text": "always" },
        {"start": "2.600","text": "at" },
        {"start": "2.958","text": "peace" },
        {"start": "3.944","text": "Sometimes" },
        {"start": "4.944","text": "big" },
        {"start": "5.285","text": "problems" },
        {"start": "5.782","text": "arise" },
        {"start": "6.440","text": "and" },
        {"start": "6.570","text": "our" },
        {"start": "6.825","text": "heroes" },
        {"start": "7.358","text": "have" },
        {"start": "7.565","text": "to" },
        {"start": "7.731","text": "save" },
        {"start": "7.970","text": "the" },
        {"start": "8.101","text": "day" }
]

var pistaEN2 = [
        {"start": "0.678","text": "On" },
        {"start": "0.820","text": "the" },
        {"start": "1.093","text": "invasion" },
        {"start": "1.606","text": "day" },
        {"start": "2.094","text": "the" },
        {"start": "2.270","text": "yogotars" },
        {"start": "2.909","text": "had" },
        {"start": "3.192","text": "to" },
        {"start": "3.329","text": "act" },
        {"start": "3.763","text": "quickly" },
        {"start": "4.984","text": "Luna" },
        {"start": "5.711","text": "turn" },
        {"start": "5.974","text": "on" },
        {"start": "6.165","text": "your" },
        {"start": "6.477","text": "force" },
        {"start": "6.804","text": "field" },
        {"start": "7.590","text": "shouted" },
        {"start": "7.941","text": "eagle" },
        {"start": "9.064","text": "hey" },
        {"start": "9.767","text": "I" },
        {"start": "9.904","text": "already" },
        {"start": "10.358","text": "did" },
        {"start": "10.577","text": "that" },
        {"start": "11.109","text": "you" },
        {"start": "11.304","text": "don't" },
        {"start": "11.549","text": "have" },
        {"start": "11.758","text": "to" },
        {"start": "11.890","text": "yell" },
        {"start": "12.046","text": "at" },
        {"start": "12.232","text": "me" },
        {"start": "12.852","text": "answered" },
        {"start": "13.247","text": "Luna" },
        {"start": "13.833","text": "mad" }
]
  
var pistaEN3 = [
        {"start": "0.530","text": "Oof" },
        {"start": "1.386","text": "jump" },
        {"start": "1.920","text": "and" },
        {"start": "2.082","text": "take" },
        {"start": "2.393","text": "down" },
        {"start": "2.623","text": "their" },
        {"start": "2.823","text": "paralyzing" },
        {"start": "3.614","text": "beam" },
        {"start": "4.355","text": "Eagle" },
        {"start": "4.666","text": "shouted" },
        {"start": "5.991","text": "Oof" },
        {"start": "6.264","text": "did" },
        {"start": "6.421","text": "not" },
        {"start": "6.759","text": "say" },
        {"start": "7.000","text": "anything" },
        {"start": "7.666","text": "but" },
        {"start": "7.804","text": "there" },
        {"start": "7.950","text": "was" },
        {"start": "8.180","text": "something" },
        {"start": "8.572","text": "about" },
        {"start": "8.749","text": "his" },
        {"start": "9.187","text": "peer's" },
        {"start": "9.544","text": "attitude" },
        {"start": "10.189","text": "that" },
        {"start": "10.343","text": "made" },
        {"start": "10.527","text": "him" },
        {"start": "10.765","text": "mad" },
]

var pistaEN4 = [
        {"start": "0.679","text": "You" },
        {"start": "0.911","text": "are" },
        {"start": "1.196","text": "too" },
        {"start": "1.411","text": "slow" },
        {"start": "2.000","text": "Dinamita" },
        {"start": "3.129","text": "give" },
        {"start": "3.229","text": "me" },
        {"start": "3.514","text": "that" },
        {"start": "4.167","text": "Eagle" },
        {"start": "4.496","text": "snarled" },
        {"start": "5.017","text": "as" },
        {"start": "5.245","text": "he" },
        {"start": "5.482","text": "snatched" },
        {"start": "5.889","text": "the" },
        {"start": "6.016","text": "rubber-duck" },
        {"start": "6.428","text": "shooter" },
        {"start": "6.928","text": "from" },
        {"start": "7.094","text": "Dinamita's" },
        {"start": "7.708","text": "hands" },
        {"start": "9.154","text": "Dinamita" },
        {"start": "9.750","text": "kept" },
        {"start": "10.153","text": "quiet" },
        {"start": "10.688","text": "but" },
        {"start": "10.841","text": "he" },
        {"start": "11.000","text": "thought" },
        {"start": "11.205","text": "Eagle's" },
        {"start": "11.555","text": "manners" },
        {"start": "12.217","text": "could" },
        {"start": "12.357","text": "be" },
        {"start": "12.559","text": "better" }
]
   
var pistaEN5 = [
        {"start": "0.576","text": "In" },
        {"start": "0.729","text": "the" },
        {"start": "0.841","text": "end" },
        {"start": "1.382","text": "the" },
        {"start": "1.534","text": "Yogotars" },
        {"start": "2.258","text": "were" },
        {"start": "2.405","text": "able" },
        {"start": "2.710","text": "to" },
        {"start": "3.016","text": "stop" },
        {"start": "3.310","text": "the" },
        {"start": "3.428","text": "invasion" },
        {"start": "3.933","text": "of" },
        {"start": "4.145","text": "Yogopolis" },
        {"start": "5.791","text": "Eagle" },
        {"start": "6.238","text": "seemed" },
        {"start": "6.467","text": "to" },
        {"start": "6.649","text": "be" },
        {"start": "6.832","text": "very" },
        {"start": "7.196","text": "happy" },
        {"start": "7.784","text": "but" },
        {"start": "7.931","text": "the" },
        {"start": "8.060","text": "rest" },
        {"start": "8.313","text": "of" },
        {"start": "8.460","text": "the" },
        {"start": "8.672","text": "team" },
        {"start": "8.936","text": "wasn't" },
        {"start": "9.924","text": "We" },
        {"start": "10.371","text": "did" },
        {"start": "10.524","text": "it" },
        {"start": "11.441","text": "Why" },
        {"start": "11.647","text": "don't" },
        {"start": "11.870","text": "we" },
        {"start": "12.052","text": "go" },
        {"start": "12.188","text": "out" },
        {"start": "12.446","text": "to" },
        {"start": "12.693","text": "celebrate" },
        {"start": "13.596","text": "said" },
        {"start": "13.893","text": "Eagle" },
        {"start": "14.357","text": "excitedly" },
        {"start": "15.451","text": "but" },
        {"start": "15.574","text": "his" },
        {"start": "15.850","text": "friends" },
        {"start": "16.397","text": "didn't" },
        {"start": "16.809","text": "follow" },
        {"start": "17.173","text": "him" }
]

var pistaEN6 = [
        {"start": "0.614","text": "Team" },
        {"start": "1.480","text": "asked" },
        {"start": "1.872","text": "Eagle" },
        {"start": "2.919","text": "The" },
        {"start": "3.040","text": "rest" },
        {"start": "3.267","text": "of" },
        {"start": "3.413","text": "the" },
        {"start": "3.574","text": "Yogotars" },
        {"start": "4.158","text": "left" },
        {"start": "4.525","text": "him" },
        {"start": "4.726","text": "by" },
        {"start": "4.933","text": "himself" },
        {"start": "6.377","text": "Eagle" },
        {"start": "6.740","text": "was" },
        {"start": "6.976","text": "confused" },
        {"start": "8.134","text": "he" },
        {"start": "8.255","text": "didn't" },
        {"start": "8.562","text": "know" },
        {"start": "8.813","text": "what" },
        {"start": "8.979","text": "he" },
        {"start": "9.135","text": "did" },
        {"start": "9.322","text": "wrong" },
        {"start": "10.968","text": "Sorry" },
        {"start": "11.516","text": "Eagle" },
        {"start": "12.337","text": "the" },
        {"start": "12.468","text": "team" },
        {"start": "12.885","text": "is" },
        {"start": "13.061","text": "not" },
        {"start": "13.670","text": "quite" },
        {"start": "13.912","text": "happy" },
        {"start": "14.345","text": "with" },
        {"start": "14.481","text": "you" },
        {"start": "15.100","text": "said" },
        {"start": "15.326","text": "Luna" },
        {"start": "16.212","text": "What" },
        {"start": "16.404","text": "did" },
        {"start": "16.544","text": "I" },
        {"start": "16.821","text": "do" },
        {"start": "17.622","text": "It's" },
        {"start": "17.878","text": "because" },
        {"start": "18.256","text": "of" },
        {"start": "18.372","text": "your" },
        {"start": "18.528","text": "manners" },
        {"start": "19.137","text": "Eagle" },
        {"start": "20.123","text": "You" },
        {"start": "20.319","text": "never" },
        {"start": "20.591","text": "said" },
        {"start": "21.054","text": "please" },
        {"start": "21.779","text": "or" },
        {"start": "22.056","text": "thank" },
        {"start": "22.454","text": "you" },
        {"start": "23.042","text": "answered" },
        {"start": "23.475","text": "Luna" },
        {"start": "23.994","text": "a" },
        {"start": "24.145","text": "little" },
        {"start": "24.351","text": "angry" },
        {"start": "25.438","text": "But" },
        {"start": "26.193","text": "I" },
        {"start": "27.024","text": "said" },
        {"start": "27.366","text": "Eagle" },
        {"start": "28.000","text": "embarrassed" },
        {"start": "29.410","text": "TO" },
        {"start": "29.626","text": "BE" },
        {"start": "29.883","text": "CONTINUED" }
]


/*--------------------------------Korean--------------------------------*/


var pistaKO1 = [
        { "start": "0.005","text": "요고폴리스는" },
        { "start": "2.044","text": "항상" },
        { "start": "3.003","text": "평화롭지는" },
        { "start": "4.478","text": "않아요." },
        { "start": "6.271","text": "가끔" },
        { "start": "7.526","text": "큰" },
        { "start": "8.308","text": "문제가" },
        { "start": "9.252","text": "생기고" },
        { "start": "10.753","text": "우리의" },
        { "start": "11.553","text": "히어로들은" },
        { "start": "13.251","text": "그" },
        { "start": "13.787","text": "문제를" },
        { "start": "14.950","text": "해결해야만" },
        { "start": "16.165","text": "해요." }
]

var pistaKO2 = [
        { "start": "0.009","text": "공격을" },
        { "start": "0.990","text": "받은" },
        { "start": "1.738","text": "어느" },
        { "start": "2.312","text": "날," },
        { "start": "3.307","text": "요고타들은" },
        { "start": "5.052","text": "재빠르게" },
        { "start": "6.360","text": "행동해야" },
        { "start": "7.466","text": "했어요." },
        { "start": "10.032","text": "루나야!" },
        { "start": "11.109","text": "네" },
        { "start": "11.311","text": "방어막을" },
        { "start": "11.988","text": "얼른" },
        { "start": "12.436","text": "켜!" },
        { "start": "13.673","text": "이글이가" },
        { "start": "14.686","text": "소리쳤어요." },
        { "start": "17.313","text": "야!" },
        { "start": "18.300","text": "이미" },
        { "start": "18.625","text": "켜" },
        { "start": "18.775","text": "놨어." },
        { "start": "20.035","text": "나한테" },
        { "start": "20.838","text": "소리를" },
        { "start": "21.484","text": "지를" },
        { "start": "22.003","text": "필요는" },
        { "start": "22.541","text": "없어." },
        { "start": "24.304","text": "루나가" },
        { "start": "25.663","text": "화난" },
        { "start": "26.392","text": "목소리로" },
        { "start": "27.600","text": "대답했어요." }
]

var pistaKO3 = [
        { "start": "0.002","text": "우프," },
        { "start": "1.032","text": "점프해" },
        { "start": "1.640","text": "가서" },
        { "start": "2.555","text": "적들의" },
        { "start": "3.410","text": "마비" },
        { "start": "3.824","text": "광선을" },
        { "start": "4.490","text": "치워!" },
        { "start": "6.437","text": "이글이가" },
        { "start": "7.551","text": "소리쳤어요." },
        { "start": "9.901","text": "우프는" },
        { "start": "11.247","text": "아무" },
        { "start": "11.882","text": "말도" },
        { "start": "12.754","text": "하지" },
        { "start": "13.243","text": "않았지만," },
        { "start": "14.919","text": "우프를" },
        { "start": "15.853","text": "화나게" },
        { "start": "16.411","text": "한" },
        { "start": "17.395","text": "친구의" },
        { "start": "18.247","text": "태도에는" },
        { "start": "19.685","text": "문제가" },
        { "start": "20.650","text": "있어" },
        { "start": "21.320","text": "보였어요." }
]

var pistaKO4 = [
        { "start": "0.005","text": "다이나미타," },
        { "start": "1.291","text": "너는" },
        { "start": "1.763","text": "너무" },
        { "start": "2.212","text": "느려." },
        { "start": "3.320","text": "그거" },
        { "start": "3.892","text": "이리" },
        { "start": "4.250","text": "내." },
        { "start": "5.585","text": "이글이가" },
        { "start": "6.928","text": "으르렁거리면서" },
        { "start": "9.002","text": "다이나미타의" },
        { "start": "10.268","text": "손에서" },
        { "start": "11.734","text": "고무" },
        { "start": "12.347","text": "오리" },
        { "start": "12.901","text": "대포를" },
        { "start": "14.144","text": "뺏어왔어요." },
        { "start": "16.896","text": "다이나미타는" },
        { "start": "18.630","text": "조용히" },
        { "start": "19.420","text": "있었지만," },
        { "start": "21.068","text": "이글이가" },
        { "start": "22.383","text": "좀" },
        { "start": "22.826","text": "더" },
        { "start": "23.763","text": "좋은" },
        { "start": "24.361","text": "태도를" },
        { "start": "25.423","text": "보였으면" },
        { "start": "26.476","text": "좋겠다고" },
        { "start": "27.827","text": "생각했어요." }
        ]

var pistaKO5 = [
        { "start": "0.001","text": "결국," },
        { "start": "1.072","text": "요고타들은" },
        { "start": "2.710","text": "요고폴리스를" },
        { "start": "4.109","text": "침략하는" },
        { "start": "5.468","text": "적들을" },
        { "start": "6.719","text": "성공적으로" },
        { "start": "8.005","text": "막았어요." },
        { "start": "10.758","text": "이글이는" },
        { "start": "12.177","text": "굉장히" },
        { "start": "13.150","text": "신나" },
        { "start": "13.885","text": "보였지만," },
        { "start": "15.464","text": "다른" },
        { "start": "16.043","text": "친구들은" },
        { "start": "17.671","text": "그렇지" },
        { "start": "18.443","text": "않아" },
        { "start": "19.022","text": "보였어요." },
        { "start": "21.355","text": "우리가" },
        { "start": "21.773","text": "해냈어!" },
        { "start": "23.184","text": "우리의" },
        { "start": "23.609","text": "승리를" },
        { "start": "24.458","text": "기념하러" },
        { "start": "25.103","text": "가자." },
        { "start": "27.359","text": "이글이가" },
        { "start": "28.817","text": "들뜬" },
        { "start": "29.669","text": "목소리로" },
        { "start": "30.680","text": "말했지만," },
        { "start": "32.329","text": "친구들은" },
        { "start": "33.891","text": "이글이를" },
        { "start": "34.871","text": "따르지" },
        { "start": "35.609","text": "않았어요." }
]

var pistaKO6 = [
        { "start": "0.005","text": "친구들아?" },
        { "start": "1.412","text": "이글이가" },
        { "start": "2.509","text": "물었어요." },
        { "start": "4.788","text": "요고타들은" },
        { "start": "6.378","text": "이글이를" },
        { "start": "7.312","text": "혼자" },
        { "start": "8.139","text": "두고" },
        { "start": "8.885","text": "떠났어요." },
        { "start": "11.370","text": "이글이는" },
        { "start": "12.766","text": "자기가" },
        { "start": "13.717","text": "뭘" },
        { "start": "14.230","text": "잘못했는지" },
        { "start": "15.462","text": "몰라서" },
        { "start": "16.938","text": "그" },
        { "start": "17.267","text": "상황을" },
        { "start": "18.586","text": "이해할" },
        { "start": "19.246","text": "수" },
        { "start": "19.724","text": "없었어요." },
        { "start": "22.887","text": "이글아" },
        { "start": "24.009","text": "미안하지만," },
        { "start": "25.800","text": "친구들이" },
        { "start": "26.800","text": "너와" },
        { "start": "27.216","text": "있고" },
        { "start": "27.842","text": "싶지" },
        { "start": "28.426","text": "않아" },
        { "start": "28.851","text": "해." },
        { "start": "30.510","text": "루나가" },
        { "start": "31.534","text": "말했어요." },
        { "start": "33.953","text": "내가" },
        { "start": "34.337","text": "뭘" },
        { "start": "34.500","text": "했길래?"},
        { "start": "37.512","text": "너의" },
        { "start": "37.968","text": "태도" },
        { "start": "38.369","text": "때문이야" },
        { "start": "39.031","text": "이글아." },
        { "start": "40.330","text": "너는" },
        { "start": "41.300","text": "'부탁해'" },
        { "start": "42.594","text": "아니면" },
        { "start": "43.639","text": "'고마워'라고" },
        { "start": "45.187","text": "한" },
        { "start": "45.429","text": "번도" },
        { "start": "45.788","text": "말하지" },
        { "start": "46.254","text": "않았잖아." },
        { "start": "48.981","text": "루나가" },
        { "start": "50.134","text": "화난" },
        { "start": "50.800","text": "목소리로" },
        { "start": "51.786","text": "대답했어요." },
        { "start": "54.844","text": "그렇지만..." },
        { "start": "56.580","text": "난" },
        { "start": "58.100","text": "이글이는" },
        { "start": "59.284","text": "당황한" },
        { "start": "1:00.120","text": "목소리로" },
        { "start": "1:01.152","text": "말했어요." },
        { "start": "1:03.546","text": "이야기는" },
        { "start": "1:04.582","text": "계속됩니다." },
]


