var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]

var pistaES1 = [
            { "start": "0.291","text": "Nao" },
            {"start": "0.761","text": "y" },
            {"start": "0.931","text": "Tomiko" },
            {"start": "1.718","text": "estaban" },
            {"start": "2.259","text": "en" },
            {"start": "2.434","text": "una" },
            {"start": "2.656","text": "carrera" },
            {"start": "3.100","text": "de" },
            {"start": "3.254","text": "parejas." },
            {"start": "4.927","text": "El" },
            {"start": "5.143","text": "camino" },
            {"start": "5.264","text": "había" },
            {"start": "5.829","text": "estado" },
            {"start": "6.306","text": "lleno" },
            {"start": "6.731","text": "de" },
            {"start": "6.852","text": "obstáculos" },
            {"start": "8.138","text": "pero" },
            {"start": "8.235","text": "a" },
            {"start": "8.432","text": "pocos" },
            {"start": "8.837","text": "metros" },
            {"start": "9.263","text": "de" },
            {"start": "9.390","text": "llegar" },
            {"start": "9.668","text": "a" },
            {"start": "9.816","text": "la" },
            {"start": "9.945","text": "meta" },
            {"start": "10.825","text": "se" },
            {"start": "10.984","text": "encontraron" },
            {"start": "11.704","text": "con" },
            {"start": "11.832","text": "un" },
            {"start": "12.081","text": "río," },
            {"start": "13.238","text": "uno" },
            {"start": "13.564","text": "de" },
            {"start": "13.700","text": "los" },
            {"start": "13.906","text": "mayores" },
            {"start": "14.526","text": "obstáculos" },
            {"start": "15.378","text": "hasta" },
            {"start": "15.590","text": "el" },
            {"start": "15.768","text": "momento." }
];

var pistaEN1 = [
            { "start": "0.772","text": "Nao" },
            {"start": "1.173","text": "and" },
            {"start": "1.342","text": "Tomiko" },
            {"start": "1.991","text": "were" },
            {"start": "2.161","text": "competing" },
            {"start": "2.737","text": "in" },
            {"start": "2.829","text": "a" },
            {"start": "3.017","text": "two-person" },
            {"start": "3.752","text": "race." },
            {"start": "4.956","text": "The" },
            {"start": "5.101","text": "road" },
            {"start": "5.438","text": "was" },
            {"start": "5.773","text": "full" },
            {"start": "5.956","text": "of" },
            {"start": "6.088","text": "obstacles" },
            {"start": "7.239","text": "and" },
            {"start": "7.380","text": "just" },
            {"start": "7.597","text": "a" },
            {"start": "7.766","text": "few" },
            {"start": "7.994","text": "meters" },
            {"start": "8.388","text": "away" },
            {"start": "8.738","text": "from" },
            {"start": "8.896","text": "the" },
            {"start": "9.092","text": "finish" },
            {"start": "9.432","text": "line" },
            {"start": "10.000","text": "they" },
            {"start": "10.203","text": "found" },
            {"start": "10.445","text": "a" },
            {"start": "10.542","text": "river." },
            {"start": "11.417","text": "The" },
            {"start": "11.705","text": "biggest" },
            {"start": "12.349","text": "obstacle" },
            {"start": "12.988","text": "of" },
            {"start": "13.109","text": "all." }
];


var pistaES2 = [
            { "start": "0.135","text": "Nao" },
            {"start": "0.520","text": "se" },
            {"start": "0.560","text": "detuvo" },
            {"start": "0.747","text": "a" },
            {"start": "1.193","text": "observar" },
            {"start": "1.834","text": "lo" },
            {"start": "1.962","text": "que" },
            {"start": "2.055","text": "se" },
            {"start": "2.289","text": "encontraba" },
            {"start": "2.870","text": "frente" },
            {"start": "3.250","text": "a" },
            {"start": "3.361","text": "él" },
            {"start": "4.298","text": "y" },
            {"start": "4.487","text": "Tomiko" },
            {"start": "5.282","text": "empezó" },
            {"start": "5.851","text": "a" },
            {"start": "5.985","text": "desesperarse." },
            {"start": "8.921","text": "-¡Corre!" },
            {"start": "10.261","text": "No" },
            {"start": "10.601","text": "te" },
            {"start": "10.727","text": "detengas" },
            {"start": "12.608","text": "-dijo" },
            {"start": "14.750","text": "Espera," },
            {"start": "15.867","text": "es" },
            {"start": "15.975","text": "mejor" },
            {"start": "16.830","text": "pensar" },
            {"start": "17.480","text": "antes" },
            {"start": "17.891","text": "de" },
            {"start": "17.954","text": "actuar" },
            {"start": "20.410","text": "-dijo" },
            {"start": "20.799","text": "Nao" },
            {"start": "21.324","text": "tranquilamente." },
            {"start": "23.476","text": "-Nos" },
            {"start": "23.834","text": "van" },
            {"start": "24.000","text": "a" },
            {"start": "24.176","text": "ganar" },
            {"start": "26.230","text": "-Tomiko" },
            {"start": "26.754","text": "gritó" }
];

var pistaEN2 = [
            { "start": "0.580","text": "Nao" },
            {"start": "1.078","text": "stopped" },
            {"start": "1.484","text": "and" },
            {"start": "1.824","text": "stared." },
            {"start": "2.912","text": "Tomiko" },
            {"start": "3.429","text": "became" },
            {"start": "4.009","text": "desperate." },
            {"start": "5.038","text": "Run!" },
            {"start": "5.842","text": "Don't" },
            {"start": "6.078","text": "stop," },
            {"start": "6.988","text": "she" },
            {"start": "7.193","text": "said." },
            {"start": "8.222","text": "Wait," },
            {"start": "8.866","text": "it's" },
            {"start": "9.135","text": "better" },
            {"start": "9.481","text": "to" },
            {"start": "9.677","text": "think" },
            {"start": "10.057","text": "before" },
            {"start": "10.501","text": "you" },
            {"start": "10.642","text": "act," },
            {"start": "11.241","text": "said" },
            {"start": "11.557","text": "Nao" },
            {"start": "11.968","text": "calmly." },
            {"start": "13.388","text": "We" },
            {"start": "13.530","text": "are" },
            {"start": "13.729","text": "going" },
            {"start": "14.009","text": "to" },
            {"start": "14.224","text": "lose," },
            {"start": "15.071","text": "shouted" },
            {"start": "15.509","text": "Tomiko." }
];



var pistaES3 = [
            { "start": "0.030","text": "Nao" },
            {"start": "0.567","text": "no" },
            {"start": "0.820","text": "contestó" },
            {"start": "1.995","text": "siguio" },
            {"start": "2.487","text": "observando" },
            {"start": "3.047","text": "el" },
            {"start": "3.167","text": "río" },
            {"start": "3.525","text": "con" },
            {"start": "3.719","text": "detenimiento;" },
            {"start": "5.235","text": "buscaba" },
            {"start": "5.971","text": "una" },
            {"start": "6.289","text": "manera" },
            {"start": "6.920","text": "para" },
            {"start": "7.179","text": "pasar" },
            {"start": "7.550","text": "sobre" },
            {"start": "7.821","text": "él" },
            {"start": "8.274","text": "de" },
            {"start": "8.352","text": "la" },
            {"start": "8.466","text": "mejor" },
            {"start": "8.914","text": "forma." }
]

var pistaEN3 = [
            { "start": "0.561","text": "Nao" },
            {"start": "1.011","text": "didn't" },
            {"start": "1.319","text": "answer." },
            {"start": "2.496","text": "He" },
            {"start": "2.618","text": "kept" },
            {"start": "2.877","text": "staring" },
            {"start": "3.388","text": "at" },
            {"start": "3.537","text": "the" },
            {"start": "3.647","text": "river." },
            {"start": "4.655","text": "He" },
            {"start": "4.765","text": "was" },
            {"start": "4.938","text": "looking" },
            {"start": "5.437","text": "for" },
            {"start": "5.557","text": "the" },
            {"start": "5.812","text": "best" },
            {"start": "6.196","text": "way" },
            {"start": "6.492","text": "to" },
            {"start": "6.683","text": "cross" },
            {"start": "7.005","text": "over" },
            {"start": "7.421","text": "it." }
];



var pistaES4 = [
            { "start": "0.110","text": "-Yo" },
            { "start": "0.404","text": "me" },
            { "start": "0.679","text": "voy-"},
            { "start": "2.257","text": "dijo"},
            { "start": "2.628","text": "Tomiko"},
            { "start": "3.730","text": "y"},
            { "start": "3.905","text": "corrió"},
            { "start": "4.342","text": "hasta"},
            { "start": "4.732","text": "perderse"},
            { "start": "5.320","text": "en" },
            { "start": "5.391","text": "el"},
            { "start": "5.527","text": "horizonte;"},
            { "start": "7.540","text": "Nao"},
            { "start": "8.210","text": "siguió"},
            { "start": "8.786","text": "observando."}
            
]

var pistaEN4 = [
            { "start": "0.627","text": "I'm" },
            { "start": "0.970","text": "leaving" },
            { "start": "1.757","text": "said"},
            { "start": "2.059","text": "Tomiko"},
            { "start": "2.808","text": "as"},
            { "start": "2.976","text": "she"},
            { "start": "3.205","text": "ran"},
            { "start": "3.615","text": "until"},
            { "start": "4.072","text": "disappearing"},
            { "start": "4.720","text": "into"},
            { "start": "5.012","text": "the"},
            { "start": "5.175","text": "horizon."},
            { "start": "6.537","text": "Nao"},
            { "start": "7.038","text": "kept"},
            { "start": "7.371","text": "looking."}
            
]


var pistaES5 = [
            { "start": "0.164","text": "Tomiko" },
            { "start": "0.694","text": "estaba" },
            { "start": "1.154","text": "muy"},
            { "start": "1.713","text": "cansada,"},
            { "start": "3.417","text": "el"},
            { "start": "3.631","text": "agua"},
            { "start": "3.876","text": "del"},
            { "start": "4.120","text": "rio"},
            { "start": "4.644","text": "hacía"},
            { "start": "5.128","text": "pesados" },
            { "start": "5.654","text": "sus"},
            { "start": "5.907","text": "pasos,"},
            { "start": "7.172","text": "no"},
            { "start": "7.466","text": "sólo"},
            { "start": "7.875","text": "los"},
            { "start": "8.124","text": "de"},
            { "start": "8.242","text": "ella,"},
            { "start": "9.153","text": "también" },
            { "start": "9.663","text": "los"},
            { "start": "9.871","text": "del"},
            { "start": "10.076","text": "resto"},
            { "start": "10.449","text": "de"},
            { "start": "10.583","text": "los"},
            { "start": "10.741","text": "competidores."},
            { "start": "12.730","text": "Después"},
            { "start": "13.394","text": "de"},
            { "start": "13.515","text": "varios"},
            { "start": "13.878","text": "minutos"},
            { "start": "14.631","text": "sintío"},
            { "start": "15.321","text": "que"},
            { "start": "15.550","text": "algo"},
            { "start": "15.838","text": "la"},
            { "start": "15.985","text": "jalaba" },
            { "start": "17.813","text": "era"},
            { "start": "18.151","text": "la"},
            { "start": "18.267","text": "mano"},
            { "start": "18.601","text": "de"},
            { "start": "18.798","text": "Nao,"},
            { "start": "19.605","text": "ayudándola"},
            { "start": "20.243","text": "a" },
            { "start": "20.331","text": "subir"},
            { "start": "21.122","text": "a"},
            { "start": "21.254","text": "una"},
            { "start": "21.606","text": "roca."}
            
]



var pistaEN5 = [
            { "start": "0.568","text": "Tomiko" },
            { "start": "1.127","text": "was" },
            { "start": "1.443","text": "really" },
            { "start": "1.809","text": "tired" },
            { "start": "2.690","text": "and" },
            { "start": "2.814","text": "the" },
            { "start": "2.942","text": "river" },
            { "start": "3.266","text": "made" },
            { "start": "3.489","text": "her" },
            { "start": "3.614","text": "steps" },
            { "start": "4.014","text": "heavy." },
            { "start": "5.290","text": "After" },
            { "start": "5.611","text": "several" },
            { "start": "6.059","text": "minutes" },
            { "start": "6.663","text": "she" },
            { "start": "6.891","text": "felt" },
            { "start": "7.132","text": "someone" },
            { "start": "7.523","text": "pull" },
            { "start": "7.756","text": "her" },
            { "start": "7.896","text": "out." },
            { "start": "9.043","text": "it" },
            { "start": "9.185","text": "was" },
            { "start": "9.369","text": "Nao´s" },
            { "start": "9.837","text": "hand" },
            { "start": "10.224","text": "helping" },
            { "start": "10.639","text": "her" },
            { "start": "10.893","text": "from" },
            { "start": "11.028","text": "the" },
            { "start": "11.208","text": "top" },
            { "start": "11.479","text": "of" },
            { "start": "11.613","text": "a" },
            { "start": "11.730","text": "rock." }
            
]


var pistaES6 = [
            { "start": "0.114","text": "-¡Ganamos!" },
            { "start": "2.369","text": "¿Cómo" },
            { "start": "2.606","text": "lograste" },
            { "start": "3.179","text": "llegar" },
            { "start": "3.575","text": "hasta" },
            { "start": "3.891","text": "donde" },
            { "start": "4.032","text": "me" },
            { "start": "4.250","text": "encontraba?-" },
            { "start": "7.324","text": "-Facil," },
            { "start": "8.644","text": "el" },
            { "start": "8.938","text": "río" },
            { "start": "9.304","text": "estaba" },
            { "start": "9.824","text": "lleno" },
            { "start": "10.223","text": "de" },
            { "start": "10.480","text": "grandes" },
            { "start": "11.265","text": "rocas" },
            { "start": "12.510","text": "y" },
            { "start": "12.641","text": "salté" },
            { "start": "13.260","text": "sobre" },
            { "start": "13.700","text": "cada" },
            { "start": "14.021","text": "una" },
            { "start": "14.948","text": "en" },
            { "start": "15.312","text": "vez" },
            { "start": "15.362","text": "de" },
            { "start": "15.511","text": "caminar" },
            { "start": "16.051","text": "por" },
            { "start": "16.181","text": "el" },
            { "start": "16.317","text": "agua-" },
            { "start": "17.534","text": "respondió" },
            { "start": "18.158","text": "Nao" },
            { "start": "18.644","text": "con" },
            { "start": "18.837","text": "tranquilidad." },
            { "start": "21.642","text": "-Pero" },
            { "start": "22.993","text": "¿Como" },
            { "start": "23.260","text": "lo" },
            { "start": "23.436","text": "supiste?" },
            { "start": "25.056","text": "-dijo" },
            { "start": "25.722","text": "Tomiko," },
            { "start": "26.893","text": "algo" },
            { "start": "27.247","text": "sorprendida." },
            { "start": "28.994","text": "-Antes" },
            { "start": "29.421","text": "de" },
            { "start": "29.490","text": "actuar" },
            { "start": "30.293","text": "debemos" },
            { "start": "30.907","text": "ser" },
            { "start": "31.273","text": "pacientes," },
            { "start": "32.860","text": "lo" },
            { "start": "33.157","text": "importante" },
            { "start": "33.891","text": "no" },
            { "start": "34.060","text": "es" },
            { "start": "34.247","text": "ganar," },
            { "start": "35.193","text": "sino" },
            { "start": "35.711","text": "llegar." }
    ]


var pistaEN6 = [
            { "start": "0.562","text": "¡We" },
            { "start": "0.824","text": "won!" },
            { "start": "1.727","text": "How" },
            { "start": "1.910","text": "did" },
            { "start": "2.027","text": "you" },
            { "start": "2.183","text": "get" },
            { "start": "2.396","text": "to" },
            { "start": "2.566","text": "me?" },
            { "start": "3.603","text": "Easy!" },
            { "start": "4.545","text": "The" },
            { "start": "4.637","text": "river" },
            { "start": "5.030","text": "was" },
            { "start": "5.269","text": "filled" },
            { "start": "5.546","text": "with" },
            { "start": "5.829","text": "big" },
            { "start": "6.149","text": "rocks" },
            { "start": "6.917","text": "and" },
            { "start": "7.028","text": "I" },
            { "start": "7.240","text": "jumped" },
            { "start": "7.654","text": "over" },
            { "start": "7.985","text": "them" },
            { "start": "8.515","text": "instead" },
            { "start": "8.904","text": "of" },
            { "start": "9.060","text": "walking" },
            { "start": "9.451","text": "through" },
            { "start": "9.703","text": "water," },
            { "start": "10.495","text": "answered" },
            { "start": "10.913","text": "Nao." },
            { "start": "12.130","text": "But" },
            { "start": "12.855","text": "How" },
            { "start": "13.048","text": "did" },
            { "start": "13.188","text": "you" },
            { "start": "13.373","text": "figure" },
            { "start": "13.728","text": "that" },
            { "start": "14.048","text": "out?" },
            { "start": "14.736","text": "said" },
            { "start": "15.036","text": "Tomiko" },
            { "start": "15.707","text": "surprised." },
            { "start": "17.236","text": "We" },
            { "start": "17.374","text": "must" },
            { "start": "17.650","text": "be" },
            { "start": "17.828","text": "patient" },
            { "start": "18.479","text": "before" },
            { "start": "18.994","text": "we" },
            { "start": "19.184","text": "act." },
            { "start": "20.224","text": "The" },
            { "start": "20.298","text": "most" },
            { "start": "20.567","text": "important" },
            { "start": "21.127","text": "thing" },
            { "start": "21.488","text": "is" },
            { "start": "21.648","text": "to" },
            { "start": "21.772","text": "get" },
            { "start": "21.948","text": "to" },
            { "start": "22.028","text": "your" },
            { "start": "22.260","text": "destination" },
            { "start": "23.048","text": "safely," },
            { "start": "24.064","text": "not" },
            { "start": "24.363","text": "win" }
    ]


/*--------------------------------Corean--------------------------------*/

var pistaKO1 = [
            { "start": "0.000","text": "나오와" },
            { "start": "1.028","text": "토미코," },
            { "start": "2.431","text": "두" },
            { "start": "2.906","text": "요고타는" },
            { "start": "4.523","text": "두" },
            { "start": "4.807","text": "명이" },
            { "start": "5.474","text": "팀으로" },
            { "start": "6.357","text": "참가하는" },
            { "start": "7.400","text": "경주에서" },
            { "start": "8.967","text": "뛰고" },
            { "start": "9.700","text": "있었어요." },
            { "start": "11.614","text": "달리는" },
            { "start": "12.609","text": "도로" },
            { "start": "13.200","text": "위에는" },
            { "start": "14.543","text": "장애물이" },
            { "start": "15.726","text": "아주" },
            { "start": "16.859","text": "많이" },
            { "start": "17.423","text": "있었지만" },
            { "start": "18.986","text": "결승선까지는" },
            { "start": "21.045","text": "몇" },
            { "start": "21.417","text": "미터" },
            { "start": "22.085","text": "남지" },
            { "start": "23.087","text": "않았었어요." },
            { "start": "25.568","text": "그리고" },
            { "start": "26.473","text": "그" },
            { "start": "26.840","text": "둘은" },
            { "start": "27.950","text": "강이라는" },
            { "start": "29.366","text": "가장" },
            { "start": "30.107","text": "큰" },
            { "start": "30.568","text": "장애물을" },
            { "start": "31.943","text": "보게" },
            { "start": "32.581","text": "되었어요." }
] 

var pistaKO2 = [
            { "start": "0.000","text": "나오는" },
            { "start": "0.900","text": "멈춰서서" },
            { "start": "2.558","text": "강을" },
            { "start": "3.575","text": "바라보았어요." },
            { "start": "5.801","text": "토미코는" },
            { "start": "7.182","text": "마음이" },
            { "start": "8.054","text": "조급해졌어요." },
            { "start": "10.916","text": "뛰어!" },
            { "start": "11.920","text": "멈추지" },
            { "start": "12.604","text": "마." },
            { "start": "13.700","text": "토미코가" },
            { "start": "14.758","text": "말했어요." },
            { "start": "16.524","text": "기다려" },
            { "start": "17.102","text": "봐."},
            { "start": "18.125","text": "무작정" },
            { "start": "19.138","text": "뛰기" },
            { "start": "19.670","text": "전에" },
            { "start": "20.840","text": "무엇을" },
            { "start": "21.654","text": "할지" },
            { "start": "22.751","text": "미리" },
            { "start": "23.272","text": "생각해보자." },
            { "start": "25.404","text": "나오가" },
            { "start": "26.577","text": "아주" },
            { "start": "27.074","text": "침착하게" },
            { "start": "28.203","text": "말했어요." },
            { "start": "30.084","text": "우리는" },
            { "start": "30.579","text": "이러다" },
            { "start": "31.080","text": "질거야." },
            { "start": "32.832","text": "토미코가" },
            { "start": "33.902","text": "소리쳤어요." }
] 

var pistaKO3 = [
            { "start": "0.000","text": "나오는" },
            { "start": "0.877","text": "대답하지" },
            { "start": "1.851","text": "않고" },
            { "start": "3.032","text": "대신" },
            { "start": "4.191","text": "강을" },
            { "start": "5.051","text": "계속" },
            { "start": "5.813","text": "쳐다보고" },
            { "start": "6.879","text": "있었어요." },
            { "start": "8.586","text": "나오는" },
            { "start": "9.911","text": "강을" },
            { "start": "10.647","text": "건너갈" },
            { "start": "12.032","text": "가장" },
            { "start": "12.765","text": "좋은" },
            { "start": "13.350","text": "방법을" },
            { "start": "14.730","text": "찾고" },
            { "start": "15.400","text": "있었어요." }
] 

var pistaKO4 = [
            { "start": "0.005","text": "나는" },
            { "start": "0.663","text": "지금" },
            { "start": "1.134","text": "갈거야." },
            { "start": "2.784","text": "토미코가" },
            { "start": "4.070","text": "얘기했어요." },
            { "start": "5.946","text": "토미코는" },
            { "start": "7.073","text": "뛰어갔고" },
            { "start": "8.630","text": "곧" },
            { "start": "9.447","text": "수평선" },
            { "start": "10.572","text": "저" },
            { "start": "11.094","text": "너머로" },
            { "start": "12.191","text": "사라졌어요." },
            { "start": "14.327","text": "나오는" },
            { "start": "15.647","text": "계속" },
            { "start": "16.628","text": "강을" },
            { "start": "17.439","text": "보기만" },
            { "start": "18.193","text": "하고" },
            { "start": "18.912","text": "있었어요." }
] 

var pistaKO5 = [
            { "start": "0.001","text": "토미코는" },
            { "start": "1.157","text": "너무" },
            { "start": "1.789","text": "지쳤고" },
            { "start": "3.300","text": "강물을" },
            { "start": "4.310","text": "가로지르면서" },
            { "start": "5.882","text": "뛰는건" },
            { "start": "7.143","text": "어려웠어요." },
            { "start": "8.984","text": "몇" },
            { "start": "9.508","text": "분" },
            { "start": "9.900","text": "후에" },
            { "start": "11.008","text": "토미코는" },
            { "start": "12.145","text": "넘어졌고," },
            { "start": "13.430","text": "그" },
            { "start": "13.587","text": "순간," },
            { "start": "14.706","text": "누군가" },
            { "start": "15.863","text": "토미코를" },
            { "start": "16.904","text": "구해줬어요." },
            { "start": "18.860","text": "토미코를" },
            { "start": "19.897","text": "강물에서" },
            { "start": "21.029","text": "꺼내준" },
            { "start": "21.689","text": "건" },
            { "start": "22.585","text": "나오의" },
            { "start": "23.750","text": "손이었어요." },
            { "start": "26.861","text": "나오는" },
            { "start": "28.229","text": "바위" },
            { "start": "28.944","text": "위에서" },
            { "start": "30.178","text": "토미코를" },
            { "start": "31.279","text": "구해줬어요." },
] 

var pistaKO6 = [
            { "start": "0.000","text": "우리가" },
            { "start": "0.500","text": "이겼어!" },
            { "start": "1.941","text": "어떻게" },
            { "start": "2.574","text": "나를" },
            { "start": "3.112","text": "구해준거니?" },
            { "start": "5.807","text": "간단해!" },
            { "start": "7.260","text": "강에는" },
            { "start": "8.461","text": "큰" },
            { "start": "8.903","text": "바위가" },
            { "start": "9.831","text": "많이" },
            { "start": "10.170","text": "있었어." },
            { "start": "11.726","text": "난" },
            { "start": "12.291","text": "그래서" },
            { "start": "13.575","text": "강을" },
            { "start": "14.276","text": "뛰어서" },
            { "start": "15.121","text": "건너가지" },
            { "start": "15.904","text": "않고" },
            { "start": "17.100","text": "바위" },
            { "start": "17.833","text": "위를" },
            { "start": "18.776","text": "징검다리처럼" },
            { "start": "20.418","text": "건너서" },
            { "start": "21.076","text": "왔어."},
            { "start": "22.881","text": "나오가" },
            { "start": "23.780","text": "대답했어요." },
            { "start": "26.211","text": "너는..." },
            { "start": "27.361","text": "어떻게" },
            { "start": "28.188","text": "그걸" },
            { "start": "28.677","text": "알아낸거니?" },
            { "start": "30.563","text": "토미코가" },
            { "start": "31.735","text": "놀라서" },
            { "start": "32.500","text": "물었어요." },
            { "start": "34.534","text": "우리는" },
            { "start": "35.759","text": "무엇을" },
            { "start": "36.419","text": "할지" },
            { "start": "37.276","text": "충분히" },
            { "start": "38.037","text": "생각하고" },
            { "start": "39.350","text": "행동해야해." },
            { "start": "41.416","text": "이기는" },
            { "start": "42.051","text": "게" },
            { "start": "42.500","text": "중요한" },
            { "start": "43.134","text": "게" },
            { "start": "43.507","text": "아니라" },
            { "start": "44.650","text": "어떻게" },
            { "start": "45.532","text": "결승선까지" },
            { "start": "47.259","text": "안전하게" },
            { "start": "48.174","text": "가는지가" },
            { "start": "49.460","text": "중요한거야." }
] 

