var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]
 
 
 /*--------------------------------Spanish--------------------------------*/
  
  var pistaES1 = [
            {"start": "","text": "A" },
            {"start": "","text": "varios" },
            {"start": "","text": "kilómetros" },
            {"start": "","text": "de," },
            {"start": "","text": "Yogópolis" },
            {"start": "","text": "se" },
            {"start": "","text": "encuentra" },
            {"start": "","text": "un" },
            {"start": "","text": "viejo" },
            {"start": "","text": "castillo" },
            {"start": "","text": "deshabitado" },
            {"start": "","text": "con" },
            {"start": "","text": "un" },
            {"start": "","text": "enorme" },
            {"start": "","text": "y" },
            {"start": "","text": "oscuro" },
            {"start": "","text": "lago" },
            {"start": "","text": "donde" },
            {"start": "","text": "vive" },
            {"start": "","text": "una" },
            {"start": "","text": "criatura" },
            {"start": "","text": "muy" },
            {"start": "","text": "especial" }
  ]

  var pistaES2 = [
            {"start": "","text": "Aunque" },
            {"start": "","text": "nadie" },
            {"start": "","text": "la" },
            {"start": "","text": "ha," },
            {"start": "","text": "visto" },
            {"start": "","text": "a" },
            {"start": "","text": "la" },
            {"start": "","text": "luz" },
            {"start": "","text": "del" },
            {"start": "","text": "día" },
            {"start": "","text": "saben" },
            {"start": "","text": "de" },
            {"start": "","text": "su" },
            {"start": "","text": "existencia" },
            {"start": "","text": "La" },
            {"start": "","text": "gente" },
            {"start": "","text": "de" },
            {"start": "","text": "los" },
            {"start": "","text": "alrededores" },
            {"start": "","text": "le" },
            {"start": "","text": "teme" },
            {"start": "","text": "y" },
            {"start": "","text": "muchos" },
            {"start": "","text": "otros" },
            {"start": "","text": "cuentan" },
            {"start": "","text": "relatos" },
            {"start": "","text": "terribles" },
            {"start": "","text": "sobre" },
            {"start": "","text": "la" },
            {"start": "","text": "criatura" },
            {"start": "","text": "marina" }
 ]
    
 var pistaES3 = [
            {"start": "","text": "Deberíamos" },
            {"start": "","text": "correr" },
            {"start": "","text": "a" },
            {"start": "","text": "esa," },
            {"start": "","text": "horrible" },
            {"start": "","text": "criatura" },
            {"start": "","text": "dijo" },
            {"start": "","text": "un" },
            {"start": "","text": "Bean" },
            {"start": "","text": "Sí" },
            {"start": "","text": "gritó" },
            {"start": "","text": "otro" },
            {"start": "","text": "Por" },
            {"start": "","text": "que" },
            {"start": "","text": "la" },
            {"start": "","text": "van" },
            {"start": "","text": "a" },
            {"start": "","text": "correr" },
            {"start": "","text": "Les" },
            {"start": "","text": "ha" },
            {"start": "","text": "hecho" },
            {"start": "","text": "algo" },
            {"start": "","text": "interrumpió" },
            {"start": "","text": "Thefannie" }
 ]
 
 var pistaES4 = [
            {"start": "","text": "Dicen" },
            {"start": "","text": "que" },
            {"start": "","text": "es" },
            {"start": "","text": "horrible" },
            {"start": "","text": "dijo" },
            {"start": "","text": "un" },
            {"start": "","text": "Bean" },
            {"start": "","text": "y" },
            {"start": "","text": "dicen" },
            {"start": "","text": "que" },
            {"start": "","text": "por" },
            {"start": "","text": "las" },
            {"start": "","text": "noches" },
            {"start": "","text": "espanta" },
            {"start": "","text": "a" },
            {"start": "","text": "la" },
            {"start": "","text": "gente" },
            {"start": "","text": "que" },
            {"start": "","text": "camina" },
            {"start": "","text": "cerca" },
            {"start": "","text": "del" },
            {"start": "","text": "lago" },
            {"start": "","text": "gritó" },
            {"start": "","text": "Alguno" },
            {"start": "","text": "de" },
            {"start": "","text": "ustedes" },
            {"start": "","text": "lo" },
            {"start": "","text": "conoce" },
            {"start": "","text": "dijo" },
            {"start": "","text": "Thefannie" },
            {"start": "","text": "Todos" },
            {"start": "","text": "se" },
            {"start": "","text": "vieron" },
            {"start": "","text": "entre" },
            {"start": "","text": "sí" },
            {"start": "","text": "pero" },
            {"start": "","text": "nadie" },
            {"start": "","text": "respondió" },
            {"start": "","text": "nadie" },
            {"start": "","text": "lo" },
            {"start": "","text": "conocía" },
            {"start": "","text": "realmente" },
            {"start": "","text": "No" },
            {"start": "","text": "creen" },
            {"start": "","text": "que" },
            {"start": "","text": "es" },
            {"start": "","text": "algo" },
            {"start": "","text": "injusto" },
            {"start": "","text": "hablar" },
            {"start": "","text": "mal" },
            {"start": "","text": "de" },
            {"start": "","text": "alguien" },
            {"start": "","text": "que" },
            {"start": "","text": "no" },
            {"start": "","text": "conocen" }
 ]
      
 var pistaES5 = [
            {"start": "","text": "Miren" },
            {"start": "","text": "Ahí" },
            {"start": "","text": "está" },
            {"start": "","text": "dijo" },
            {"start": "","text": "uno" },
            {"start": "","text": "de" },
            {"start": "","text": "los" },
            {"start": "","text": "Beans" },
            {"start": "","text": "Todos" },
            {"start": "","text": "voltearon" },
            {"start": "","text": "a" },
            {"start": "","text": "ver" },
            {"start": "","text": "a" },
            {"start": "","text": "la" },
            {"start": "","text": "criatura" },
            {"start": "","text": "marina" },
            {"start": "","text": "No" },
            {"start": "","text": "se" },
            {"start": "","text": "ve" },
            {"start": "","text": "tan" },
            {"start": "","text": "horrible" },
            {"start": "","text": "y" },
            {"start": "","text": "espantoso" },
            {"start": "","text": "como" },
            {"start": "","text": "me" },
            {"start": "","text": "habían" },
            {"start": "","text": "contado" },
            {"start": "","text": "dijo" },
            {"start": "","text": "uno" },
            {"start": "","text": "de" },
            {"start": "","text": "los" },
            {"start": "","text": "Beans" },
            {"start": "","text": "Hola" },
            {"start": "","text": "mi" },
            {"start": "","text": "nombre" },
            {"start": "","text": "es" },
            {"start": "","text": "Arthurius" },
            {"start": "","text": "Yo" },
            {"start": "","text": "soy" },
            {"start": "","text": "Thefannie" },
            {"start": "","text": "Yo" },
            {"start": "","text": "soy" },
            {"start": "","text": "Aji" },
            {"start": "","text": "respondió" },
            {"start": "","text": "la" },
            {"start": "","text": "criatura" },
            {"start": "","text": "marina" }
]
 
var pistaES6 = [
            {"start": "","text": "Durante" },
            {"start": "","text": "esa" },
            {"start": "","text": "noche" },
            {"start": "","text": "todos" },
            {"start": "","text": "intercambiaron" },
            {"start": "","text": "ideas" },
            {"start": "","text": "e" },
            {"start": "","text": "historias" },
            {"start": "","text": "se" },
            {"start": "","text": "presentaron" },
            {"start": "","text": "y" },
            {"start": "","text": "descubrieron" },
            {"start": "","text": "que" },
            {"start": "","text": "el" },
            {"start": "","text": "pequeño" },
            {"start": "","text": "Aji" },
            {"start": "","text": "sólo" },
            {"start": "","text": "era" },
            {"start": "","text": "una" },
            {"start": "","text": "criatura" },
            {"start": "","text": "tímida" },
            {"start": "","text": "y" },
            {"start": "","text": "sin" },
            {"start": "","text": "amigos" },
            {"start": "","text": "Desde" },
            {"start": "","text": "ese" },
            {"start": "","text": "día" },
            {"start": "","text": "los" },
            {"start": "","text": "Beans" },
            {"start": "","text": "aprendieron" },
            {"start": "","text": "a" },
            {"start": "","text": "no" },
            {"start": "","text": "juzgar" },
            {"start": "","text": "por" },
            {"start": "","text": "las" },
            {"start": "","text": "apariencias" },
            {"start": "","text": "ni" },
            {"start": "","text": "a" },
            {"start": "","text": "fiarse" },
            {"start": "","text": "de" },
            {"start": "","text": "los" },
            {"start": "","text": "relatos" },
            {"start": "","text": "de" },
            {"start": "","text": "terceras" },
            {"start": "","text": "personas" }
]


/*--------------------------------English--------------------------------*/

var pistaEN1 = [
             {"start":"","text": "Far" },
             {"start":"","text": "away" },
             {"start":"","text": "from" },
             {"start":"","text": "Yogopolis" },
             {"start":"","text": "there" },
             {"start":"","text": "was" },
             {"start":"","text": "an" },
             {"start":"","text": "old" },
             {"start":"","text": "abandoned" },
             {"start":"","text": "castle" },
             {"start":"","text": "with" },
             {"start":"","text": "a" },
             {"start":"","text": "dark" },
             {"start":"","text": "lake" },
             {"start":"","text": "where" },
             {"start":"","text": "a" },
             {"start":"","text": "special" },
             {"start":"","text": "creature" },
             {"start":"","text": "lived" }
]

var pistaEN2 = [
             {"start":"","text": "Although" },
             {"start":"","text": "no" },
             {"start":"","text": "one" },
             {"start":"","text": "had" },
             {"start":"","text": "seen" },
             {"start":"","text": "it" },
             {"start":"","text": "during" },
             {"start":"","text": "the" },
             {"start":"","text": "daylight" },
             {"start":"","text": "people" },
             {"start":"","text": "were" },
             {"start":"","text": "afraid" },
             {"start":"","text": "of" },
             {"start":"","text": "the" },
             {"start":"","text": "creature" },
             {"start":"","text": "Many" },
             {"start":"","text": "told" },
             {"start":"","text": "horrible" },
             {"start":"","text": "stories" },
             {"start":"","text": "about" },
             {"start":"","text": "the" },
             {"start":"","text": "creature" },
             {"start":"","text": "in" },
             {"start":"","text": "the" },
             {"start":"","text": "lake" }
             
]

var pistaEN3 = [
             {"start":"","text": "We" },
             {"start":"","text": "should" },
             {"start":"","text": "make" },
             {"start":"","text": "that" },
             {"start":"","text": "horrible" },
             {"start":"","text": "creature" },
             {"start":"","text": "leave" },
             {"start":"","text": "said" },
             {"start":"","text": "a" },
             {"start":"","text": "Bean" },
             {"start":"","text": "Yes" },
             {"start":"","text": "another" },
             {"start":"","text": "screamed" },
             {"start":"","text": "Why" },
             {"start":"","text": "do" },
             {"start":"","text": "you" },
             {"start":"","text": "want" },
             {"start":"","text": "it" },
             {"start":"","text": "to" },
             {"start":"","text": "leave" },
             {"start":"","text": "Has" },
             {"start":"","text": "it" },
             {"start":"","text": "done" },
             {"start":"","text": "something" },
             {"start":"","text": "to" },
             {"start":"","text": "you" },
             {"start":"","text": "Thefannie" },
             {"start":"","text": "interrupted" }
            
]

var pistaEN4 = [
            {"start":"","text": "They" },
            {"start":"","text": "say" },
            {"start":"","text": "it's" },
            {"start":"","text": "horrible" },
            {"start":"","text": "said" },
            {"start":"","text": "a" },
            {"start":"","text": "Bean" },
            {"start":"","text": "They" },
            {"start":"","text": "say" },
            {"start":"","text": "it" },
            {"start":"","text": "scares" },
            {"start":"","text": "people" },
            {"start":"","text": "by" },
            {"start":"","text": "the" },
            {"start":"","text": "lake" },
            {"start":"","text": "at" },
            {"start":"","text": "night" },
            {"start":"","text": "screamed" },
            {"start":"","text": "another" },
            {"start":"","text": "Bean" },
            {"start":"","text": "Do" },
            {"start":"","text": "any" },
            {"start":"","text": "of" },
            {"start":"","text": "you" },
            {"start":"","text": "know" },
            {"start":"","text": "the" },
            {"start":"","text": "creature" },
            {"start":"","text": "said" },
            {"start":"","text": "Thefannie" },
            {"start":"","text": "They" },
            {"start":"","text": "looked" },
            {"start":"","text": "at" },
            {"start":"","text": "each" },
            {"start":"","text": "other" },
            {"start":"","text": "but" },
            {"start":"","text": "nobody" },
            {"start":"","text": "answered" },
            {"start":"","text": "No" },
            {"start":"","text": "one" },
            {"start":"","text": "really" },
            {"start":"","text": "knew" },
            {"start":"","text": "the" },
            {"start":"","text": "creature" },
            {"start":"","text": "Don't" },
            {"start":"","text": "you" },
            {"start":"","text": "think" },
            {"start":"","text": "it's" },
            {"start":"","text": "unfair" },
            {"start":"","text": "to" },
            {"start":"","text": "talk" },
            {"start":"","text": "about" },
            {"start":"","text": "someone" },
            {"start":"","text": "you" },
            {"start":"","text": "don't" },
            {"start":"","text": "know" }   
]
 
var pistaEN5 = [
            {"start":"","text": "Look" },
            {"start":"","text": "There" },
            {"start":"","text": "it" },
            {"start":"","text": "is" },
            {"start":"","text": "said" },
            {"start":"","text": "one" },
            {"start":"","text": "of" },
            {"start":"","text": "the" },
            {"start":"","text": "Beans" },
            {"start":"","text": "Everybody" },
            {"start":"","text": "turned" },
            {"start":"","text": "to" },
            {"start":"","text": "see" },
            {"start":"","text": "the" },
            {"start":"","text": "creature" },
            {"start":"","text": "in" },
            {"start":"","text": "the" },
            {"start":"","text": "lake" },
            {"start":"","text": "it" },
            {"start":"","text": "doesn't" },
            {"start":"","text": "look" },
            {"start":"","text": "as" },
            {"start":"","text": "scary" },
            {"start":"","text": "and" },
            {"start":"","text": "horrible" },
            {"start":"","text": "as" },
            {"start":"","text": "I" },
            {"start":"","text": "was" },
            {"start":"","text": "told" },
            {"start":"","text": "said" },
            {"start":"","text": "a" },
            {"start":"","text": "Bean" },
            {"start":"","text": "Hi" },
            {"start":"","text": "My" },
            {"start":"","text": "name" },
            {"start":"","text": "is" },
            {"start":"","text": "Arthurius" },
            {"start":"","text": "I'm" },
            {"start":"","text": "Thefannie" },
            {"start":"","text": "I'm" },
            {"start":"","text": "Aji" },
            {"start":"","text": "said" },
            {"start":"","text": "the" },
            {"start":"","text": "creature" }
]
  
var pistaEN6 = [
            {"start":"","text": "That" },
            {"start":"","text": "night" },
            {"start":"","text": "everyone" },
            {"start":"","text": "shared" },
            {"start":"","text": "ideas" },
            {"start":"","text": "and" },
            {"start":"","text": "stories" },
            {"start":"","text": "They" },
            {"start":"","text": "realized" },
            {"start":"","text": "little" },
            {"start":"","text": "Aji" },
            {"start":"","text": "was" },
            {"start":"","text": "only" },
            {"start":"","text": "a" },
            {"start":"","text": "shy" },
            {"start":"","text": "lonely" },
            {"start":"","text": "creature" },
            {"start":"","text": "From" },
            {"start":"","text": "that" },
            {"start":"","text": "day" },
            {"start":"","text": "on" },
            {"start":"","text": "the" },
            {"start":"","text": "Beans" },
            {"start":"","text": "learned" },
            {"start":"","text": "not" },
            {"start":"","text": "to" },
            {"start":"","text": "judge" },
            {"start":"","text": "others" },
            {"start":"","text": "by" },
            {"start":"","text": "their" },
            {"start":"","text": "loos" },
            {"start":"","text": "or" },
            {"start":"","text": "trust" },
            {"start":"","text": "everything" },
            {"start":"","text": "people" },
            {"start":"","text": "say" }
]


/*--------------------------------Corean--------------------------------*/

var pistaKO1 = [
            { "start": "0.069","text": "요고폴리스에서" },
            { "start": "1.888","text": "아주" },
            { "start": "2.579","text": "멀리" },
            { "start": "3.325","text": "떨어진" },
            { "start": "3.879","text": "곳에," },
            { "start": "5.309","text": "아무도" },
            { "start": "6.127","text": "살지" },
            { "start": "6.862","text": "않는" },
            { "start": "7.988","text": "오래된" },
            { "start": "8.813","text": "성이" },
            { "start": "9.550","text": "있었어요." },
            { "start": "11.563","text": "그" },
            { "start": "11.969","text": "성" },
            { "start": "12.448","text": "안에는" },
            { "start": "13.900","text": "검은" },
            { "start": "14.682","text": "호수가" },
            { "start": "15.768","text": "있었고" },
            { "start": "17.360","text": "그" },
            { "start": "17.790","text": "호수" },
            { "start": "18.418","text": "안에는" },
            { "start": "19.781","text": "특별한" },
            { "start": "20.750","text": "생물이" },
            { "start": "22.012","text": "살고" },
            { "start": "22.826","text": "있었어요." }
]

var pistaKO2 = [
            { "start": "0.008","text": "해가" },
            { "start": "1.195","text": "떠" },
            { "start": "1.490","text": "있을" },
            { "start": "2.033","text": "때" },
            { "start": "2.888","text": "아무도" },
            { "start": "3.835","text": "그" },
            { "start": "4.224","text": "생물을" },
            { "start": "5.492","text": "본" },
            { "start": "5.782","text": "적이" },
            { "start": "6.395","text": "없지만," },
            { "start": "8.021","text": "모두" },
            { "start": "9.128","text": "그" },
            { "start": "9.591","text": "생물을" },
            { "start": "10.528","text": "두려워했어요." },
            { "start": "13.052","text": "많은" },
            { "start": "13.836","text": "사람들이" },
            { "start": "15.334","text": "호수에" },
            { "start": "16.221","text": "사는" },
            { "start": "16.952","text": "생물에" },
            { "start": "17.919","text": "대한" },
            { "start": "19.178","text": "무시무시한" },
            { "start": "20.609","text": "이야기를" },
            { "start": "21.884","text": "나누었어요." }
]

var pistaKO3 = [
            { "start": "0.015","text": "우리는" },
            { "start": "1.168","text": "그" },
            { "start": "1.557","text": "무서운" },
            { "start": "2.165","text": "생물을" },
            { "start": "2.924","text": "내쫓아야" },
            { "start": "3.850","text": "해." },
            { "start": "5.095","text": "빈이가" },
            { "start": "5.994","text": "말했어요." },
            { "start": "8.317","text": "맞아!" },
            { "start": "9.804","text": "다른" },
            { "start": "10.430","text": "빈이가" },
            { "start": "11.427","text": "소리쳤어요." },
            { "start": "13.818","text": "왜" },
            { "start": "14.206","text": "그" },
            { "start": "14.517","text": "생물을" },
            { "start": "15.273","text": "내쫓아야" },
            { "start": "16.157","text": "해?" },
            { "start": "17.190","text": "우리에게" },
            { "start": "18.106","text": "아무런" },
            { "start": "18.819","text": "잘못도" },
            { "start": "19.617","text": "하지" },
            { "start": "20.270","text": "않았는걸?" },
            { "start": "21.865","text": "티파니가" },
            { "start": "23.155","text": "중간에" },
            { "start": "24.020","text": "말했어요." }
]

var pistaKO4 = [
            { "start": "0.014","text": "그" },
            { "start": "0.356","text": "동물은" },
            { "start": "1.470","text": "너무" },
            { "start": "2.144","text": "무섭다고" },
            { "start": "2.857","text": "했어." },
            { "start": "4.522","text": "빈이가" },
            { "start": "5.414","text": "말했어요." },
            { "start": "8.069","text": "그" },
            { "start": "8.421","text": "동물이" },
            { "start": "9.625","text": "밤에" },
            { "start": "10.361","text": "호수를" },
            { "start": "11.068","text": "지나가는" },
            { "start": "11.921","text": "사람들을" },
            { "start": "13.197","text": "놀래킨다고" },
            { "start": "14.457","text": "들었어." },
            { "start": "16.483","text": "다른" },
            { "start": "17.090","text": "빈이가" },
            { "start": "18.116","text": "소리쳤어요." },
            { "start": "20.501","text": "너희" },
            { "start": "20.961","text": "중" },
            { "start": "21.464","text": "누구라도" },
            { "start": "22.380","text": "그" },
            { "start": "22.709","text": "생물을" },
            { "start": "23.442","text": "아는" },
            { "start": "23.785","text": "사람이" },
            { "start": "24.500","text": "있니?" },
            { "start": "25.771","text": "티파니가" },
            { "start": "26.877","text": "물었어요." },
            { "start": "28.672","text": "모두들" },
            { "start": "29.483","text": "서로를" },
            { "start": "30.341","text": "쳐다보기만" },
            { "start": "31.515","text": "하고" },
            { "start": "32.562","text": "대답을" },
            { "start": "33.422","text": "하지" },
            { "start": "34.384","text": "못했어요." },
            { "start": "35.975","text": "아무도" },
            { "start": "37.304","text": "그" },
            { "start": "37.626","text": "생물을" },
            { "start": "38.600","text": "직접" },
            { "start": "39.335","text": "알지" },
            { "start": "40.213","text": "못했거든요." },
            { "start": "42.520","text": "알지도" },
            { "start": "43.311","text": "못하는" },
            { "start": "44.075","text": "사람에" },
            { "start": "44.739","text": "대해서" },
            { "start": "45.510","text": "말을" },
            { "start": "45.974","text": "하는" },
            { "start": "46.381","text": "건" },
            { "start": "46.963","text": "불공평하지" },
            { "start": "48.150","text": "않아?" },
]

var pistaKO5 = [
            { "start": "0.054","text": "저길" },
            { "start": "0.532","text": "봐!" },
            { "start": "1.417","text": "저기" },
            { "start": "1.890","text": "있다." },
            { "start": "3.371","text": "한" },
            { "start": "3.859","text": "빈이가" },
            { "start": "4.660","text": "말했어요." },
            { "start": "6.250","text": "모두들" },
            { "start": "7.419","text": "고개를" },
            { "start": "8.190","text": "돌려서" },
            { "start": "9.446","text": "호수에" },
            { "start": "10.216","text": "산다는" },
            { "start": "11.335","text": "생물을" },
            { "start": "12.227","text": "보았어요." },
            { "start": "14.221","text": "내" },
            { "start": "14.581","text": "생각하고는" },
            { "start": "15.922","text": "전혀" },
            { "start": "16.401","text": "다르게" },
            { "start": "17.577","text": "무섭지도" },
            { "start": "18.375","text": "않고" },
            { "start": "19.191","text": "못생기지도" },
            { "start": "20.190","text": "않았네." },
            { "start": "21.940","text": "한" },
            { "start": "22.399","text": "빈이가" },
            { "start": "23.337","text": "말했어요." },
            { "start": "25.126","text": "안녕!" },
            { "start": "26.261","text": "나는" },
            { "start": "26.890","text": "알투리우스야." },
            { "start": "29.776","text": "나는" },
            { "start": "30.723","text": "티파니야." },
            { "start": "33.035","text": "나는" },
            { "start": "34.219","text": "아히라고" },
            { "start": "35.114","text": "해." },
            { "start": "36.507","text": "생물이" },
            { "start": "37.778","text": "자기" },
            { "start": "38.371","text": "소개를" },
            { "start": "39.116","text": "했어요." }
]

var pistaKO6 = [
            { "start": "0.028","text": "그날" },
            { "start": "0.543","text": "밤," },
            { "start": "1.405","text": "모두들" },
            { "start": "2.604","text": "자기의" },
            { "start": "3.395","text": "생각과" },
            { "start": "4.458","text": "이야기를" },
            { "start": "5.460","text": "나누었어요." },
            { "start": "7.476","text": "다들" },
            { "start": "8.690","text": "작은" },
            { "start": "9.389","text": "아히는" },
            { "start": "10.777","text": "그저" },
            { "start": "11.423","text": "수줍고" },
            { "start": "12.430","text": "외로운" },
            { "start": "13.285","text": "친구라는" },
            { "start": "14.172","text": "걸" },
            { "start": "14.767","text": "알게" },
            { "start": "15.375","text": "되었어요." },
            { "start": "17.574","text": "그날" },
            { "start": "18.191","text": "이후로," },
            { "start": "19.416","text": "빈이들은" },
            { "start": "20.775","text": "절대" },
            { "start": "22.087","text": "다른" },
            { "start": "22.586","text": "사람의" },
            { "start": "23.566","text": "외모를" },
            { "start": "24.392","text": "보고" },
            { "start": "25.004","text": "평가하거나" },
            { "start": "26.695","text": "다른" },
            { "start": "27.150","text": "사람들이" },
            { "start": "28.510","text": "하는" },
            { "start": "29.107","text": "얘기를" },
            { "start": "30.276","text": "모두" },
            { "start": "30.924","text": "믿지" },
            { "start": "31.550","text": "않기로" },
            { "start": "32.534","text": "결심했어요." }

]


