var pistaES0 = [{ "start": "0.000","text": "empty" }]
 var pistaEN0 = [{ "start": "0.000","text": "empty" }]
 var pistaPT0 = [{ "start": "0.000","text": "empty" }]
 var pistaZH0 = [{ "start": "0.000","text": "empty" }]
 var pistaJA0 = [{ "start": "0.000","text": "empty" }]
 var pistaKO0 = [{ "start": "0.000","text": "empty" }]
 
 
 /*--------------------------------Spanish--------------------------------*/
  
  
  var pistaES1 = [
            {"start": "0.149","text": "Despues" },
            {"start": "0.714","text": "de" },
            {"start": "0.884","text": "la" },
            {"start": "0.959","text": "gran" },
            {"start": "1.268","text": "batalla" },
            {"start": "2.248","text": "todos" },
            {"start": "2.642","text": "fueron" },
            {"start": "2.983","text": "a" },
            {"start": "3.058","text": "celebrar" },
            {"start": "3.697","text": "a" },
            {"start": "3.814","text": "la" },
            {"start": "3.953","text": "sala" },
            {"start": "4.337","text": "de" },
            {"start": "4.539","text": "juegos" },
            {"start": "4.912","text": "de" },
            {"start": "5.061","text": "la" },
            {"start": "5.189","text": "Yogomansion" },
            {"start": "7.437","text": "Esperen" },
            {"start": "8.087","text": "amigos" },
            {"start": "9.803","text": "dijo" },
            {"start": "10.293","text": "Eagle" },
            {"start": "12.157","text": "Todos" },
            {"start": "12.488","text": "se" },
            {"start": "12.766","text": "comportaron" },
            {"start": "13.585","text": "extraños" },
            {"start": "14.224","text": "con" },
            {"start": "14.416","text": "el." }
  ]
             
  var pistaES2 = [
      
            {"start": "0.288","text": "Eagle" },
            {"start": "0.991","text": "le" },
            {"start": "1.215","text": "pidio" },
            {"start": "1.630","text": "un" },
            {"start": "1.694","text": "vaso" },
            {"start": "1.982","text": "de" },
            {"start": "2.131","text": "agua" },
            {"start": "2.250","text": "de" },
            {"start": "2.472","text": "frutas" },
            {"start": "3.090","text": "a" },
            {"start": "3.260","text": "Dinamita" },
            {"start": "4.464","text": "pero" },
            {"start": "4.731","text": "el" },
            {"start": "5.168","text": "parecia" },
            {"start": "5.956","text": "no" },
            {"start": "6.169","text": "escucharlo" }
 ];
      
 var pistaES3 = [
             { "start": "0.085","text": "Eagle" },
             { "start": "0.597","text": "intento" },
             { "start": "1.065","text": "platicar" },
             { "start": "1.609","text": "con"},
             { "start": "1.811","text": "Oof"},
             { "start": "2.110","text": "sobre"},
             { "start": "2.515","text": "la"},
             { "start": "2.717","text": "batalla"},
             { "start": "3.751","text": "pero"},
             { "start": "4.006","text": "el"},
             { "start": "4.198","text": "se"},
             { "start": "4.475","text": "dio"},
             { "start": "4.837","text": "media"},
             { "start": "5.178","text": "vuelta"},
             { "start": "6.222","text": "parecia"},
             { "start": "6.798","text": "molesto"}
             
 ]
 
  var pistaES4 = [
             {"start": "0.244","text": "Eagle" },
             {"start": "0.703","text": "desesperado" },
             {"start": "1.737","text": "y" },
             {"start": "1.897","text": "algo" },
             {"start": "2.142","text": "afligido" },
             {"start": "3.165","text": "camino" },
             {"start": "3.612","text": "hacia" },
             {"start": "3.996","text": "Luna" },
             {"start": "4.592","text": "y" },
             {"start": "4.688","text": "le" },
             {"start": "4.880","text": "pregunto" },
             {"start": "6.990","text": "Que" },
             {"start": "7.118","text": "esta" },
             {"start": "7.480","text": "pasando" },
             {"start": "8.108","text": "Luna" },
             {"start": "9.131","text": "Nadie" },
             {"start": "9.675","text": "me" },
             {"start": "9.771","text": "hace" },
             {"start": "10.154","text": "caso" },
             {"start": "10.847","text": "simplemente" },
             {"start": "11.763","text": "me" },
             {"start": "11.870","text": "ignoran" },
             {"start": "13.724","text": "Que" },
             {"start": "13.915","text": "me" },
             {"start": "14.107","text": "hicieron" },
             {"start": "14.565","text": "los" },
             {"start": "14.704","text": "extraterrestres" },
             {"start": "15.620","text": "en" },
             {"start": "15.769","text": "la" },
             {"start": "15.844","text": "batalla" },
             {"start": "18.561","text": "No" },
             {"start": "18.913","text": "pasa" },
             {"start": "19.296","text": "nada" },
             {"start": "19.658","text": "Eagle" },
             {"start": "20.319","text": "eres" },
             {"start": "20.756","text": "tu" },
             {"start": "21.523","text": "el" },
             {"start": "21.693","text": "equipo" },
             {"start": "22.205","text": "esta" },
             {"start": "22.407","text": "enojado"},
             {"start": "22.972","text": "contigo"},
             {"start": "23.686","text": "porque"},
             {"start": "24.048","text": "no"},
             {"start": "24.272","text": "pides"},
             {"start": "24.560","text": "las"},
             {"start": "24.805","text": "cosas"},
             {"start": "25.188","text": "por"},
             {"start": "25.465","text": "favor"}
 ]
       
 var pistaES5 = [
             { "start": "0.405","text": "Eagle" },
             { "start": "0.874","text": "volvio" },
             { "start": "1.289","text": "hacia" },
             { "start": "1.481","text": "Dinamita" },
             { "start": "2.440","text": "y" },
             { "start": "2.674","text": "otra" },
             { "start": "2.909","text": "vez" },
             { "start": "3.143","text": "le" },
             { "start": "3.324","text": "pidio" },
             { "start": "3.623","text": "un" },
             { "start": "3.932","text": "vaso" },
             { "start": "4.337","text": "de" },
             { "start": "4.464","text": "agua" },
             { "start": "4.720","text": "de" },
             { "start": "4.827","text": "frutas" },
             { "start": "7.171","text": "Dinamita" },
             { "start": "8.481","text": "Puedes" },
             { "start": "8.844","text": "regalarme" },
             { "start": "9.558","text": "agua" },
             { "start": "10.719","text": "por" },
             { "start": "10.847","text": "favor" },
             { "start": "13.415","text": "Todos" },
             { "start": "13.756","text": "los" },
             { "start": "13.969","text": "yogotars" },
             { "start": "14.651","text": "voltearon" },
             { "start": "15.332","text": "hacia" },
             { "start": "15.716","text": "Eagle" },
             { "start": "16.291","text": "al" },
             { "start": "16.505","text": "escuchar" },
             { "start": "17.091","text": "por" },
             { "start": "17.218","text": "favor" },
             { "start": "19.999","text": "Oof" },
             { "start": "20.426","text": "por" },
             { "start": "20.553","text": "su" },
             { "start": "20.798","text": "parte" },
             { "start": "21.651","text": "inicio" },
             { "start": "22.109","text": "una" },
             { "start": "22.365","text": "platica" },
             { "start": "22.834","text": "con" },
             { "start": "22.972","text": "el" },
             { "start": "23.643","text": "como" },
             { "start": "23.867","text": "si" },
             { "start": "24.176","text": "nada" },
             { "start": "24.634","text": "hubiera" },
             { "start": "25.114","text": "pasado" }
 ]
      
 var pistaES6 = [
            
            { "start": "0.554","text": "Gracias" },
            { "start": "1.247","text": "Luna" },
            { "start": "2.600","text": "dijo" },
            { "start": "3.079","text": "Eagle" },
            { "start": "5.072","text": "De" },
            { "start": "5.338","text": "nada" },
            { "start": "6.830","text": "respondio" },
            { "start": "7.565","text": "Luna" },
            { "start": "9.249","text": "Todos" },
            { "start": "9.632","text": "aqui" },
            { "start": "9.930","text": "nos" },
            { "start": "10.175","text": "esforzamos" },
            { "start": "10.847","text": "por" },
            { "start": "11.028","text": "convivir" },
            { "start": "11.486","text": "en" },
            { "start": "11.699","text": "paz" },
            { "start": "12.488","text": "es" },
            { "start": "12.775","text": "importante" },
            { "start": "13.585","text": "dirigirse" },
            { "start": "14.246","text": "correctamente" },
            { "start": "15.130","text": "hacia" },
            { "start": "15.386","text": "los" },
            { "start": "15.641","text": "demas" },
            { "start": "16.931","text": "Aunque" },
            { "start": "17.314","text": "nos" },
            { "start": "17.559","text": "conocemos" },
            { "start": "18.209","text": "desde" },
            { "start": "18.401","text": "hace" },
            { "start": "18.689","text": "mucho" },
            { "start": "19.051","text": "tiempo" },
            { "start": "19.989","text": "siempre" },
            { "start": "20.585","text": "debe" },
            { "start": "20.777","text": "haber" },
            { "start": "21.001","text": "respeto" },
            { "start": "21.523","text": "entre" },
            { "start": "21.811","text": "nosotros" },
            { "start": "23.068","text": "por" },
            { "start": "23.260","text": "favor" },
            { "start": "23.782","text": "y" },
            { "start": "23.995","text": "gracias" },
            { "start": "24.783","text": "son" },
            { "start": "25.082","text": "palabras" },
            { "start": "25.572","text": "sencillas" },
            { "start": "26.279","text": "que" },
            { "start": "26.552","text": "pueden" },
            { "start": "27.053","text": "cambiar" },
            { "start": "27.820","text": "todo" }
]


/*--------------------------------English--------------------------------*/


var pistaEN1 = [
             {"start":"0.650","text": "After" },
             {"start": "0.955","text": "a" },
             {"start": "1.160","text": "huge" },
             {"start": "1.522","text": "battle" },
             {"start": "2.131","text": "everybody" },
             {"start": "2.675","text": "celebrated" },
             {"start": "3.456","text": "at" },
             {"start": "3.646","text": "the" },
             {"start": "3.761","text": "Yogomansion" },
             {"start": "4.724","text": "playroom." },
             {"start": "5.975","text": "Guys" },
             {"start": "6.888","text": "wait" },
             {"start": "7.818","text": "said" },
             {"start": "8.065","text": "Eagle." },
             {"start": "9.340","text": "Everybody" },
             {"start": "9.834","text": "was" },
             {"start": "10.122","text": "acting" },
             {"start": "10.641","text": "strange." }
]

var pistaEN2 = [
             {"start": "0.617","text": "Eagle" },
             {"start": "1.070","text": "asked" },
             {"start": "1.539","text": "Dinamita" },
             {"start": "2.238","text": "for" },
             {"start": "2.370","text": "a" },
             {"start": "2.469","text": "glass" },
             {"start": "2.749","text": "of" },
             {"start": "2.897","text": "juice" },
             {"start": "3.637","text": "but" },
             {"start": "3.786","text": "he" },
             {"start": "4.008","text": "pretended." },
             {"start": "4.551","text": "not" },
             {"start": "4.790","text": "to" },
             {"start": "4.921","text": "hear" }
]

var pistaEN3 = [
             {"start": "0.683","text": "Eagle" },
             {"start": "1.012","text": "tried" },
             {"start": "1.374","text": "to" },
             {"start": "1.481","text": "talk" },
             {"start": "1.786","text": "to" },
             {"start": "1.950","text": "Oof" },
             {"start": "2.205","text": "about" },
             {"start": "2.485","text": "the" },
             {"start": "2.625","text": "battle" },
             {"start": "3.168","text": "but" },
             {"start": "3.316","text": "he" },
             {"start": "3.465","text": "just" },
             {"start": "3.687","text": "turned" },
             {"start": "3.950","text": "away." },
             {"start": "5.053","text": "Oof" },
             {"start": "5.473","text": "seemed" },
             {"start": "6.049","text": "to" },
             {"start": "6.139","text": "be" },
             {"start": "6.296","text": "mad" }
]

var pistaEN4 = [
            { "start": "0.675","text": "Eagle" },
            { "start": "1.308","text": "desperate" },
            { "start": "1.866","text": "and" },
            { "start": "2.033","text": "a" },
            { "start": "2.123","text": "little" },
            { "start": "2.837","text": "sad" },
            { "start": "2.971","text": "walked" },
            { "start": "3.399","text": "to" },
            { "start": "3.588","text": "Luna" },
            { "start": "3.942","text": "and" },
            { "start": "4.074","text": "asked" },
            { "start": "4.469","text": "her" },
            { "start": "5.094","text": "What's" },
            { "start": "5.399","text": "going" },
            { "start": "5.662","text": "on" },
            { "start": "5.991","text": "Luna" },
            { "start": "6.723","text": "Nobody" },
            { "start": "7.069","text": "pays" },
            { "start": "7.357","text": "attention" },
            { "start": "7.958","text": "to," },
            { "start": "8.106","text": "me" },
            { "start": "8.476","text": "they" },
            { "start": "8.633","text": "just" },
            { "start": "8.880","text": "ignore" },
            { "start": "9.414","text": "me" },
            { "start": "10.353","text": "What" },
            { "start": "10.558","text": "did" },
            { "start": "10.723","text": "the" },
            { "start": "10.863","text": "aliens" },
            { "start": "11.546","text": "do" },
            { "start": "11.743","text": "to" },
            { "start": "11.892","text": "me" },
            { "start": "12.081","text": "during" },
            { "start": "12.336","text": "the" },
            { "start": "12.533","text": "battle" },
            { "start": "14.459","text": "There's" },
            { "start": "14.657","text": "nothing" },
            { "start": "15.043","text": "going" },
            { "start": "15.229","text": "on" },
            { "start": "15.595","text": "Eagle" },
            { "start": "16.204","text": "it's" },
            { "start": "16.467","text": "you" },
            { "start": "17.537","text": "The" },
            { "start": "17.669","text": "team" },
            { "start": "17.915","text": "is" },
            { "start": "18.072","text": "mad" },
            { "start": "18.327","text": "at" },
            { "start": "18.450","text": "you" },
            { "start": "18.760","text": "because" },
            { "start": "18.706","text": "you" },
            { "start": "19.183","text": "never" },
            { "start": "19.504","text": "say" },
            { "start": "19.915","text": "please" }
            
]
 
var pistaEN5 = [
            { "start": "0.675","text": "Eagle" },
            { "start": "1.053","text": "came" },
            { "start": "1.300","text": "back" },
            { "start": "1.564","text": "to" },
            { "start": "1.695","text": "Dinamita" },
            { "start": "2.461","text": "and" },
            { "start": "2.633","text": "asked" },
            { "start": "2.963","text": "him" },
            { "start": "3.160","text": "for" },
            { "start": "3.242","text": "a" },
            { "start": "3.374","text": "glass" },
            { "start": "3.662","text": "of" },
            { "start": "3.835","text": "juice" },
            { "start": "4.065","text": "again" },
            { "start": "5.036","text": "Can" },
            { "start": "5.110","text": "you" },
            { "start": "5.431","text": "please" },
            { "start": "6.065","text": "give" },
            { "start": "6.304","text": "me" },
            { "start": "6.509","text": "some" },
            { "start": "6.847","text": "juice" },
            { "start": "7.300","text": "Dinamita" },
            { "start": "9.126","text": "All" },
            { "start": "9.275","text": "of," },
            { "start": "9.398","text": "the" },
            { "start": "9.530","text": "yogotars" },
            { "start": "10.427","text": "turned" },
            { "start": "10.912","text": "to" },
            { "start": "11.044","text": "look" },
            { "start": "11.241","text": "at" },
            { "start": "11.340","text": "Eagle" },
            { "start": "11.793","text": "when" },
            { "start": "11.949","text": "they" },
            { "start": "12.048","text": "heard" },
            { "start": "12.319","text": "the." },
            { "start": "12.443","text": "word" },
            { "start": "12.863","text": "please" },
            { "start": "14.533","text": "oof" },
            { "start": "14.879","text": "then" },
            { "start": "15.060","text": "started" },
            { "start": "15.512","text": "talking" },
            { "start": "15.858","text": "to" },
            { "start": "16.023","text": "Eagle" },
            { "start": "16.410","text": "as" },
            { "start": "16.591","text": "if" },
            { "start": "16.730","text": "nothing" },
            { "start": "17.060","text": "had" },
            { "start": "17.241","text": "happened" }

]
  
var pistaEN6 = [
            { "start": "0.634","text": "Thank" },
            { "start": "0.988","text": "you" },
            { "start": "1.259","text": "Luna" },
            { "start": "1.992","text": "said" },
            { "start": "2.205","text": "eagle" },
            { "start": "3.094","text": "you're" },
            { "start": "3.275","text": "welcome" },
            { "start": "4.115","text": "she" },
            { "start": "4.386","text": "answered" },
            { "start": "5.333","text": "we" },
            { "start": "5.464","text": "all" },
            { "start": "5.711","text": "try" },
            { "start": "5.950","text": "to" },
            { "start": "6.032","text": "get" },
            { "start": "6.254","text": "along" },
            { "start": "6.715","text": "so" },
            { "start": "6.995","text": "it's" },
            { "start": "7.225","text": "important" },
            { "start": "7.744","text": "to" },
            { "start": "7.900","text": "treat." },
            { "start": "8.155","text": "everyone" },
            { "start": "8.764","text": "nicely" },
            { "start": "10.155","text": "Although" },
            { "start": "10.476","text": "we've" },
            { "start": "10.649","text": "known" },
            { "start": "10.896","text": "each" },
            { "start": "11.134","text": "other" },
            { "start": "11.357","text": "for" },
            { "start": "11.497","text": "a" },
            { "start": "11.669","text": "long"},
            { "start": "12.031","text": "time"},
            { "start": "12.838","text": "we"},
            { "start": "12.953","text": "must"},
            { "start": "13.249","text": "always"},
            { "start": "13.743","text": "be"},
            { "start": "13.932","text": "respectful"},
            { "start": "15.694","text": "Please"},
            { "start": "16.632","text": "and"},
            { "start": "16.977","text": "thank"},
            { "start": "17.422","text": "you"},
            { "start": "17.990","text": "are"},
            { "start": "18.154","text": "simple"},
            { "start": "18.547","text": "words"},
            { "start": "19.010","text": "that"},
            { "start": "19.199","text": "can"},
            { "start": "19.347","text": "make"},
            { "start": "19.545","text": "your"},
            { "start": "19.784","text": "friends"},
            { "start": "20.170","text": "feel"},
            { "start": "20.318","text": "like"},
            { "start": "20.598","text": "you"},
            { "start": "20.796","text": "care"},
            { "start": "21.076","text": "about"},
            { "start": "21.331","text": "them"}
]


/*--------------------------------Corean--------------------------------*/


var pistaKO1 = [
            
        { "start": "0.104","text": "큰" },
        { "start": "0.620","text": "전투가" },
        { "start": "1.705","text": "끝난" },
        { "start": "2.188","text": "뒤," },
        { "start": "3.097","text": "모두" },
        { "start": "4.214","text": "요고맨션" },
        { "start": "5.522","text": "놀이방에" },
        { "start": "6.400","text": "모여서" },
        { "start": "7.672","text": "승리를" },
        { "start": "8.696","text": "축하하고" },
        { "start": "9.772","text": "있었어요." },
        { "start": "12.325","text": "얘들아," },
        { "start": "13.545","text": "잠깐만!" },
        { "start": "15.254","text": "이글이가" },
        { "start": "16.341","text": "말했어요." },
        { "start": "18.440","text": "모두" },
        { "start": "19.539","text": "이상하게" },
        { "start": "20.605","text": "행동하고" },
        { "start": "21.689","text": "있었어요." }

]

var pistaKO2 = [
    
        { "start": "0.001","text": "이글이는" },
        { "start": "1.354","text": "다이나미타에게" },
        { "start": "3.422","text": "주스를" },
        { "start": "4.462","text": "한" },
        { "start": "4.813","text": "잔" },
        { "start": "5.781","text": "달라고" },
        { "start": "6.631","text": "했지만," },
        { "start": "8.153","text": "다이나미타는" },
        { "start": "10.112","text": "못" },
        { "start": "10.568","text": "들은" },
        { "start": "11.033","text": "척" },
        { "start": "11.804","text": "했어요." }
]

var pistaKO3 = [
    
        { "start": "0.001","text": "이글이는" },
        { "start": "1.493","text": "우프에게" },
        { "start": "3.365","text": "전투에" },
        { "start": "4.423","text": "대해서" },
        { "start": "5.636","text": "얘기하려고" },
        { "start": "6.800","text": "했지만," },
        { "start": "8.274","text": "우프는" },
        { "start": "9.647","text": "그저" },
        { "start": "10.711","text": "돌아서" },
        { "start": "11.595","text": "가버렸어요." },
        { "start": "13.974","text": "우프는" },
        { "start": "15.218","text": "화나" },
        { "start": "15.867","text": "보였어요." }
]

var pistaKO4 = [
    
        { "start": "0.016","text": "이글이는" },
        { "start": "1.428","text": "절망적이고" },
        { "start": "3.010","text": "슬픈" },
        { "start": "3.766","text": "상태로" },
        { "start": "5.376","text": "루나에게" },
        { "start": "6.587","text": "다가가" },
        { "start": "7.582","text": "물었어요." },
        { "start": "9.617","text": "루나야," },
        { "start": "10.908","text": "무슨" },
        { "start": "11.465","text": "일이" },
        { "start": "12.100","text": "일어나고" },
        { "start": "13.000","text": "있는" },
        { "start": "13.325","text": "거야?" },
        { "start": "14.481","text": "아무도" },
        { "start": "15.636","text": "내" },
        { "start": "16.022","text": "말을" },
        { "start": "16.692","text": "듣지" },
        { "start": "17.141","text": "않아." },
        { "start": "18.622","text": "모두들" },
        { "start": "19.806","text": "나를" },
        { "start": "20.549","text": "무시하고" },
        { "start": "21.300","text": "있어." },
        { "start": "23.079","text": "전투" },
        { "start": "23.839","text": "중에" },
        { "start": "24.942","text": "외계인들이" },
        { "start": "26.161","text": "나에게" },
        { "start": "27.249","text": "무슨" },
        { "start": "27.735","text": "짓을" },
        { "start": "28.389","text": "한" },
        { "start": "28.672","text": "거니?" },
        { "start": "31.307","text": "아무" },
        { "start": "31.735","text": "일도" },
        { "start": "32.450","text": "일어나지" },
        { "start": "33.200","text": "않았어." },
        { "start": "34.868","text": "문제는" },
        { "start": "35.934","text": "너야." },
        { "start": "37.312","text": "네가" },
        { "start": "38.455","text": "'부탁해'라는" },
        { "start": "39.944","text": "말을" },
        { "start": "40.959","text": "절대" },
        { "start": "41.654","text": "하지" },
        { "start": "42.100","text": "않아서" },
        { "start": "43.393","text": "친구들이" },
        { "start": "44.319","text": "너에게" },
        { "start": "45.645","text": "화가" },
        { "start": "46.175","text": "난" },
        { "start": "46.474","text": "거야." }
]

var pistaKO5 = [
    
        { "start": "0.100","text": "이글이는" },
        { "start": "1.459","text": "다이나미타에게" },
        { "start": "3.213","text": "돌아가서" },
        { "start": "4.797","text": "다시" },
        { "start": "5.454","text": "한번" },
        { "start": "6.558","text": "주스를" },
        { "start": "7.548","text": "달라고" },
        { "start": "8.480","text": "물었어요." },
        { "start": "11.298","text": "다이나미타야," },
        { "start": "13.142","text": "나에게" },
        { "start": "13.955","text": "주스" },
        { "start": "14.679","text": "한" },
        { "start": "14.915","text": "잔을" },
        { "start": "15.488","text": "줄래?" },
        { "start": "16.810","text": "부탁해." },
        { "start": "19.514","text": "이글이가" },
        { "start": "20.944","text": "'부탁해'라고" },
        { "start": "22.614","text": "말했을" },
        { "start": "23.304","text": "때," },
        { "start": "24.541","text": "모든" },
        { "start": "25.223","text": "요고타들이" },
        { "start": "26.877","text": "고개를" },
        { "start": "27.688","text": "돌려서" },
        { "start": "29.142","text": "그를" },
        { "start": "29.908","text": "쳐다봤어요." },
        { "start": "32.597","text": "우프는" },
        { "start": "34.112","text": "아무" },
        { "start": "34.676","text": "일도" },
        { "start": "35.820","text": "일어나지" },
        { "start": "36.800","text": "않았던" },
        { "start": "37.731","text": "것처럼" },
        { "start": "39.115","text": "다시" },
        { "start": "40.371","text": "이글이와" },
        { "start": "41.710","text": "대화를" },
        { "start": "42.566","text": "나누었어요." }
    
]

var pistaKO6 = [
    
        { "start": "0.001","text": "고마워" },
        { "start": "0.700","text": "루나야." },
        { "start": "2.813","text": "이글이가" },
        { "start": "3.857","text": "말했어요." },
        { "start": "6.033","text": "천만에." },
        { "start": "7.813","text": "루나가" },
        { "start": "8.770","text": "대답했어요." },
        { "start": "11.575","text": "우리는" },
        { "start": "12.700","text": "모두" },
        { "start": "13.640","text": "친하게" },
        { "start": "14.485","text": "지내려고" },
        { "start": "15.720","text": "노력하고" },
        { "start": "16.673","text": "있어." },
        { "start": "18.293","text": "그래서" },
        { "start": "19.436","text": "모두를" },
        { "start": "20.607","text": "잘" },
        { "start": "21.086","text": "대하는" },
        { "start": "21.687","text": "게" },
        { "start": "22.158","text": "중요해." },
        { "start": "23.938","text": "우리가" },
        { "start": "25.158","text": "오랜" },
        { "start": "25.710","text": "시간" },
        { "start": "26.401","text": "동안" },
        { "start": "27.122","text": "친구였지만," },
        { "start": "28.931","text": "그래도" },
        { "start": "29.745","text": "우리는" },
        { "start": "30.847","text": "항상" },
        { "start": "31.964","text": "서로를" },
        { "start": "32.767","text": "존중해" },
        { "start": "33.539","text": "줘야" },
        { "start": "34.000","text": "해." },
        { "start": "36.588","text": "네가" },
        { "start": "37.746","text": "'부탁해'나" },
        { "start": "39.393","text": "'고마워'같은" },
        { "start": "41.181","text": "단순한" },
        { "start": "42.120","text": "말만" },
        { "start": "42.818","text": "더해도" },
        { "start": "44.253","text": "네" },
        { "start": "44.665","text": "친구들은" },
        { "start": "46.119","text": "네가" },
        { "start": "47.174","text": "자기들을" },
        { "start": "48.200","text": "얼마나" },
        { "start": "49.100","text": "아끼고" },
        { "start": "49.961","text": "배려하는지" },
        { "start": "51.506","text": "느낄" },
        { "start": "51.927","text": "수" },
        { "start": "52.313","text": "있어." }
]
