var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]

var pistaES1 = [
            { "start": "0.135","text": "Es" },
            {"start": "0.422","text": "navidad" },
            {"start": "1.501","text": "y" },
            {"start": "1.690","text": "Oof" },
            {"start": "2.034","text": "quiere" },
            {"start": "2.215","text": "impresionar" },
            {"start": "2.829","text": "a" },
            {"start": "3.070","text": "Oona" },
            {"start": "3.594","text": "con" },
            {"start": "3.691","text": "un" },
            {"start": "3.902","text": "hermoso" },
            {"start": "4.522","text": "regalo;" },
            {"start": "6.101","text": "desgraciadamente" },
            {"start": "7.653","text": "no" },
            {"start": "8.023","text": "tiene" },
            {"start": "8.274","text": "dinero" },
            {"start": "8.718","text": "para" },
            {"start": "8.968","text": "comprarlo" }
];

var pistaEN1 = [
            { "start": "0.644","text": "It's" },
            {"start": "1.001","text": "Christmas" },
            {"start": "1.885","text": "and" },
            {"start": "2.131","text": "Oof" },
            {"start": "2.521","text": "wants" },
            {"start": "2.902","text": "to" },
            {"start": "3.034","text": "surprise" },
            {"start": "3.690","text": "Oona" },
            {"start": "4.180","text": "with" },
            {"start": "4.308","text": "a" },
            {"start": "4.534","text": "beautiful" },
            {"start": "5.151","text": "present." },
            {"start": "6.246","text": "Unfortunately" },
            {"start": "7.230","text": "he" },
            {"start": "7.496","text": "has" },
            {"start": "7.872","text": "no" },
            {"start": "8.395","text": "money." }
];


var pistaES2 = [
            { "start": "0.145","text": "Dos" },
            {"start": "0.511","text": "Zuhlurk" },
            {"start": "1.053","text": "se" },
            {"start": "1.263","text": "percatan" },
            {"start": "1.735","text": "de" },
            {"start": "1.887","text": "la" },
            {"start": "2.025","text": "preocupación" },
            {"start": "2.670","text": "de" },
            {"start": "2.940","text": "Oof" },
            {"start": "3.741","text": "y" },
            {"start": "3.860","text": "deciden" },
            {"start": "4.308","text": "ofrecerle" },
            {"start": "4.953","text": "ayuda" },
            {"start": "5.353","text": "al" },
            {"start": "5.580","text": "Yogotar." },
            {"start": "7.428","text": "Emocionado" },
            {"start": "8.407","text": "acepta," },
            {"start": "9.687","text": "sin" },
            {"start": "9.968","text": "darse" },
            {"start": "10.384","text": "cuenta" },
            {"start": "10.915","text": "de" },
            {"start": "11.027","text": "los." },
            {"start": "11.223","text": "verdaderos" },
            {"start": "11.894","text": "planes" },
            {"start": "12.294","text": "de" },
            {"start": "12.406","text": "sus" },
            {"start": "12.692","text": "nuevos"},
            {"start": "13.076","text": "amigos."}
];

var pistaEN2 = [
            { "start": "0.604","text": "Two" },
            {"start": "1.013","text": "Zuhlurks" },
            {"start": "1.736","text": "realize" },
            {"start": "2.251","text": "Oof's" },
            {"start": "2.591","text": "problem" },
            {"start": "3.240","text": "and" },
            {"start": "3.429","text": "decide" },
            {"start": "4.144","text": "to" },
            {"start": "4.243","text": "help" },
            {"start": "4.713","text": "him." },
            {"start": "6.135","text": "Oof" },
            {"start": "6.465","text": "accepts" },
            {"start": "7.071","text": "their" },
            {"start": "7.253","text": "help" },
            {"start": "7.854","text": "and" },
            {"start": "8.002","text": "is" },
            {"start": "8.155","text": "happy." },
            {"start": "9.303","text": "But" },
            {"start": "9.549","text": "Oof" },
            {"start": "9.908","text": "is" },
            {"start": "10.219","text": "unaware" },
            {"start": "10.877","text": "of" },
            {"start": "11.009","text": "their" },
            {"start": "11.273","text": "true" },
            {"start": "11.823","text": "intentions."}
    
    
];



var pistaES3 = [
            { "start": "0.094","text": "-Pero…" },
            {"start": "1.248","text": "¿Qué" },
            {"start": "1.353","text": "están" },
            {"start": "1.612","text": "haciendo?" },
            {"start": "3.797","text": "-dijo" },
            {"start": "4.264","text": "Oof." },
            {"start": "6.775","text": "-Tomando" },
            {"start": "7.315","text": "nuestros" },
            {"start": "7.740","text": "regalos" },
            {"start": "8.766","text": "-dijo" },
            {"start": "9.148","text": "el" },
            {"start": "9.318","text": "Zuhlurk." },
            {"start": "10.663","text": "--Si" },
            {"start": "10.913","text": "no" },
            {"start": "11.136","text": "pagas" },
            {"start": "11.556","text": "por" },
            {"start": "11.675","text": "ellos," },
            {"start": "12.541","text": "estás" },
            {"start": "12.980","text": "robando" },
            {"start": "15.478","text": "-dijo" },
            {"start": "15.885","text": "Oof." },
            {"start": "18.120","text": "-Nadie" },
            {"start": "18.567","text": "se" },
            {"start": "18.782","text": "va" },
            {"start": "18.890","text": "a" },
            {"start": "18.933","text": "dar" },
            {"start": "19.194","text": "cuenta," },
            {"start": "20.123","text": "no" },
            {"start": "20.482","text": "te" },
            {"start": "20.654","text": "preocupes" },
            {"start": "22.772","text": "-dijo" },
            {"start": "23.133","text": "el" },
            {"start": "23.293","text": "otro" },
            {"start": "23.673","text": "Zuhlurk."}
]

var pistaEN3 = [
            { "start": "0.598","text": '"But...' },
            {"start": "1.382","text": "What" },
            {"start": "1.607","text": "are" },
            {"start": "1.740","text": "you" },
            {"start": "1.903","text": 'doing?"' },
            {"start": "2.619","text": "Oof" },
            {"start": "2.827","text": "said." },
            {"start": "4.620","text": '"We' },
            {"start": "4.977","text": "are" },
            {"start": "5.204","text": "taking" },
            {"start": "5.792","text": "our" },
            {"start": "6.110","text": 'presents,"' },
            {"start": "6.998","text": "said" },
            {"start": "7.289","text": "one" },
            {"start": "7.440","text": "of" },
            {"start": "7.619","text": "the" },
            {"start": "7.691","text": "Zuhlurks." },
            {"start": "9.155","text": '"If' },
            {"start": "9.299","text": "you" },
            {"start": "9.432","text": "don't" },
            {"start": "9.712","text": "pay" },
            {"start": "10.001","text": 'for' },
            {"start": "10.137","text": "them," },
            {"start": "10.738","text": "you" },
            {"start": "10.971","text": "are" },
            {"start": "11.149","text": 'stealing,"' },
            {"start": "12.381","text": "said" },
            {"start": "12.642","text": "Oof." },
            {"start": "13.832","text": "Don't" },
            {"start": "14.317","text": "worry!" },
            {"start": "15.044","text": "No" },
            {"start": "15.320","text": "one" },
            {"start": "15.541","text": 'will' },
            {"start": "15.727","text": "notice," },
            {"start": "16.722","text": "said" },
            {"start": "17.019","text": "the" },
            {"start": "17.140","text": "Zuhlurk."}
];



var pistaES4 = [
            { "start": "0.138","text": "Oof" },
            { "start": "0.719","text": "observa" },
            { "start": "1.316","text": "a"},
            { "start": "1.516","text": "Justice,"},
            { "start": "2.922","text": "una"},
            { "start": "3.259","text": "voz"},
            { "start": "3.508","text": "interior"},
            { "start": "4.090","text": "le"},
            { "start": "4.332","text": "dice"},
            { "start": "4.700","text": "que" },
            { "start": "4.842","text": "debe"},
            { "start": "5.156","text": "hacer"},
            { "start": "5.549","text": "lo"},
            { "start": "5.746","text": "correcto,"},
            { "start": "7.228","text": "pero"},
            { "start": "7.481","text": "el"},
            { "start": "7.564","text": "Zuhlurk"},
            { "start": "8.252","text": "le" },
            { "start": "8.429","text": "dice"},
            { "start": "8.713","text": "lo"},
            { "start": "8.919","text": "contrario:"},
            { "start": "10.787","text": "-Ni"},
            { "start": "10.960","text": "lo"},
            { "start": "11.083","text": "intentes.,"},
            { "start": "12.351","text": "si"},
            { "start": "12.488","text": "nadie"},
            { "start": "12.840","text": "se" },
            { "start": "12.934","text": "entera,"},
            { "start": "13.685","text": "no"},
            { "start": "13.969","text": "pasa:"},
            { "start": "14.279","text": "nada."},
            { "start": "15.151","text": "Sólo"},
            { "start": "15.558","text": "toma"},
            { "start": "15.835","text": "tu"},
            { "start": "15.901","text": "regalo"},
            { "start": "16.610","text": "y"},
            { "start": "16.752","text": "vete."}
            
]

var pistaEN4 = [
            { "start": "0.827","text": "Oof" },
            { "start": "1.141","text": "sees" },
            { "start": "1.490","text": "Justice,"},
            { "start": "2.577","text": "a"},
            { "start": "2.739","text": "voice"},
            { "start": "3.126","text": "within"},
            { "start": "3.726","text": "tells"},
            { "start": "4.056","text": "him"},
            { "start": "4.284","text": "to"},
            { "start": "4.445","text": "do"},
            { "start": "4.610","text": "the"},
            { "start": "4.797","text": "right"},
            { "start": "5.148","text": "thing"},
            { "start": "6.047","text": "but"},
            { "start": "6.166","text": "the"},
            { "start": "6.331","text": "Zuhlurks" },
            { "start": "6.800","text": "says"},
            { "start": "7.206","text": "the"},
            { "start": "7.355","text": "opposite."},
            { "start": "8.572","text": "Don't"},
            { "start": "8.940","text": "even"},
            { "start": "9.294","text": "try"},
            { "start": "9.535","text": "it."},
            { "start": "10.201","text": "If"},
            { "start": "10.412","text": "nobody"},
            { "start": "10.872","text": "notices,"},
            { "start": "11.704","text": "nothing"},
            { "start": "12.080","text": "will"},
            { "start": "12.250","text": "happen."},
            { "start": "13.219","text": "Just"},
            { "start": "13.510","text": "take"},
            { "start": "13.731","text": "your"},
            { "start": "13.923","text": "present"},
            { "start": "14.325","text": "and"},
            { "start": "14.565","text": "go-" }
            
]


var pistaES5 = [
            { "start": "0.244","text": "Oof" },
            { "start": "0.663","text": "lo" },
            { "start": "0.900","text": "pensó" },
            { "start": "1.386","text": "bien" },
            { "start": "1.980","text": "y" },
            { "start": "2.126","text": "decidió" },
            { "start": "2.716","text": "hacer" },
            { "start": "3.115","text": "lo" },
            { "start": "3.281","text": "correcto:" },
            { "start": "4.757","text": "Le" },
            { "start": "4.964","text": "hizo" },
            { "start": "5.171","text": "un" },
            { "start": "5.313","text": "regalo" },
            { "start": "5.728","text": "a" },
            { "start": "5.854","text": "Oona" },
            { "start": "6.372","text": "con" },
            { "start": "6.578","text": "sus" },
            { "start": "6.807","text": "propias" },
            { "start": "7.234","text": "manos…" }
            
]



var pistaEN5 = [
            { "start": "0.647","text": "Oof" },
            { "start": "0.963","text": "thinks" },
            { "start": "1.219","text": "it" },
            { "start": "1.464","text": "through" },
            { "start": "2.115","text": "and" },
            { "start": "2.286","text": "decides" },
            { "start": "2.840","text": "to" },
            { "start": "3.006","text": "do" },
            { "start": "3.250","text": "the" },
            { "start": "3.498","text": "right" },
            { "start": "3.869","text": "thing." },
            { "start": "4.900","text": "Instead" },
            { "start": "5.913","text": "he" },
            { "start": "6.053","text": "makes" },
            { "start": "6.493","text": "Oona" },
            { "start": "6.823","text": "a" },
            { "start": "7.061","text": "present" },
            { "start": "7.536","text": "with" },
            { "start": "7.681","text": "his" },
            { "start": "8.007","text": "own" },
            { "start": "8.386","text": "hands." }
            
]


var pistaES6 = [
            { "start": "0.356","text": "…y" },
            { "start": "0.491","text": "le" },
            { "start": "0.725","text": "contó" },
            { "start": "1.050","text": "a" },
            { "start": "1.238","text": "Justice" },
            { "start": "1.875","text": "sobre" },
            { "start": "2.183","text": "los" },
            { "start": "2.500","text": "planes" },
            { "start": "2.878","text": "de" },
            { "start": "3.001","text": "los" },
            { "start": "3.224","text": "Zuhlurks." },
            { "start": "5.197","text": "Esperemos" },
            { "start": "5.877","text": "que" },
            { "start": "6.013","text": "ellos" },
            { "start": "6.313","text": "también" },
            { "start": "7.005","text": "entiendan" },
            { "start": "7.715","text": "que" },
            { "start": "7.829","text": "siempre" },
            { "start": "8.425","text": "es" },
            { "start": "8.588","text": "mejor" },
            { "start": "9.195","text": "hacer" },
            { "start": "9.621","text": "lo" },
            { "start": "9.866","text": "correcto."}
    ]


var pistaEN6 = [
            { "start": "0.635","text": "..." },
            { "start": "0.673","text": "and" },
            { "start": "0.845","text": "tells" },
            { "start": "1.240","text": "Justice" },
            { "start": "1.764","text": "about" },
            { "start": "2.112","text": "the" },
            { "start": "2.204","text": "Zuhlurk's" },
            { "start": "2.798","text": "plans." },
            { "start": "4.041","text": "Let's" },
            { "start": "4.323","text": "hope" },
            { "start": "4.603","text": "they" },
            { "start": "4.840","text": "understand" },
            { "start": "5.499","text": "that" },
            { "start": "5.594","text": "it's" },
            { "start": "5.733","text": "important" },
            { "start": "6.358","text": "to" },
            { "start": "6.596","text": "always" },
            { "start": "7.159","text": "do" },
            { "start": "7.418","text": "the" },
            { "start": "7.623","text": "right" },
            { "start": "8.014","text": "thing." }
    ]


/*--------------------------------Corean--------------------------------*/


var pistaKO1 = [
            { "start": "0.009","text": "이제" },
            { "start": "1.118","text": "크리스마스가" },
            { "start": "2.757","text": "다가왔고" },
            { "start": "4.450","text": "우프는" },
            { "start": "5.869","text": "우나에게" },
            { "start": "7.267","text": "선물을" },
            { "start": "8.203","text": "주어서" },
            { "start": "9.534","text": "깜짝" },
            { "start": "10.546","text": "놀래키고" },
            { "start": "11.677","text": "싶어요" },
            { "start": "13.385","text": "그렇지만" },
            { "start": "14.587","text": "안타깝게도" },
            { "start": "16.490","text": "우프는" },
            { "start": "17.803","text": "돈이" },
            { "start": "18.493","text": "없어요." }
] 

var pistaKO2 = [
            { "start": "0.060","text": "두" },
            { "start": "0.462","text": "즐러크가" },
            { "start": "2.072","text": "걱정하는" },
            { "start": "3.294","text": "우프를" },
            { "start": "4.334","text": "보게" },
            { "start": "4.787","text": "되고" },
            { "start": "5.945","text": "도와주기로" },
            { "start": "7.445","text": "결심해요." },
            { "start": "9.920","text": "우프는" },
            { "start": "11.307","text": "도움을" },
            { "start": "12.161","text": "받게" },
            { "start": "12.925","text": "되어서" },
            { "start": "14.200","text": "행복해요." },
            { "start": "16.086","text": "하지만" },
            { "start": "17.418","text": "우프는" },
            { "start": "18.423","text": "두" },
            { "start": "18.892","text": "즐러크가" },
            { "start": "20.425","text": "도와주려는" },
            { "start": "21.700","text": "이유를" },
            { "start": "22.955","text": "아직" },
            { "start": "23.665","text": "몰라요." }
] 

var pistaKO3 = [
            { "start": "0.061","text": "그렇지만..." },
            { "start": "1.650","text": "뭐" },
            { "start": "1.900","text": "하고" },
            { "start": "2.304","text": "계세요?" },
            { "start": "4.150","text": "우프가" },
            { "start": "5.178","text": "물었어요." },
            { "start": "7.065","text": "우리는" },
            { "start": "8.129","text": "우리" },
            { "start": "8.469","text": "선물을" },
            { "start": "9.178","text": "챙겨가는거야." },
            { "start": "11.572","text": "한" },
            { "start": "12.066","text": "즐러크가" },
            { "start": "13.301","text": "말했어요." },
            { "start": "15.321","text": "돈을" },
            { "start": "15.927","text": "내지" },
            { "start": "16.386","text": "않고" },
            { "start": "17.058","text": "가져가는" },
            { "start": "18.022","text": "건" },
            { "start": "18.785","text": "훔치는" },
            { "start": "19.545","text": "거잖아요." },
            { "start": "21.575","text": "우프가" },
            { "start": "22.577","text": "말했어요" },
            { "start": "24.129","text": "걱정마!" },
            { "start": "25.485","text": "아무도" },
            { "start": "26.065","text": "모를거야" },
            { "start": "28.042","text": "다른" },
            { "start": "28.650","text": "즐러크가" },
            { "start": "29.955","text": "대답했어요." }
] 

var pistaKO4 = [
            { "start": "0.034","text": "우프는" },
            { "start": "1.021","text": "바른" },
            { "start": "1.630","text": "일을" },
            { "start": "2.121","text": "해야" },
            { "start": "2.700","text": "한다고" },
            { "start": "3.456","text": "말하는" },
            { "start": "4.737","text": "저스티스를" },
            { "start": "6.139","text": "바라보아요." },
            { "start": "8.176","text": "그렇지만" },
            { "start": "9.587","text": "즐러크들은" },
            { "start": "11.012","text": "전혀" },
            { "start": "11.833","text": "다른" },
            { "start": "12.869","text": "이야기를" },
            { "start": "13.827","text": "해요." },
            { "start": "15.422","text": "다른" },
            { "start": "15.791","text": "생각은" },
            { "start": "16.731","text": "하지도" },
            { "start": "17.200","text": "마." },
            { "start": "18.262","text": "아무도" },
            { "start": "18.857","text": "모르면," },
            { "start": "19.957","text": "아무" },
            { "start": "20.400","text": "일도" },
            { "start": "20.900","text": "일어나지" },
            { "start": "21.538","text": "않는거야." },
            { "start": "23.274","text": "얼른" },
            { "start": "24.072","text": "선물을" },
            { "start": "24.674","text": "챙겨서" },
            { "start": "25.262","text": "나가자!" }
] 

var pistaKO5 = [
            { "start": "0.018","text": "우프는" },
            { "start": "1.066","text": "곰곰히" },
            { "start": "1.978","text": "생각하고" },
            { "start": "3.650","text": "올바른" },
            { "start": "4.565","text": "일을" },
            { "start": "5.469","text": "하기로" },
            { "start": "6.278","text": "결정해요." },
            { "start": "8.884","text": "대신" },
            { "start": "10.101","text": "우나를" },
            { "start": "10.954","text": "위한" },
            { "start": "11.513","text": "선물을" },
            { "start": "12.720","text": "직접" },
            { "start": "13.609","text": "만들기로" },
            { "start": "14.462","text": "했어요." }
] 

var pistaKO6 = [
            { "start": "0.007","text": "... 그리고" },
            { "start": "0.961","text": "우프는" },
            { "start": "2.343","text": "저스티스에게" },
            { "start": "4.432","text": "즐러크들이" },
            { "start": "6.175","text": "선물을" },
            { "start": "7.091","text": "훔치고" },
            { "start": "7.970","text": "있다고" },
            { "start": "9.118","text": "알려주어요." },
            { "start": "11.350","text": "항상" },
            { "start": "12.191","text": "올바른" },
            { "start": "12.957","text": "일을" },
            { "start": "13.418","text": "하는" },
            { "start": "13.890","text": "게" },
            { "start": "14.618","text": "중요하다는걸" },
            { "start": "16.485","text": "즐러크들이" },
            { "start": "18.105","text": "깨달았으면" },
            { "start": "19.307","text": "해요." }
] 

