var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]
 
 
 /*--------------------------------Spanish--------------------------------*/
  
  var pistaES1 = [
            {"start": "0.483","text": "A" },
            {"start": "0.667","text": "varios" },
            {"start": "1.119","text": "kilómetros" },
            {"start": "1.728","text": "de," },
            {"start": "1.870","text": "Yogópolis" },
            {"start": "2.943","text": "se" },
            {"start": "3.338","text": "encuentra" },
            {"start": "3.740","text": "un" },
            {"start": "3.924","text": "viejo" },
            {"start": "4.334","text": "castillo" },
            {"start": "4.871","text": "deshabitado" },
            {"start": "6.426","text": "con" },
            {"start": "6.595","text": "un" },
            {"start": "6.756","text": "enorme" },
            {"start": "7.411","text": "y" },
            {"start": "7.484","text": "oscuro" },
            {"start": "7.975","text": "lago" },
            {"start": "8.806","text": "donde" },
            {"start": "9.186","text": "vive" },
            {"start": "9.603","text": "una" },
            {"start": "9.822","text": "criatura" },
            {"start": "10.469","text": "muy" },
            {"start": "10.826","text": "especial" }
  ]

  var pistaES2 = [
            {"start": "0.250","text": "Aunque" },
            {"start": "0.600","text": "nadie" },
            {"start": "1.051","text": "la" },
            {"start": "1.145","text": "ha," },
            {"start": "1.262","text": "visto" },
            {"start": "1.546","text": "a" },
            {"start": "1.653","text": "la" },
            {"start": "1.761","text": "luz" },
            {"start": "2.020","text": "del" },
            {"start": "2.210","text": "día" },
            {"start": "3.040","text": "saben" },
            {"start": "3.453","text": "de" },
            {"start": "3.587","text": "su" },
            {"start": "3.755","text": "existencia" },
            {"start": "5.821","text": "La" },
            {"start": "6.144","text": "gente" },
            {"start": "6.523","text": "de" },
            {"start": "6.614","text": "los" },
            {"start": "6.816","text": "alrededores" },
            {"start": "7.677","text": "le" },
            {"start": "7.944","text": "teme" },
            {"start": "8.728","text": "y" },
            {"start": "8.900","text": "muchos" },
            {"start": "9.369","text": "otros" },
            {"start": "9.860","text": "cuentan" },
            {"start": "10.265","text": "relatos" },
            {"start": "10.855","text": "terribles" },
            {"start": "11.647","text": "sobre" },
            {"start": "11.918","text": "la" },
            {"start": "12.069","text": "criatura" },
            {"start": "12.517","text": "marina" }
 ]
    
 var pistaES3 = [
            {"start": "0.350","text": "Deberíamos" },
            {"start": "1.134","text": "correr" },
            {"start": "1.443","text": "a" },
            {"start": "1.513","text": "esa," },
            {"start": "1.683","text": "horrible" },
            {"start": "2.294","text": "criatura" },
            {"start": "4.241","text": "dijo" },
            {"start": "4.620","text": "un" },
            {"start": "4.774","text": "Bean" },
            {"start": "6.400","text": "Sí" },
            {"start": "8.450","text": "gritó" },
            {"start": "9.034","text": "otro" },
            {"start": "12.198","text": "Por" },
            {"start": "12.478","text": "que" },
            {"start": "12.573","text": "la" },
            {"start": "12.734","text": "van" },
            {"start": "12.957","text": "a" },
            {"start": "13.070","text": "correr" },
            {"start": "14.293","text": "Les" },
            {"start": "14.580","text": "ha" },
            {"start": "14.678","text": "hecho" },
            {"start": "14.984","text": "algo" },
            {"start": "17.202","text": "interrumpió" },
            {"start": "18.084","text": "Thefannie" }
 ]
 
 var pistaES4 = [
            {"start": "0.440","text": "Dicen" },
            {"start": "0.974","text": "que" },
            {"start": "1.071","text": "es" },
            {"start": "1.193","text": "horrible" },
            {"start": "3.146","text": "dijo" },
            {"start": "3.560","text": "un" },
            {"start": "3.781","text": "Bean" },
            {"start": "5.715","text": "y" },
            {"start": "5.918","text": "dicen" },
            {"start": "6.331","text": "que" },
            {"start": "6.487","text": "por" },
            {"start": "6.563","text": "las" },
            {"start": "6.889","text": "noches" },
            {"start": "7.310","text": "espanta" },
            {"start": "7.756","text": "a" },
            {"start": "7.826","text": "la" },
            {"start": "7.947","text": "gente" },
            {"start": "8.465","text": "que" },
            {"start": "8.560","text": "camina" },
            {"start": "9.072","text": "cerca" },
            {"start": "9.540","text": "del" },
            {"start": "9.715","text": "lago" },
            {"start": "11.625","text": "gritó" },
            {"start": "12.238","text": "otro" },
            {"start": "14.807","text": "Alguno" },
            {"start": "15.233","text": "de" },
            {"start": "15.317","text": "ustedes" },
            {"start": "15.803","text": "lo" },
            {"start": "16.020","text": "conoce" },
            {"start": "18.180","text": "dijo" },
            {"start": "18.550","text": "Thefannie" },
            {"start": "20.279","text": "Todos" },
            {"start": "20.636","text": "se" },
            {"start": "20.876","text": "vieron" },
            {"start": "21.130","text": "entre" },
            {"start": "21.478","text": "sí" },
            {"start": "22.044","text": "pero" },
            {"start": "22.274","text": "nadie" },
            {"start": "22.610","text": "respondió" },
            {"start": "24.786","text": "nadie" },
            {"start": "25.193","text": "lo" },
            {"start": "25.374","text": "conocía" },
            {"start": "25.941","text": "realmente" },
            {"start": "28.815","text": "No" },
            {"start": "29.123","text": "creen" },
            {"start": "29.360","text": "que" },
            {"start": "29.430","text": "es" },
            {"start": "29.560","text": "algo" },
            {"start": "29.800","text": "injusto" },
            {"start": "30.380","text": "hablar" },
            {"start": "30.642","text": "mal" },
            {"start": "30.900","text": "de" },
            {"start": "30.987","text": "alguien" },
            {"start": "31.446","text": "que" },
            {"start": "31.520","text": "no" },
            {"start": "31.700","text": "conocen" }
 ]
      
 var pistaES5 = [
            {"start": "0.437","text": "Miren" },
            {"start": "1.515","text": "Ahí" },
            {"start": "1.864","text": "está" },
            {"start": "4.290","text": "dijo" },
            {"start": "4.652","text": "uno" },
            {"start": "4.971","text": "de" },
            {"start": "5.071","text": "los" },
            {"start": "5.241","text": "Beans" },
            {"start": "6.643","text": "Todos" },
            {"start": "7.065","text": "voltearon" },
            {"start": "7.500","text": "a" },
            {"start": "7.680","text": "ver" },
            {"start": "8.070","text": "a" },
            {"start": "8.150","text": "la" },
            {"start": "8.283","text": "criatura" },
            {"start": "8.760","text": "marina" },
            {"start": "10.600","text": "No" },
            {"start": "10.823","text": "se" },
            {"start": "11.028","text": "ve" },
            {"start": "11.202","text": "tan" },
            {"start": "11.310","text": "horrible" },
            {"start": "11.874","text": "y" },
            {"start": "11.896","text": "espantoso" },
            {"start": "12.652","text": "como" },
            {"start": "12.984","text": "me" },
            {"start": "13.056","text": "lo" },
            {"start": "13.144","text": "habían" },
            {"start": "13.528","text": "contado" },
            {"start": "16.031","text": "dijo" },
            {"start": "16.420","text": "uno" },
            {"start": "16.765","text": "de" },
            {"start": "16.827","text": "los" },
            {"start": "17.067","text": "Beans" },
            {"start": "18.235","text": "Hola" },
            {"start": "19.126","text": "mi" },
            {"start": "19.348","text": "nombre" },
            {"start": "19.672","text": "es" },
            {"start": "19.844","text": "Arthurius" },
            {"start": "22.554","text": "Yo" },
            {"start": "22.724","text": "soy" },
            {"start": "23.120","text": "Thefannie" },
            {"start": "25.304","text": "Yo" },
            {"start": "25.639","text": "soy" },
            {"start": "26.018","text": "Aji" },
            {"start": "27.832","text": "respondió" },
            {"start": "28.616","text": "la" },
            {"start": "28.856","text": "criatura" },
            {"start": "29.327","text": "marina" }
]
 
var pistaES6 = [
            {"start": "0.437","text": "Durante" },
            {"start": "0.971","text": "esa" },
            {"start": "1.277","text": "noche" },
            {"start": "2.060","text": "todos" },
            {"start": "2.400","text": "intercambiaron" },
            {"start": "3.212","text": "ideas" },
            {"start": "3.832","text": "e" },
            {"start": "3.914","text": "historias" },
            {"start": "5.191","text": "se" },
            {"start": "5.453","text": "presentaron" },
            {"start": "6.648","text": "y" },
            {"start": "6.771","text": "descubrieron" },
            {"start": "7.466","text": "que" },
            {"start": "7.560","text": "el" },
            {"start": "7.694","text": "pequeño" },
            {"start": "8.228","text": "Aji" },
            {"start": "8.967","text": "sólo" },
            {"start": "9.356","text": "era" },
            {"start": "9.494","text": "una" },
            {"start": "9.744","text": "criatura" },
            {"start": "10.271","text": "tímida" },
            {"start": "10.689","text": "y" },
            {"start": "10.771","text": "sin" },
            {"start": "11.000","text": "amigos" },
            {"start": "13.087","text": "Desde" },
            {"start": "13.535","text": "ese" },
            {"start": "13.871","text": "día" },
            {"start": "14.663","text": "los" },
            {"start": "15.051","text": "Beans" },
            {"start": "15.425","text": "aprendieron" },
            {"start": "16.116","text": "a" },
            {"start": "16.258","text": "no" },
            {"start": "16.526","text": "juzgar" },
            {"start": "17.040","text": "por" },
            {"start": "17.143","text": "las" },
            {"start": "17.333","text": "apariencias" },
            {"start": "19.245","text": "ni" },
            {"start": "19.425","text": "a" },
            {"start": "19.533","text": "fiarse" },
            {"start": "19.981","text": "de" },
            {"start": "20.100","text": "los" },
            {"start": "20.343","text": "relatos" },
            {"start": "20.859","text": "de" },
            {"start": "21.064","text": "terceras" },
            {"start": "21.677","text": "personas" }
]


/*--------------------------------English--------------------------------*/

var pistaEN1 = [
             {"start":"0.735","text": "Far" },
             {"start":"1.026","text": "away" },
             {"start":"1.557","text": "from" },
             {"start":"1.746","text": "Yogopolis" },
             {"start":"2.837","text": "there" },
             {"start":"2.944","text": "was" },
             {"start":"3.131","text": "an" },
             {"start":"3.436","text": "old" },
             {"start":"3.862","text": "abandoned" },
             {"start":"4.631","text": "castle" },
             {"start":"5.272","text": "with" },
             {"start":"5.422","text": "a" },
             {"start":"5.640","text": "dark" },
             {"start":"5.976","text": "lake" },
             {"start":"6.422","text": "where" },
             {"start":"6.563","text": "a" },
             {"start":"6.645","text": "special" },
             {"start":"7.374","text": "creature" },
             {"start":"7.795","text": "lived" }
]

var pistaEN2 = [
             {"start":"0.551","text": "Although" },
             {"start":"0.924","text": "no" },
             {"start":"1.171","text": "one" },
             {"start":"1.376","text": "had" },
             {"start":"1.643","text": "seen" },
             {"start":"1.834","text": "it" },
             {"start":"2.085","text": "during" },
             {"start":"2.309","text": "the" },
             {"start":"2.491","text": "daylight" },
             {"start":"3.352","text": "people" },
             {"start":"3.778","text": "were" },
             {"start":"4.197","text": "afraid" },
             {"start":"4.441","text": "of" },
             {"start":"4.517","text": "the" },
             {"start":"4.807","text": "creature" },
             {"start":"6.000","text": "Many" },
             {"start":"6.579","text": "told" },
             {"start":"7.017","text": "horrible" },
             {"start":"7.600","text": "stories" },
             {"start":"8.066","text": "about" },
             {"start":"8.281","text": "the" },
             {"start":"8.522","text": "creature" },
             {"start":"9.089","text": "in" },
             {"start":"9.228","text": "the" },
             {"start":"9.228","text": "lake" }
             
]

var pistaEN3 = [
             {"start":"0.514","text": "We" },
             {"start":"0.884","text": "should" },
             {"start":"1.159","text": "make" },
             {"start":"1.394","text": "that" },
             {"start":"1.554","text": "horrible" },
             {"start":"2.181","text": "creature" },
             {"start":"2.720","text": "leave" },
             {"start":"3.624","text": "said" },
             {"start":"3.836","text": "a" },
             {"start":"3.998","text": "Bean" },
             {"start":"4.909","text": "Yes" },
             {"start":"5.614","text": "another" },
             {"start":"5.990","text": "screamed" },
             {"start":"7.390","text": "Why" },
             {"start":"7.649","text": "do" },
             {"start":"7.764","text": "you" },
             {"start":"7.889","text": "want" },
             {"start":"8.035","text": "it" },
             {"start":"8.241","text": "to" },
             {"start":"8.362","text": "leave" },
             {"start":"9.224","text": "Has" },
             {"start":"9.374","text": "it" },
             {"start":"9.530","text": "done" },
             {"start":"9.820","text": "something" },
             {"start":"10.249","text": "to" },
             {"start":"10.432","text": "you" },
             {"start":"10.965","text": "Thefannie" },
             {"start":"11.532","text": "interrupted" }
            
]

var pistaEN4 = [
            {"start":"0.514","text": "They" },
            {"start":"0.752","text": "say" },
            {"start":"0.950","text": "it's" },
            {"start":"1.295","text": "horrible" },
            {"start":"2.230","text": "said" },
            {"start":"2.500","text": "a" },
            {"start":"2.591","text": "Bean" },
            {"start":"3.584","text": "They" },
            {"start":"3.737","text": "say" },
            {"start":"3.897","text": "it" },
            {"start":"4.050","text": "scares" },
            {"start":"4.660","text": "people" },
            {"start":"4.9950","text": "that" },
            {"start":"5.151","text": "pass" },
            {"start":"5.535","text": "by" },
            {"start":"5.855","text": "the" },
            {"start":"5.985","text": "lake" },
            {"start":"6.250","text": "at" },
            {"start":"6.424","text": "night" },
            {"start":"7.187","text": "screamed" },
            {"start":"7.700","text": "another" },
            {"start":"8.107","text": "Bean" },
            {"start":"9.071","text": "Do" },
            {"start":"9.194","text": "any" },
            {"start":"9.458","text": "of" },
            {"start":"9.614","text": "you" },
            {"start":"9.748","text": "know" },
            {"start":"10.236","text": "the" },
            {"start":"10.362","text": "creature" },
            {"start":"11.226","text": "said" },
            {"start":"11.565","text": "Thefannie" },
            {"start":"12.983","text": "They" },
            {"start":"13.098","text": "looked" },
            {"start":"13.359","text": "at" },
            {"start":"13.463","text": "each" },
            {"start":"13.712","text": "other" },
            {"start":"14.330","text": "but" },
            {"start":"14.442","text": "nobody" },
            {"start":"14.751","text": "answered" },
            {"start":"15.964","text": "No" },
            {"start":"16.184","text": "one" },
            {"start":"16.578","text": "really" },
            {"start":"16.943","text": "knew" },
            {"start":"17.293","text": "the" },
            {"start":"17.446","text": "creature" },
            {"start":"18.536","text": "Don't" },
            {"start":"18.726","text": "you" },
            {"start":"18.957","text": "think" },
            {"start":"19.139","text": "it's" },
            {"start":"19.381","text": "unfair" },
            {"start":"20.170","text": "to" },
            {"start":"20.330","text": "talk" },
            {"start":"20.647","text": "about" },
            {"start":"21.000","text": "someone" },
            {"start":"21.309","text": "you" },
            {"start":"21.577","text": "don't" },
            {"start":"21.905","text": "know" }   
]
 
var pistaEN5 = [
            {"start":"0.550","text": "Look" },
            {"start":"1.274","text": "There" },
            {"start":"1.518","text": "it" },
            {"start":"1.602","text": "is" },
            {"start":"2.214","text": "said" },
            {"start":"2.409","text": "one" },
            {"start":"2.600","text": "of" },
            {"start":"2.709","text": "the" },
            {"start":"2.869","text": "Beans" },
            {"start":"3.902","text": "Everybody" },
            {"start":"4.424","text": "turned" },
            {"start":"4.966","text": "to" },
            {"start":"5.157","text": "see" },
            {"start":"5.315","text": "the" },
            {"start":"5.528","text": "creature" },
            {"start":"5.847","text": "in" },
            {"start":"5.896","text": "the" },
            {"start":"6.051","text": "lake" },
            {"start":"6.972","text": "it" },
            {"start":"7.111","text": "doesn't" },
            {"start":"7.408","text": "look" },
            {"start":"7.758","text": "as" },
            {"start":"8.098","text": "scary" },
            {"start":"8.521","text": "and" },
            {"start":"8.716","text": "horrible" },
            {"start":"9.127","text": "as" },
            {"start":"9.288","text": "I" },
            {"start":"9.396","text": "was" },
            {"start":"9.678","text": "told" },
            {"start":"10.420","text": "said" },
            {"start":"10.624","text": "a" },
            {"start":"10.772","text": "Bean" },
            {"start":"11.820","text": "Hi" },
            {"start":"12.640","text": "My" },
            {"start":"12.813","text": "name" },
            {"start":"13.057","text": "is" },
            {"start":"13.178","text": "Arthurius" },
            {"start":"14.683","text": "I'm" },
            {"start":"14.977","text": "Thefannie" },
            {"start":"16.217","text": "I'm" },
            {"start":"16.628","text": "Aji" },
            {"start":"17.522","text": "said" },
            {"start":"17.825","text": "the" },
            {"start":"18.000","text": "creature" }
]
  
var pistaEN6 = [
            {"start":"0.526","text": "That" },
            {"start":"0.795","text": "night" },
            {"start":"1.395","text": "everyone" },
            {"start":"1.971","text": "shared" },
            {"start":"2.439","text": "ideas" },
            {"start":"3.218","text": "and" },
            {"start":"3.390","text": "stories" },
            {"start":"4.657","text": "They" },
            {"start":"4.824","text": "realized" },
            {"start":"5.587","text": "little" },
            {"start":"5.860","text": "Aji" },
            {"start":"6.376","text": "was" },
            {"start":"6.600","text": "only" },
            {"start":"6.908","text": "a" },
            {"start":"6.983","text": "shy" },
            {"start":"7.600","text": "lonely" },
            {"start":"8.267","text": "creature" },
            {"start":"9.347","text": "From" },
            {"start":"9.567","text": "that" },
            {"start":"9.841","text": "day" },
            {"start":"10.040","text": "on" },
            {"start":"10.717","text": "the" },
            {"start":"10.872","text": "Beans" },
            {"start":"11.275","text": "learned" },
            {"start":"11.667","text": "not" },
            {"start":"12.049","text": "to" },
            {"start":"12.237","text": "judge" },
            {"start":"12.570","text": "others" },
            {"start":"12.994","text": "by" },
            {"start":"13.198","text": "their" },
            {"start":"13.408","text": "looks" },
            {"start":"14.052","text": "or" },
            {"start":"14.400","text": "trust" },
            {"start":"14.713","text": "everything" },
            {"start":"15.331","text": "people" },
            {"start":"15.700","text": "say" }
]


/*--------------------------------Corean--------------------------------*/

var pistaKO1 = [
            { "start": "0.069","text": "요고폴리스에서" },
            { "start": "1.888","text": "아주" },
            { "start": "2.579","text": "멀리" },
            { "start": "3.325","text": "떨어진" },
            { "start": "3.879","text": "곳에," },
            { "start": "5.309","text": "아무도" },
            { "start": "6.127","text": "살지" },
            { "start": "6.862","text": "않는" },
            { "start": "7.988","text": "오래된" },
            { "start": "8.813","text": "성이" },
            { "start": "9.550","text": "있었어요." },
            { "start": "11.563","text": "그" },
            { "start": "11.969","text": "성" },
            { "start": "12.448","text": "안에는" },
            { "start": "13.900","text": "검은" },
            { "start": "14.682","text": "호수가" },
            { "start": "15.768","text": "있었고" },
            { "start": "17.360","text": "그" },
            { "start": "17.790","text": "호수" },
            { "start": "18.418","text": "안에는" },
            { "start": "19.781","text": "특별한" },
            { "start": "20.750","text": "생물이" },
            { "start": "22.012","text": "살고" },
            { "start": "22.826","text": "있었어요." }
]

var pistaKO2 = [
            { "start": "0.008","text": "해가" },
            { "start": "1.195","text": "떠" },
            { "start": "1.490","text": "있을" },
            { "start": "2.033","text": "때" },
            { "start": "2.888","text": "아무도" },
            { "start": "3.835","text": "그" },
            { "start": "4.224","text": "생물을" },
            { "start": "5.492","text": "본" },
            { "start": "5.782","text": "적이" },
            { "start": "6.395","text": "없지만," },
            { "start": "8.021","text": "모두" },
            { "start": "9.128","text": "그" },
            { "start": "9.591","text": "생물을" },
            { "start": "10.528","text": "두려워했어요." },
            { "start": "13.052","text": "많은" },
            { "start": "13.836","text": "사람들이" },
            { "start": "15.334","text": "호수에" },
            { "start": "16.221","text": "사는" },
            { "start": "16.952","text": "생물에" },
            { "start": "17.919","text": "대한" },
            { "start": "19.178","text": "무시무시한" },
            { "start": "20.609","text": "이야기를" },
            { "start": "21.884","text": "나누었어요." }
]

var pistaKO3 = [
            { "start": "0.015","text": "우리는" },
            { "start": "1.168","text": "그" },
            { "start": "1.557","text": "무서운" },
            { "start": "2.165","text": "생물을" },
            { "start": "2.924","text": "내쫓아야" },
            { "start": "3.850","text": "해." },
            { "start": "5.095","text": "빈이가" },
            { "start": "5.994","text": "말했어요." },
            { "start": "8.317","text": "맞아!" },
            { "start": "9.804","text": "다른" },
            { "start": "10.430","text": "빈이가" },
            { "start": "11.427","text": "소리쳤어요." },
            { "start": "13.818","text": "왜" },
            { "start": "14.206","text": "그" },
            { "start": "14.517","text": "생물을" },
            { "start": "15.273","text": "내쫓아야" },
            { "start": "16.157","text": "해?" },
            { "start": "17.190","text": "우리에게" },
            { "start": "18.106","text": "아무런" },
            { "start": "18.819","text": "잘못도" },
            { "start": "19.617","text": "하지" },
            { "start": "20.270","text": "않았는걸?" },
            { "start": "21.865","text": "티파니가" },
            { "start": "23.155","text": "중간에" },
            { "start": "24.020","text": "말했어요." }
]

var pistaKO4 = [
            { "start": "0.014","text": "그" },
            { "start": "0.356","text": "동물은" },
            { "start": "1.470","text": "너무" },
            { "start": "2.144","text": "무섭다고" },
            { "start": "2.857","text": "했어." },
            { "start": "4.522","text": "빈이가" },
            { "start": "5.414","text": "말했어요." },
            { "start": "8.069","text": "그" },
            { "start": "8.421","text": "동물이" },
            { "start": "9.625","text": "밤에" },
            { "start": "10.361","text": "호수를" },
            { "start": "11.068","text": "지나가는" },
            { "start": "11.921","text": "사람들을" },
            { "start": "13.197","text": "놀래킨다고" },
            { "start": "14.457","text": "들었어." },
            { "start": "16.483","text": "다른" },
            { "start": "17.090","text": "빈이가" },
            { "start": "18.116","text": "소리쳤어요." },
            { "start": "20.501","text": "너희" },
            { "start": "20.961","text": "중" },
            { "start": "21.464","text": "누구라도" },
            { "start": "22.380","text": "그" },
            { "start": "22.709","text": "생물을" },
            { "start": "23.442","text": "아는" },
            { "start": "23.785","text": "사람이" },
            { "start": "24.500","text": "있니?" },
            { "start": "25.771","text": "티파니가" },
            { "start": "26.877","text": "물었어요." },
            { "start": "28.672","text": "모두들" },
            { "start": "29.483","text": "서로를" },
            { "start": "30.341","text": "쳐다보기만" },
            { "start": "31.515","text": "하고" },
            { "start": "32.562","text": "대답을" },
            { "start": "33.422","text": "하지" },
            { "start": "34.384","text": "못했어요." },
            { "start": "35.975","text": "아무도" },
            { "start": "37.304","text": "그" },
            { "start": "37.626","text": "생물을" },
            { "start": "38.600","text": "직접" },
            { "start": "39.335","text": "알지" },
            { "start": "40.213","text": "못했거든요." },
            { "start": "42.520","text": "알지도" },
            { "start": "43.311","text": "못하는" },
            { "start": "44.075","text": "사람에" },
            { "start": "44.739","text": "대해서" },
            { "start": "45.510","text": "말을" },
            { "start": "45.974","text": "하는" },
            { "start": "46.381","text": "건" },
            { "start": "46.963","text": "불공평하지" },
            { "start": "48.150","text": "않아?" },
]

var pistaKO5 = [
            { "start": "0.054","text": "저길" },
            { "start": "0.532","text": "봐!" },
            { "start": "1.417","text": "저기" },
            { "start": "1.890","text": "있다." },
            { "start": "3.371","text": "한" },
            { "start": "3.859","text": "빈이가" },
            { "start": "4.660","text": "말했어요." },
            { "start": "6.250","text": "모두들" },
            { "start": "7.419","text": "고개를" },
            { "start": "8.190","text": "돌려서" },
            { "start": "9.446","text": "호수에" },
            { "start": "10.216","text": "산다는" },
            { "start": "11.335","text": "생물을" },
            { "start": "12.227","text": "보았어요." },
            { "start": "14.221","text": "내" },
            { "start": "14.581","text": "생각하고는" },
            { "start": "15.922","text": "전혀" },
            { "start": "16.401","text": "다르게" },
            { "start": "17.577","text": "무섭지도" },
            { "start": "18.375","text": "않고" },
            { "start": "19.191","text": "못생기지도" },
            { "start": "20.190","text": "않았네." },
            { "start": "21.940","text": "한" },
            { "start": "22.399","text": "빈이가" },
            { "start": "23.337","text": "말했어요." },
            { "start": "25.126","text": "안녕!" },
            { "start": "26.261","text": "나는" },
            { "start": "26.890","text": "알투리우스야." },
            { "start": "29.776","text": "나는" },
            { "start": "30.723","text": "티파니야." },
            { "start": "33.035","text": "나는" },
            { "start": "34.219","text": "아히라고" },
            { "start": "35.114","text": "해." },
            { "start": "36.507","text": "생물이" },
            { "start": "37.778","text": "자기" },
            { "start": "38.371","text": "소개를" },
            { "start": "39.116","text": "했어요." }
]

var pistaKO6 = [
            { "start": "0.028","text": "그날" },
            { "start": "0.543","text": "밤," },
            { "start": "1.405","text": "모두들" },
            { "start": "2.604","text": "자기의" },
            { "start": "3.395","text": "생각과" },
            { "start": "4.458","text": "이야기를" },
            { "start": "5.460","text": "나누었어요." },
            { "start": "7.476","text": "다들" },
            { "start": "8.690","text": "작은" },
            { "start": "9.389","text": "아히는" },
            { "start": "10.777","text": "그저" },
            { "start": "11.423","text": "수줍고" },
            { "start": "12.430","text": "외로운" },
            { "start": "13.285","text": "친구라는" },
            { "start": "14.172","text": "걸" },
            { "start": "14.767","text": "알게" },
            { "start": "15.375","text": "되었어요." },
            { "start": "17.574","text": "그날" },
            { "start": "18.191","text": "이후로," },
            { "start": "19.416","text": "빈이들은" },
            { "start": "20.775","text": "절대" },
            { "start": "22.087","text": "다른" },
            { "start": "22.586","text": "사람의" },
            { "start": "23.566","text": "외모를" },
            { "start": "24.392","text": "보고" },
            { "start": "25.004","text": "평가하거나" },
            { "start": "26.695","text": "다른" },
            { "start": "27.150","text": "사람들이" },
            { "start": "28.510","text": "하는" },
            { "start": "29.107","text": "얘기를" },
            { "start": "30.276","text": "모두" },
            { "start": "30.924","text": "믿지" },
            { "start": "31.550","text": "않기로" },
            { "start": "32.534","text": "결심했어요." }

]


