var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]


/*--------------------------------Spanish--------------------------------*/

var pistaES1 = [
        {"start": "0.159","text": "A" },
        {"start": "0.365","text": "Justice" },
        {"start": "1.078","text": "le" },
        {"start": "1.165","text": "encanta" },
        {"start": "1.967","text": "compartir" },
        {"start": "2.656","text": "sus" },
        {"start": "3.071","text": "cosas" },
        {"start": "3.548","text": "con" },
        {"start": "3.829","text": "Paz" },
        {"start": "4.845","text": "pero" },
        {"start": "5.000","text": "a" },
        {"start": "5.145","text": "veces" },
        {"start": "5.828","text": "se" },
        {"start": "6.167","text": "enoja" },
        {"start": "6.688","text": "mucho" },
        {"start": "7.268","text": "con" },
        {"start": "7.443","text": "ella" }
]
  
var pistaES2 = [
        {"start": "0.257","text": "Le" },
        {"start": "0.529","text": "molesta" },
        {"start": "1.190","text": "que" },
        {"start": "1.448","text": "Paz" },
        {"start": "2.459","text": "tome" },
        {"start": "2.782","text": "sus" },
        {"start": "3.108","text": "colores" },
        {"start": "3.564","text": "sin" },
        {"start": "3.928","text": "pedir" },
        {"start": "4.351","text": "permiso" }
];
  
var pistaES3 = [
        {"start": "0.185","text": "Le" },
        {"start": "0.426","text": "molesta" },
        {"start": "1.171","text": "que" },
        {"start": "1.407","text": "Paz" },
        {"start": "2.456","text": "tome" },
        {"start": "2.842","text": "su" },
        {"start": "3.000","text": "almuerzo" },
        {"start": "4.017","text": "sin" },
        {"start": "4.288","text": "pedir" },
        {"start": "4.916","text": "permiso" }
]

var pistaES4 = [
        {"start": "0.090","text": "Pero" },
        {"start": "0.368","text": "a" },
        {"start": "0.572","text": "Justice" },
        {"start": "1.637","text": "le" },
        {"start": "1.823","text": "molesta" },
        {"start": "2.425","text": "más" },
        {"start": "3.285","text": "que" },
        {"start": "3.496","text": "Paz" },
        {"start": "3.945","text": "no" },
        {"start": "4.193","text": "pida" },
        {"start": "4.700","text": "todas" },
        {"start": "5.181","text": "esas" },
        {"start": "5.666","text": "cosas" },
        {"start": "6.617","text": "utilizando" },
        {"start": "7.463","text": "las" },
        {"start": "7.711","text": "palabras" },
        {"start": "8.353","text": "mágicas" },
        {"start": "9.873","text": "por" },
        {"start": "10.336","text": "favor" }
]
 
var pistaES5 = [
        {"start": "0.193","text": "Un" },
        {"start": "0.445","text": "buen" },
        {"start": "0.764","text": "día" },
        {"start": "1.704","text": "Justice" },
        {"start": "2.442","text": "le" },
        {"start": "2.635","text": "negó" },
        {"start": "3.080","text": "los" },
        {"start": "3.400","text": "colores" },
        {"start": "4.448","text": "el" },
        {"start": "4.666","text": "almuerzo" },
        {"start": "5.471","text": "y" },
        {"start": "5.740","text": "sus" },
        {"start": "6.050","text": "cómics" },
        {"start": "7.746","text": "Paz" },
        {"start": "8.241","text": "se" },
        {"start": "8.534","text": "puso" },
        {"start": "8.820","text": "triste" },
        {"start": "10.162","text": "no" },
        {"start": "10.481","text": "sabía" },
        {"start": "11.295","text": "lo" },
        {"start": "11.480","text": "que" },
        {"start": "11.690","text": "estaba" },
        {"start": "12.092","text": "pasando" }
]
    
var pistaES6 = [
        {"start": "0.236","text": "Justice" },
        {"start": "1.029","text": "le" },
        {"start": "1.225","text": "dijo" },
        {"start": "1.495","text": "a" },
        {"start": "1.703","text": "Paz" },
        {"start": "3.536","text": "Te" },
        {"start": "3.727","text": "presto" },
        {"start": "4.137","text": "lo" },
        {"start": "4.356","text": "que" },
        {"start": "4.491","text": "tu" },
        {"start": "4.829","text": "quieras" },
        {"start": "5.863","text": "solo" },
        {"start": "6.296","text": "utiliza" },
        {"start": "7.049","text": "las" },
        {"start": "7.280","text": "palabras" },
        {"start": "7.909","text": "mágicas" },
        {"start": "8.994","text": "Por" },
        {"start": "9.264","text": "favor" },
        {"start": "11.760","text": "Paz" },
        {"start": "12.147","text": "entendio" },
        {"start": "12.839","text": "de" },
        {"start": "12.918","text": "inmediato" },
        {"start": "14.194","text": "y" },
        {"start": "14.373","text": "dijo" },
        {"start": "16.223","text": "Justice" },
        {"start": "17.583","text": "Podrías" },
        {"start": "18.758","text": "prestarme" },
        {"start": "18.747","text": "tus" },
        {"start": "19.039","text": "cómics" },
        {"start": "20.180","text": "Por" },
        {"start": "20.489","text": "favor" },
        {"start": "23.424","text": "Justice" },
        {"start": "24.081","text": "no" },
        {"start": "24.351","text": "pudo" },
        {"start": "24.649","text": "negarse" },
        {"start": "25.593","text": "y" },
        {"start": "25.689","text": "se" },
        {"start": "25.914","text": "los" },
        {"start": "26.167","text": "prestó" },
        {"start": "26.695","text": "con" },
        {"start": "27.050","text": "gusto" },
        {"start": "28.758","text": "Paz" },
        {"start": "29.438","text": "entendió" },
        {"start": "30.017","text": "el" },
        {"start": "30.147","text": "valor" },
        {"start": "30.596","text": "de" },
        {"start": "30.737","text": "las" },
        {"start": "30.950","text": "palabras" },
        {"start": "31.513","text": "mágicas" },
        {"start": "32.547","text": "que" },
        {"start": "32.665","text": "le" },
        {"start": "32.749","text": "había" },
        {"start": "33.058","text": "enseñado" },
        {"start": "33.829","text": "su" },
        {"start": "33.829","text": "amigo" }
]

/*--------------------------------English--------------------------------*/
 
var pistaEN1 = [
        {"start": "0.693","text": "Justice" },
        {"start": "1.272","text": "loves" },
        {"start": "1.751","text": "sharing" },
        {"start": "2.230","text": "his" },
        {"start": "2.433","text": "belongings" },
        {"start": "3.028","text": "with" },
        {"start": "3.234","text": "Paz" },
        {"start": "3.929","text": "although" },
        {"start": "4.272","text": "sometimes" },
        {"start": "4.931","text": "she" },
        {"start": "5.186","text": "makes" },
        {"start": "5.494","text": "him" },
        {"start": "5.737","text": "really" },
        {"start": "6.082","text": "mad" }
]

var pistaEN2 = [
        {"start": "0.694","text": "He" },
        {"start": "1.070","text": "dislikes" },
        {"start": "1.852","text": "when" },
        {"start": "2.080","text": "Paz" },
        {"start": "2.499","text": "takes" },
        {"start": "2.698","text": "his" },
        {"start": "2.976","text": "colored" },
        {"start": "3.246","text": "pencils" },
        {"start": "3.794","text": "without" },
        {"start": "4.117","text": "permission" }
]
  
var pistaEN3 = [
        {"start": "0.766","text": "He" },
        {"start": "1.034","text": "dislikes" },
        {"start": "1.816","text": "when" },
        {"start": "2.088","text": "Paz" },
        {"start": "2.488","text": "takes" },
        {"start": "2.760","text": "his" },
        {"start": "2.960","text": "lunch" },
        {"start": "3.416","text": "without" },
        {"start": "3.758","text": "permission" }
]

var pistaEN4 = [
        {"start": "0.783","text": "But" },
        {"start": "1.464","text": "what" },
        {"start": "1.748","text": "Justice" },
        {"start": "2.436","text": "dislikes" },
        {"start": "3.111","text": "the" },
        {"start": "3.193","text": "most" },
        {"start": "3.723","text": "is" },
        {"start": "3.925","text": "that" },
        {"start": "4.140","text": "Paz" },
        {"start": "4.613","text": "takes" },
        {"start": "5.000","text": "all" },
        {"start": "5.143","text": "of" },
        {"start": "5.269","text": "his" },
        {"start": "5.433","text": "stuff" },
        {"start": "5.945","text": "without" },
        {"start": "6.487","text": "using" },
        {"start": "6.942","text": "the" },
        {"start": "7.017","text": "magic" },
        {"start": "7.500","text": "word" },
        {"start": "8.286","text": "Please" }
]
   
var pistaEN5 = [
        {"start": "0.631","text": "One" },
        {"start": "0.966","text": "day" },
        {"start": "1.697","text": "Justice" },
        {"start": "2.231","text": "refused" },
        {"start": "2.925","text": "to" },
        {"start": "3.091","text": "share" },
        {"start": "3.386","text": "his" },
        {"start": "3.585","text": "colored" },
        {"start": "3.924","text": "pencils" },
        {"start": "4.573","text": "comics" },
        {"start": "5.112","text": "and" },
        {"start": "5.256","text": "lunch" },
        {"start": "5.665","text": "with" },
        {"start": "5.850","text": "Paz" },
        {"start": "6.978","text": "She" },
        {"start": "7.200","text": "got" },
        {"start": "7.447","text": "really" },
        {"start": "7.771","text": "sad" },
        {"start": "8.343","text": "because" },
        {"start": "8.686","text": "she" },
        {"start": "8.896","text": "couldn't" },
        {"start": "9.176","text": "figure" },
        {"start": "9.527","text": "out" },
        {"start": "9.763","text": "what" },
        {"start": "10.065","text": "was" },
        {"start": "10.257","text": "wrong" }
]

var pistaEN6 = [
        {"start": "0.624","text": "Justice" },
        {"start": "1.281","text": "talked" },
        {"start": "1.821","text": "to" },
        {"start": "2.062","text": "Paz" },
        {"start": "3.010","text": "I'll" },
        {"start": "3.359","text": "lend" },
        {"start": "3.592","text": "you" },
        {"start": "3.892","text": "whatever" },
        {"start": "4.307","text": "you" },
        {"start": "4.500","text": "want" },
        {"start": "5.305","text": "just" },
        {"start": "6.037","text": "use" },
        {"start": "6.353","text": "the" },
        {"start": "6.461","text": "magic" },
        {"start": "6.869","text": "word" },
        {"start": "7.958","text": "please" },
        {"start": "9.970","text": "Paz" },
        {"start": "10.361","text": "immediately" },
        {"start": "11.159","text": "understood" },
        {"start": "11.875","text": "and" },
        {"start": "12.191","text": "said" },
        {"start": "12.789","text": "Justice" },
        {"start": "13.729","text": "can" },
        {"start": "14.087","text": "I" },
        {"start": "14.402","text": "borrow" },
        {"start": "14.818","text": "your" },
        {"start": "15.000","text": "comics" },
        {"start": "16.124","text": "PLEASE" },
        {"start": "18.000","text": "Justice" },
        {"start": "18.577","text": "lent" },
        {"start": "18.860","text": "them" },
        {"start": "19.134","text": "to" },
        {"start": "19.300","text": "her" },
        {"start": "19.492","text": "gladly" },
        {"start": "20.639","text": "Paz" },
        {"start": "21.113","text": "understood" },
        {"start": "21.878","text": "the" },
        {"start": "22.053","text": "value" },
        {"start": "22.585","text": "of" },
        {"start": "22.743","text": "the" },
        {"start": "22.884","text": "magic" },
        {"start": "23.375","text": "word" },
        {"start": "23.674","text": "that" },
        {"start": "23.874","text": "her" },
        {"start": "24.215","text": "friend" },
        {"start": "24.547","text": "taught" },
        {"start": "24.739","text": "her" }
]


/*--------------------------------Korean--------------------------------*/


var pistaKO1 = [
        { "start": "0.000","text": "저스티스는" },
        { "start": "2.272","text": "파즈와" },
        { "start": "3.673","text": "물건을" },
        { "start": "5.099","text": "나눠" },
        { "start": "5.884","text": "쓰는" },
        { "start": "6.470","text": "걸" },
        { "start": "7.350","text": "좋아해요." },
        { "start": "9.837","text": "하지만" },
        { "start": "11.529","text": "파즈는" },
        { "start": "13.339","text": "가끔" },
        { "start": "14.908","text": "저스티스를" },
        { "start": "17.218","text": "정말" },
        { "start": "18.602","text": "화나게" },
        { "start": "19.748","text": "해요." },
]

var pistaKO2 = [
        { "start": "0.016","text": "저스티스는" },
        { "start": "2.261","text": "파즈가" },
        { "start": "3.859","text": "묻지도" },
        { "start": "5.187","text": "않고" },
        { "start": "6.776","text": "자기" },
        { "start": "8.124","text": "색연필을" },
        { "start": "10.177","text": "가져가는" },
        { "start": "11.332","text": "걸" },
        { "start": "12.456","text": "싫어해요." },
]

var pistaKO3 = [
        { "start": "0.000","text": "저스티스는" },
        { "start": "2.335","text": "파즈가" },
        { "start": "4.081","text": "묻지도" },
        { "start": "5.440","text": "않고" },
        { "start": "7.056","text": "자기" },
        { "start": "8.480","text": "점심을" },
        { "start": "10.190","text": "가져가는" },
        { "start": "11.449","text": "걸" },
        { "start": "12.505","text": "싫어해요." },
]

var pistaKO4 = [
        { "start": "0.012","text": "하지만," },
        { "start": "1.698","text": "저스티스를" },
        { "start": "4.024","text": "가장" },
        { "start": "5.439","text": "화나게" },
        { "start": "6.934","text": "하는" },
        { "start": "7.675","text": "건" },
        { "start": "8.999","text": "따로" },
        { "start": "10.231","text": "있어요." },
        { "start": "12.727","text": "파즈는" },
        { "start": "14.531","text": "'부탁해'라는" },
        { "start": "17.556","text": "마법" },
        { "start": "18.393","text": "같은" },
        { "start": "19.331","text": "말을" },
        { "start": "20.562","text": "전혀" },
        { "start": "21.898","text": "하지" },
        { "start": "22.693","text": "않고" },
        { "start": "24.084","text": "저스티스의" },
        { "start": "26.055","text": "물건을" },
        { "start": "27.592","text": "막" },
        { "start": "28.498","text": "가져가요." },
]

var pistaKO5 = [
        { "start": "0.000","text": "어느" },
        { "start": "0.574","text": "날," },
        { "start": "1.453","text": "저스티스는" },
        { "start": "3.750","text": "파즈와" },
        { "start": "5.392","text": "색연필," },
        { "start": "7.115","text": "만화책," },
        { "start": "8.584","text": "점심을" },
        { "start": "10.051","text": "나누지" },
        { "start": "11.084","text": "않았어요." },
        { "start": "13.250","text": "파즈는" },
        { "start": "14.903","text": "뭐가" },
        { "start": "15.785","text": "잘못" },
        { "start": "16.694","text": "되었는지" },
        { "start": "18.319","text": "몰라서" },
        { "start": "19.800","text": "굉장히" },
        { "start": "20.943","text": "슬펐어요." },
]

var pistaKO6 = [
        { "start": "0.000","text": "저스티스는" },
        { "start": "2.339","text": "파즈에게" },
        { "start": "3.982","text": "말했어요." },
        { "start": "6.787","text": "나는" },
        { "start": "8.172","text": "너에게" },
        { "start": "9.765","text": "뭐든" },
        { "start": "11.200","text": "빌려줄" },
        { "start": "12.389","text": "거야." },
        { "start": "14.279","text": "대신," },
        { "start": "15.769","text": "너는" },
        { "start": "17.343","text": "'부탁해'라는" },
        { "start": "19.729","text": "마법의" },
        { "start": "20.808","text": "단어를" },
        { "start": "22.484","text": "써야" },
        { "start": "23.409","text": "해." },
        { "start": "25.210","text": "파즈는" },
        { "start": "26.671","text": "바로" },
        { "start": "27.444","text": "알아듣고" },
        { "start": "28.989","text": "말했어요." },
        { "start": "31.627","text": "저스티스야," },
        { "start": "33.728","text": "네" },
        { "start": "34.188","text": "만화책을" },
        { "start": "36.127","text": "빌릴" },
        { "start": "36.659","text": "수" },
        { "start": "37.365","text": "있을까?" },
        { "start": "39.290","text": "부탁해." },
        { "start": "41.873","text": "저스티스는" },
        { "start": "43.980","text": "기쁜" },
        { "start": "44.905","text": "마음으로" },
        { "start": "46.522","text": "만화책을" },
        { "start": "48.278","text": "빌려줬어요." },
        { "start": "51.198","text": "파즈는" },
        { "start": "52.943","text": "저스티스가" },
        { "start": "54.670","text": "알려준" },
        { "start": "56.293","text": "마법의" },
        { "start": "57.394","text": "단어가" },
        { "start": "59.508","text": "얼마나" },
        { "start": "60.851","text": "중요한지" },
        { "start": "62.625","text": "이해했어요." },
]


