var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]


/*--------------------------------Spanish--------------------------------*/

var pistaES1 = [
        {"start": "","text": "En" },
        {"start": "","text": "Yogópolis" },
        {"start": "","text": "no" },
        {"start": "","text": "todo" },
        {"start": "","text": "es" },
        {"start": "","text": "paz" },
        {"start": "","text": "y" },
        {"start": "","text": "tranquilidad" },
        {"start": "","text": "Algunas" },
        {"start": "","text": "veces" },
        {"start": "","text": "hay" },
        {"start": "","text": "problemas" },
        {"start": "","text": "mayores" },
        {"start": "","text": "que" },
        {"start": "","text": "nuestros" },
        {"start": "","text": "héroes" },
        {"start": "","text": "deben" },
        {"start": "","text": "atender" }
]
  
var pistaES2 = [
        {"start": "","text": "El" },
        {"start": "","text": "día" },
        {"start": "","text": "de" },
        {"start": "","text": "la" },
        {"start": "","text": "invasión" },
        {"start": "","text": "los" },
        {"start": "","text": "Yogotars" },
        {"start": "","text": "actuaron" },
        {"start": "","text": "rápidamente" },
        {"start": "","text": "Luna" },
        {"start": "","text": "Activa" },
        {"start": "","text": "tu" },
        {"start": "","text": "campo" },
        {"start": "","text": "de" },
        {"start": "","text": "defensa" },
        {"start": "","text": "gritó" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "Oye" },
        {"start": "","text": "ya" },
        {"start": "","text": "lo" },
        {"start": "","text": "hice" },
        {"start": "","text": "no" },
        {"start": "","text": "tienes" },
        {"start": "","text": "que" },
        {"start": "","text": "gritarme" },
        {"start": "","text": "dijo" },
        {"start": "","text": "Luna" },
        {"start": "","text": "molesta" }
];
  
var pistaES3 = [
        {"start": "","text": "Oof" },
        {"start": "","text": "salta" },
        {"start": "","text": "y" },
        {"start": "","text": "derriba" },
        {"start": "","text": "su" },
        {"start": "","text": "rayo" },
        {"start": "","text": "paralizador" },
        {"start": "","text": "gritó" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "Oof" },
        {"start": "","text": "no" },
        {"start": "","text": "dijo" },
        {"start": "","text": "nada" },
        {"start": "","text": "pero" },
        {"start": "","text": "algo" },
        {"start": "","text": "en" },
        {"start": "","text": "la" },
        {"start": "","text": "actitud" },
        {"start": "","text": "de" },
        {"start": "","text": "su" },
        {"start": "","text": "compañero" },
        {"start": "","text": "le" },
        {"start": "","text": "molestó" }
]

var pistaES4 = [
        {"start": "","text": "Eres" },
        {"start": "","text": "muy" },
        {"start": "","text": "lento" },
        {"start": "","text": "Dinamita" },
        {"start": "","text": "déjame" },
        {"start": "","text": "eso" },
        {"start": "","text": "a" },
        {"start": "","text": "mi" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "le" },
        {"start": "","text": "arrebató" },
        {"start": "","text": "el" },
        {"start": "","text": "cañón" },
        {"start": "","text": "de" },
        {"start": "","text": "patos" },
        {"start": "","text": "de" },
        {"start": "","text": "hule" },
        {"start": "","text": "a" },
        {"start": "","text": "Dinamita" },
        {"start": "","text": "él" },
        {"start": "","text": "no" },
        {"start": "","text": "dijo" },
        {"start": "","text": "nada" },
        {"start": "","text": "pero" },
        {"start": "","text": "los" },
        {"start": "","text": "modales" },
        {"start": "","text": "de" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "no" },
        {"start": "","text": "le" },
        {"start": "","text": "parecieron" },
        {"start": "","text": "los" },
        {"start": "","text": "correctos" }
]
 
var pistaES5 = [
        {"start": "","text": "Al" },
        {"start": "","text": "final" },
        {"start": "","text": "los" },
        {"start": "","text": "Yogotars" },
        {"start": "","text": "lograron" },
        {"start": "","text": "detener" },
        {"start": "","text": "la" },
        {"start": "","text": "invasión" },
        {"start": "","text": "a" },
        {"start": "","text": "Yogópolis" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "parecía" },
        {"start": "","text": "muy" },
        {"start": "","text": "contento" },
        {"start": "","text": "pero" },
        {"start": "","text": "el" },
        {"start": "","text": "resto" },
        {"start": "","text": "de" },
        {"start": "","text": "sus" },
        {"start": "","text": "compañeros" },
        {"start": "","text": "no" },
        {"start": "","text": "lo" },
        {"start": "","text": "estaban" },
        {"start": "","text": "Lo" },
        {"start": "","text": "logramos" },
        {"start": "","text": "Que" },
        {"start": "","text": "les" },
        {"start": "","text": "parece" },
        {"start": "","text": "si" },
        {"start": "","text": "celebramos" },
        {"start": "","text": "dijo" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "muy" },
        {"start": "","text": "emocionado" },
        {"start": "","text": "Sus" },
        {"start": "","text": "compañeros" },
        {"start": "","text": "no" },
        {"start": "","text": "le" },
        {"start": "","text": "hicieron" },
        {"start": "","text": "caso" }
]
   
var pistaES6 = [
        {"start": "","text": "Amigos" },
        {"start": "","text": "dijo" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "El" },
        {"start": "","text": "resto" },
        {"start": "","text": "de" },
        {"start": "","text": "Yogotars" },
        {"start": "","text": "lo" },
        {"start": "","text": "dejaron" },
        {"start": "","text": "solo" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "estaba" },
        {"start": "","text": "desconcertado" },
        {"start": "","text": "no" },
        {"start": "","text": "sabía" },
        {"start": "","text": "qué" },
        {"start": "","text": "había" },
        {"start": "","text": "hecho" },
        {"start": "","text": "mal" },
        {"start": "","text": "Lo" },
        {"start": "","text": "siento" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "el" },
        {"start": "","text": "equipo" },
        {"start": "","text": "no" },
        {"start": "","text": "está" },
        {"start": "","text": "muy" },
        {"start": "","text": "contento" },
        {"start": "","text": "contigo" },
        {"start": "","text": "dijo" },
        {"start": "","text": "Luna" },
        {"start": "","text": "Que" },
        {"start": "","text": "fue" },
        {"start": "","text": "lo" },
        {"start": "","text": "que" },
        {"start": "","text": "hice" },
        {"start": "","text": "Son" },
        {"start": "","text": "tus" },
        {"start": "","text": "modales" },
        {"start": "","text": "no" },
        {"start": "","text": "hubo" },
        {"start": "","text": "un" },
        {"start": "","text": "por" },
        {"start": "","text": "favor" },
        {"start": "","text": "ni" },
        {"start": "","text": "un" },
        {"start": "","text": "gracias" },
        {"start": "","text": "respondió" },
        {"start": "","text": "Luna" },
        {"start": "","text": "algo" },
        {"start": "","text": "molesta" },
        {"start": "","text": "Pero" },
        {"start": "","text": "yo" },
        {"start": "","text": "dijo" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "CONTINUARÁ" }
]

/*--------------------------------English--------------------------------*/
 
var pistaEN1 = [
        {"start": "","text": "Yogopolis" },
        {"start": "","text": "is" },
        {"start": "","text": "not" },
        {"start": "","text": "always" },
        {"start": "","text": "at" },
        {"start": "","text": "peace" },
        {"start": "","text": "Sometimes" },
        {"start": "","text": "big" },
        {"start": "","text": "problems" },
        {"start": "","text": "arise" },
        {"start": "","text": "and" },
        {"start": "","text": "our" },
        {"start": "","text": "heroes" },
        {"start": "","text": "have" },
        {"start": "","text": "to" },
        {"start": "","text": "save" },
        {"start": "","text": "the" },
        {"start": "","text": "day" }
]

var pistaEN2 = [
        {"start": "","text": "On" },
        {"start": "","text": "the" },
        {"start": "","text": "invasion" },
        {"start": "","text": "day" },
        {"start": "","text": "the" },
        {"start": "","text": "yogotars" },
        {"start": "","text": "had" },
        {"start": "","text": "to" },
        {"start": "","text": "act" },
        {"start": "","text": "quickly" },
        {"start": "","text": "Luna" },
        {"start": "","text": "turn" },
        {"start": "","text": "on" },
        {"start": "","text": "your" },
        {"start": "","text": "force" },
        {"start": "","text": "field" },
        {"start": "","text": "shouted" },
        {"start": "","text": "eagle" },
        {"start": "","text": "hey" },
        {"start": "","text": "I" },
        {"start": "","text": "already" },
        {"start": "","text": "did" },
        {"start": "","text": "that" },
        {"start": "","text": "you" },
        {"start": "","text": "don't" },
        {"start": "","text": "have" },
        {"start": "","text": "to" },
        {"start": "","text": "yell" },
        {"start": "","text": "at" },
        {"start": "","text": "me" },
        {"start": "","text": "answered" },
        {"start": "","text": "Luna" },
        {"start": "","text": "mad" }
]
  
var pistaEN3 = [
        {"start": "","text": "Oof" },
        {"start": "","text": "jump" },
        {"start": "","text": "and" },
        {"start": "","text": "take" },
        {"start": "","text": "down" },
        {"start": "","text": "their" },
        {"start": "","text": "paralyzing" },
        {"start": "","text": "beam" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "shouted" },
        {"start": "","text": "Oof" },
        {"start": "","text": "did" },
        {"start": "","text": "not" },
        {"start": "","text": "say" },
        {"start": "","text": "anything" },
        {"start": "","text": "but" },
        {"start": "","text": "there" },
        {"start": "","text": "was" },
        {"start": "","text": "something" },
        {"start": "","text": "about" },
        {"start": "","text": "his" },
        {"start": "","text": "peer's" },
        {"start": "","text": "attitude" },
        {"start": "","text": "that" },
        {"start": "","text": "made" },
        {"start": "","text": "him" },
        {"start": "","text": "mad" },
]

var pistaEN4 = [
        {"start": "","text": "You" },
        {"start": "","text": "are" },
        {"start": "","text": "too" },
        {"start": "","text": "slow" },
        {"start": "","text": "Dinamita" },
        {"start": "","text": "gime" },
        {"start": "","text": "that" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "snarled" },
        {"start": "","text": "as" },
        {"start": "","text": "he" },
        {"start": "","text": "snatched" },
        {"start": "","text": "the" },
        {"start": "","text": "rubber-duck" },
        {"start": "","text": "shooter" },
        {"start": "","text": "from" },
        {"start": "","text": "Dinamita's" },
        {"start": "","text": "hands" },
        {"start": "","text": "Dinamita" },
        {"start": "","text": "kept" },
        {"start": "","text": "quiet" },
        {"start": "","text": "but" },
        {"start": "","text": "he" },
        {"start": "","text": "thought" },
        {"start": "","text": "Eagle's" },
        {"start": "","text": "manners" },
        {"start": "","text": "could" },
        {"start": "","text": "be" },
        {"start": "","text": "better" }
]
   
var pistaEN5 = [
        {"start": "","text": "In" },
        {"start": "","text": "the" },
        {"start": "","text": "end" },
        {"start": "","text": "the" },
        {"start": "","text": "Yogotars" },
        {"start": "","text": "were" },
        {"start": "","text": "able" },
        {"start": "","text": "to" },
        {"start": "","text": "stop" },
        {"start": "","text": "the" },
        {"start": "","text": "invasion" },
        {"start": "","text": "of" },
        {"start": "","text": "Yogopolis" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "seemed" },
        {"start": "","text": "to" },
        {"start": "","text": "be" },
        {"start": "","text": "very" },
        {"start": "","text": "happy" },
        {"start": "","text": "but" },
        {"start": "","text": "the" },
        {"start": "","text": "rest" },
        {"start": "","text": "of" },
        {"start": "","text": "the" },
        {"start": "","text": "team" },
        {"start": "","text": "wasn't" },
        {"start": "","text": "We" },
        {"start": "","text": "did" },
        {"start": "","text": "it" },
        {"start": "","text": "Why" },
        {"start": "","text": "don't" },
        {"start": "","text": "we" },
        {"start": "","text": "go" },
        {"start": "","text": "out" },
        {"start": "","text": "to" },
        {"start": "","text": "celebrate" },
        {"start": "","text": "said" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "excitedly" },
        {"start": "","text": "but" },
        {"start": "","text": "his" },
        {"start": "","text": "friends" },
        {"start": "","text": "didn't" },
        {"start": "","text": "follow" },
        {"start": "","text": "him" }
]

var pistaEN6 = [
        {"start": "","text": "Team" },
        {"start": "","text": "asked" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "The" },
        {"start": "","text": "rest" },
        {"start": "","text": "of" },
        {"start": "","text": "the" },
        {"start": "","text": "Yogotars" },
        {"start": "","text": "left" },
        {"start": "","text": "him" },
        {"start": "","text": "by" },
        {"start": "","text": "himself" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "was" },
        {"start": "","text": "confused" },
        {"start": "","text": "he" },
        {"start": "","text": "didn't" },
        {"start": "","text": "know" },
        {"start": "","text": "what" },
        {"start": "","text": "he" },
        {"start": "","text": "did" },
        {"start": "","text": "wrong" },
        {"start": "","text": "Sorry" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "the" },
        {"start": "","text": "team" },
        {"start": "","text": "is" },
        {"start": "","text": "not" },
        {"start": "","text": "quite" },
        {"start": "","text": "happy" },
        {"start": "","text": "with" },
        {"start": "","text": "you" },
        {"start": "","text": "said" },
        {"start": "","text": "Luna" },
        {"start": "","text": "What" },
        {"start": "","text": "did" },
        {"start": "","text": "I" },
        {"start": "","text": "do" },
        {"start": "","text": "It's" },
        {"start": "","text": "because" },
        {"start": "","text": "of" },
        {"start": "","text": "your" },
        {"start": "","text": "manners" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "You" },
        {"start": "","text": "never" },
        {"start": "","text": "said" },
        {"start": "","text": "please" },
        {"start": "","text": "or" },
        {"start": "","text": "thank" },
        {"start": "","text": "you" },
        {"start": "","text": "answered" },
        {"start": "","text": "Luna" },
        {"start": "","text": "a" },
        {"start": "","text": "little" },
        {"start": "","text": "angry" },
        {"start": "","text": "But" },
        {"start": "","text": "I" },
        {"start": "","text": "said" },
        {"start": "","text": "Eagle" },
        {"start": "","text": "embarrassed" },
        {"start": "","text": "TO BE CONTINUED" }
]


/*--------------------------------Korean--------------------------------*/


var pistaKO1 = [
        { "start": "0.005","text": "요고폴리스는" },
        { "start": "2.044","text": "항상" },
        { "start": "3.003","text": "평화롭지는" },
        { "start": "4.478","text": "않아요." },
        { "start": "6.271","text": "가끔" },
        { "start": "7.526","text": "큰" },
        { "start": "8.308","text": "문제가" },
        { "start": "9.252","text": "생기고" },
        { "start": "10.753","text": "우리의" },
        { "start": "11.553","text": "히어로들은" },
        { "start": "13.251","text": "그" },
        { "start": "13.787","text": "문제를" },
        { "start": "14.950","text": "해결해야만" },
        { "start": "16.165","text": "해요." }
]

var pistaKO2 = [
        { "start": "0.009","text": "공격을" },
        { "start": "0.990","text": "받은" },
        { "start": "1.738","text": "어느" },
        { "start": "2.312","text": "날," },
        { "start": "3.307","text": "요고타들은" },
        { "start": "5.052","text": "재빠르게" },
        { "start": "6.360","text": "행동해야" },
        { "start": "7.466","text": "했어요." },
        { "start": "10.032","text": "루나야!" },
        { "start": "11.109","text": "네" },
        { "start": "11.311","text": "방어막을" },
        { "start": "11.988","text": "얼른" },
        { "start": "12.436","text": "켜!" },
        { "start": "13.673","text": "이글이가" },
        { "start": "14.686","text": "소리쳤어요." },
        { "start": "17.313","text": "야!" },
        { "start": "18.300","text": "이미" },
        { "start": "18.625","text": "켜" },
        { "start": "18.775","text": "놨어." },
        { "start": "20.035","text": "나한테" },
        { "start": "20.838","text": "소리를" },
        { "start": "21.484","text": "지를" },
        { "start": "22.003","text": "필요는" },
        { "start": "22.541","text": "없어." },
        { "start": "24.304","text": "루나가" },
        { "start": "25.663","text": "화난" },
        { "start": "26.392","text": "목소리로" },
        { "start": "27.600","text": "대답했어요." }
]

var pistaKO3 = [
        { "start": "0.002","text": "우프," },
        { "start": "1.032","text": "점프해" },
        { "start": "1.640","text": "가서" },
        { "start": "2.555","text": "적들의" },
        { "start": "3.410","text": "마비" },
        { "start": "3.824","text": "광선을" },
        { "start": "4.490","text": "치워!" },
        { "start": "6.437","text": "이글이가" },
        { "start": "7.551","text": "소리쳤어요." },
        { "start": "9.901","text": "우프는" },
        { "start": "11.247","text": "아무" },
        { "start": "11.882","text": "말도" },
        { "start": "12.754","text": "하지" },
        { "start": "13.243","text": "않았지만," },
        { "start": "14.919","text": "우프를" },
        { "start": "15.853","text": "화나게" },
        { "start": "16.411","text": "한" },
        { "start": "17.395","text": "친구의" },
        { "start": "18.247","text": "태도에는" },
        { "start": "19.685","text": "문제가" },
        { "start": "20.650","text": "있어" },
        { "start": "21.320","text": "보였어요." }
]

var pistaKO4 = [
        { "start": "0.005","text": "다이나미타," },
        { "start": "1.291","text": "너는" },
        { "start": "1.763","text": "너무" },
        { "start": "2.212","text": "느려." },
        { "start": "3.320","text": "그거" },
        { "start": "3.892","text": "이리" },
        { "start": "4.250","text": "내." },
        { "start": "5.585","text": "이글이가" },
        { "start": "6.928","text": "으르렁거리면서" },
        { "start": "9.002","text": "다이나미타의" },
        { "start": "10.268","text": "손에서" },
        { "start": "11.734","text": "고무" },
        { "start": "12.347","text": "오리" },
        { "start": "12.901","text": "대포를" },
        { "start": "14.144","text": "뺏어왔어요." },
        { "start": "16.896","text": "다이나미타는" },
        { "start": "18.630","text": "조용히" },
        { "start": "19.420","text": "있었지만," },
        { "start": "21.068","text": "이글이가" },
        { "start": "22.383","text": "좀" },
        { "start": "22.826","text": "더" },
        { "start": "23.763","text": "좋은" },
        { "start": "24.361","text": "태도를" },
        { "start": "25.423","text": "보였으면" },
        { "start": "26.476","text": "좋겠다고" },
        { "start": "27.827","text": "생각했어요." }
        ]

var pistaKO5 = [
        { "start": "0.001","text": "결국," },
        { "start": "1.072","text": "요고타들은" },
        { "start": "2.710","text": "요고폴리스를" },
        { "start": "4.109","text": "침략하는" },
        { "start": "5.468","text": "적들을" },
        { "start": "6.719","text": "성공적으로" },
        { "start": "8.005","text": "막았어요." },
        { "start": "10.758","text": "이글이는" },
        { "start": "12.177","text": "굉장히" },
        { "start": "13.150","text": "신나" },
        { "start": "13.885","text": "보였지만," },
        { "start": "15.464","text": "다른" },
        { "start": "16.043","text": "친구들은" },
        { "start": "17.671","text": "그렇지" },
        { "start": "18.443","text": "않아" },
        { "start": "19.022","text": "보였어요." },
        { "start": "21.355","text": "우리가" },
        { "start": "21.773","text": "해냈어!" },
        { "start": "23.184","text": "우리의" },
        { "start": "23.609","text": "승리를" },
        { "start": "24.458","text": "기념하러" },
        { "start": "25.103","text": "가자." },
        { "start": "27.359","text": "이글이가" },
        { "start": "28.817","text": "들뜬" },
        { "start": "29.669","text": "목소리로" },
        { "start": "30.680","text": "말했지만," },
        { "start": "32.329","text": "친구들은" },
        { "start": "33.891","text": "이글이를" },
        { "start": "34.871","text": "따르지" },
        { "start": "35.609","text": "않았어요." }
]

var pistaKO6 = [
        { "start": "0.005","text": "친구들아?" },
        { "start": "1.412","text": "이글이가" },
        { "start": "2.509","text": "물었어요." },
        { "start": "4.788","text": "요고타들은" },
        { "start": "6.378","text": "이글이를" },
        { "start": "7.312","text": "혼자" },
        { "start": "8.139","text": "두고" },
        { "start": "8.885","text": "떠났어요." },
        { "start": "11.370","text": "이글이는" },
        { "start": "12.766","text": "자기가" },
        { "start": "13.717","text": "뭘" },
        { "start": "14.230","text": "잘못했는지" },
        { "start": "15.462","text": "몰라서" },
        { "start": "16.938","text": "그" },
        { "start": "17.267","text": "상황을" },
        { "start": "18.586","text": "이해할" },
        { "start": "19.246","text": "수" },
        { "start": "19.724","text": "없었어요." },
        { "start": "22.887","text": "이글아" },
        { "start": "24.009","text": "미안하지만," },
        { "start": "25.800","text": "친구들이" },
        { "start": "26.800","text": "너와" },
        { "start": "27.216","text": "있고" },
        { "start": "27.842","text": "싶지" },
        { "start": "28.426","text": "않아" },
        { "start": "28.851","text": "해." },
        { "start": "30.510","text": "루나가" },
        { "start": "31.534","text": "말했어요." },
        { "start": "33.953","text": "내가" },
        { "start": "34.337","text": "뭘" },
        { "start": "34.500","text": "했길래?"},
        { "start": "37.512","text": "너의" },
        { "start": "37.968","text": "태도" },
        { "start": "38.369","text": "때문이야" },
        { "start": "39.031","text": "이글아." },
        { "start": "40.330","text": "너는" },
        { "start": "41.300","text": "'부탁해'" },
        { "start": "42.594","text": "아니면" },
        { "start": "43.639","text": "'고마워'라고" },
        { "start": "45.187","text": "한" },
        { "start": "45.429","text": "번도" },
        { "start": "45.788","text": "말하지" },
        { "start": "46.254","text": "않았잖아." },
        { "start": "48.981","text": "루나가" },
        { "start": "50.134","text": "화난" },
        { "start": "50.800","text": "목소리로" },
        { "start": "51.786","text": "대답했어요." },
        { "start": "54.844","text": "그렇지만..." },
        { "start": "56.580","text": "난" },
        { "start": "58.100","text": "이글이는" },
        { "start": "59.284","text": "당황한" },
        { "start": "1:00.120","text": "목소리로" },
        { "start": "1:01.152","text": "말했어요." },
        { "start": "1:03.546","text": "이야기는" },
        { "start": "1:04.582","text": "계속됩니다." },
]


