var pistaES0 = [{ "start": "0.000","text": "empty" }]
var pistaEN0 = [{ "start": "0.000","text": "empty" }]
var pistaPT0 = [{ "start": "0.000","text": "empty" }]
var pistaZH0 = [{ "start": "0.000","text": "empty" }]
var pistaJA0 = [{ "start": "0.000","text": "empty" }]
var pistaKO0 = [{ "start": "0.000","text": "empty" }]


/*--------------------------------Spanish--------------------------------*/

var pistaES1 = [
        {"start": "0.318","text": "que" },
        {"start": "0.616","text": "es" },
        {"start": "0.934","text": "lo" },
        {"start": "1.140","text": "que" },
        {"start": "1.218","text": "mas" },
        {"start": "1.472","text": "les" },
        {"start": "1.814","text": "gusta" },
        {"start": "2.267","text": "de" },
        {"start": "2.375","text": "la" },
        {"start": "2.555","text": "galaxia" },
        {"start": "3.296","text": "ignos" },
        {"start": "5.346","text": "preguntó" },
        {"start": "5.884","text": "el" },
        {"start": "6.040","text": "general" },
        {"start": "6.636","text": "Sharp" },
        {"start": "7.407","text": "a" },
        {"start": "7.529","text": "los" },
        {"start": "7.742","text": "Yogotars" }
]
  
var pistaES2 = [
        {"start": "0.569","text": "La" },
        {"start": "0.800","text": "comida" },
        {"start": "2.498","text": "dijo" },
        {"start": "2.850","text": "Dinamita" },
        {"start": "4.817","text": "los" },
        {"start": "5.159","text": "libros" },
        {"start": "7.122","text": "dijo" },
        {"start": "7.657","text": "oona" },
        {"start": "9.354","text": "y" },
        {"start": "9.485","text": "a" },
        {"start": "9.668","text": "ti" },
        {"start": "10.000","text": "Arthurius" },
        {"start": "12.026","text": "preguntó" },
        {"start": "12.800","text": "Sharp" }
];

var pistaES3 = [
        {"start": "0.225","text": "Arthurius" },
        {"start": "1.011","text": "se" },
        {"start": "1.131","text": "quedo" },
        {"start": "1.400","text": "en" },
        {"start": "1.585","text": "silencio" },
        {"start": "3.120","text": "parecía" },
        {"start": "3.695","text": "distraído" },
        {"start": "6.263","text": "Theffanie" },
        {"start": "6.926","text": "se" },
        {"start": "7.278","text": "dio" },
        {"start": "7.556","text": "cuenta" },
        {"start": "7.900","text": "de" },
        {"start": "8.168","text": "ello" },
        {"start": "8.910","text": "y" },
        {"start": "9.077","text": "utilizó" },
        {"start": "9.517","text": "el" },
        {"start": "9.758","text": "poder" },
        {"start": "10.090","text": "de" },
        {"start": "10.185","text": "su" },
        {"start": "10.500","text": "gema" },
        {"start": "11.135","text": "para" },
        {"start": "11.376","text": "ver" },
        {"start": "11.543","text": "los" },
        {"start": "11.821","text": "pensamientos" },
        {"start": "12.859","text": "de" },
        {"start": "12.880","text": "Arthurius" }
]

var pistaES4 = [
        {"start": "0.220","text": "Yo" },
        {"start": "0.492","text": "también" },
        {"start": "0.959","text": "extraño" },
        {"start": "1.626","text": "nuestro" },
        {"start": "2.048","text": "hogar" },
        {"start": "2.309","text": "Arthurius" },
        {"start": "3.778","text": "extrañar" },
        {"start": "4.432","text": "es" },
        {"start": "4.740","text": "bueno" },
        {"start": "6.600","text": "dijo" },
        {"start": "7.040","text": "Theffanie" },
        {"start": "9.617","text": "Pero" },
        {"start": "10.236","text": "eso" },
        {"start": "10.531","text": "me" },
        {"start": "10.785","text": "hace" },
        {"start": "11.023","text": "sentir" },
        {"start": "11.659","text": "triste" },
        {"start": "13.800","text": "dijo" },
        {"start": "14.250","text": "Arthurius" },
        {"start": "16.167","text": "yo" },
        {"start": "16.456","text": "te" },
        {"start": "16.612","text": "voy" },
        {"start": "16.716","text": "a" },
        {"start": "16.890","text": "ayudar" }
]
 
var pistaES5 = [
        {"start": "0.313","text": "Theffanie" },
        {"start": "1.042","text": "uso" },
        {"start": "1.452","text": "el" },
        {"start": "1.620","text": "poder" },
        {"start": "1.943","text": "de" },
        {"start": "2.126","text": "su" },
        {"start": "2.472","text": "gema" },
        {"start": "3.319","text": "e" },
        {"start": "3.546","text": "hizo" },
        {"start": "3.886","text": "que" },
        {"start": "3.961","text": "Arthurius" },
        {"start": "4.663","text": "recordara" },
        {"start": "5.500","text": "todos" },
        {"start": "5.900","text": "los" },
        {"start": "6.093","text": "momentos" },
        {"start": "6.746","text": "divertidos" },
        {"start": "7.567","text": "con" },
        {"start": "7.745","text": "los" },
        {"start": "7.950","text": "Yogotars" },
        {"start": "10.450","text": "es" },
        {"start": "10.853","text": "importante" },
        {"start": "11.400","text": "disfrutar" },
        {"start": "12.343","text": "todos" },
        {"start": "12.618","text": "los" },
        {"start": "12.921","text": "momentos" },
        {"start": "13.412","text": "que" },
        {"start": "13.557","text": "vives" },
        {"start": "15.100","text": "dijo" },
        {"start": "15.700","text": "Theffanie" }
]
      
var pistaES6 = [
        {"start": "0.415","text": "Mis" },
        {"start": "0.764","text": "amigos" },
        {"start": "2.554","text": "Eso" },
        {"start": "2.772","text": "es" },
        {"start": "2.897","text": "lo" },
        {"start": "3.116","text": "que" },
        {"start": "3.500","text": "mas" },
        {"start": "3.667","text": "he" },
        {"start": "3.858","text": "disfrutado" },
        {"start": "4.671","text": "de" },
        {"start": "4.818","text": "la" },
        {"start": "4.976","text": "galaxia" },
        {"start": "5.550","text": "Ignós" },
        {"start": "7.470","text": "dijo" },
        {"start": "7.857","text": "Arthurius" },
        {"start": "10.187","text": "Al" },
        {"start": "10.465","text": "final" },
        {"start": "11.065","text": "Arthurius" },
        {"start": "11.742","text": "entendió" },
        {"start": "12.506","text": "que" },
        {"start": "12.642","text": "tambien" },
        {"start": "12.959","text": "es" },
        {"start": "13.188","text": "importante" },
        {"start": "13.963","text": "valorar" },
        {"start": "14.748","text": "a" },
        {"start": "14.803","text": "las" },
        {"start": "15.087","text": "personas" },
        {"start": "15.769","text": "que" },
        {"start": "15.850","text": "lo" },
        {"start": "15.954","text": "rodean" }
]

/*--------------------------------English--------------------------------*/
 
var pistaEN1 = [
        {"start": "0.611","text": "what" },
        {"start": "0.892","text": "do" },
        {"start": "1.035","text": "you" },
        {"start": "1.231","text": "linke" },
        {"start": "1.555","text": "the" },
        {"start": "1.646","text": "most" },
        {"start": "2.137","text": "in" },
        {"start": "2.347","text": "the" },
        {"start": "2.500","text": "Ignos" },
        {"start": "3.125","text": "galaxy" },
        {"start": "4.141","text": "Asked" },
        {"start": "4.614","text": "General" },
        {"start": "5.014","text": "Sharp" },
        {"start": "5.520","text": "to" },
        {"start": "5.628","text": "the" },
        {"start": "5.792","text": "Yogotars" }
]
 
var pistaEN2 = [
        {"start": "0.586","text": "Food" },
        {"start": "1.537","text": "Said" },
        {"start": "1.779","text": "Dinamita" },
        {"start": "3.109","text": "Books" },
        {"start": "3.941","text": "Said" },
        {"start": "4.296","text": "oona" },
        {"start": "5.605","text": "What" },
        {"start": "5.919","text": "about" },
        {"start": "6.247","text": "you" },
        {"start": "6.659","text": "Arthurius" },
        {"start": "7.867","text": "Sharp" },
        {"start": "8.121","text": "asked" }
]
  
var pistaEN3 = [
        {"start": "0.587","text": "Arthurius" },
        {"start": "1.467","text": "kept" },
        {"start": "1.708","text": "silent" },
        {"start": "2.641","text": "he" },
        {"start": "2.851","text": "seemed" },
        {"start": "3.200","text": "to" },
        {"start": "3.323","text": "be" },
        {"start": "3.480","text": "distracted" },
        {"start": "5.185","text": "Theffanie" },
        {"start": "5.604","text": "realized" },
        {"start": "6.250","text": "this" },
        {"start": "6.848","text": "and" },
        {"start": "7.000","text": "used" },
        {"start": "7.333","text": "her" },
        {"start": "7.536","text": "gem's" },
        {"start": "8.000","text": "power" },
        {"start": "8.511","text": "to" },
        {"start": "8.818","text": "read" },
        {"start": "9.234","text": "his" },
        {"start": "9.440","text": "mind" }
]

var pistaEN4 = [
        {"start": "0.676","text": "She" },
        {"start": "0.895","text": "realized" },
        {"start": "1.647","text": "that" },
        {"start": "1.837","text": "he" },
        {"start": "1.923","text": "was" },
        {"start": "2.088","text": "homesick" },
        {"start": "3.479","text": "I" },
        {"start": "3.643","text": "miss" },
        {"start": "3.886","text": "home" },
        {"start": "4.168","text": "too" },
        {"start": "4.500","text": "Arthurius" },
        {"start": "6.000","text": "It's" },
        {"start": "6.180","text": "ok" },
        {"start": "6.587","text": "to" },
        {"start": "6.790","text": "feel" },
        {"start": "7.025","text": "this" },
        {"start": "7.265","text": "way" },
        {"start": "8.074","text": "said" },
        {"start": "8.377","text": "Theffanie" },
        {"start": "9.523","text": "but" },
        {"start": "10.361","text": "it" },
        {"start": "10.538","text": "makes" },
        {"start": "10.909","text": "me" },
        {"start": "11.190","text": "sad" },
        {"start": "12.213","text": "replied" },
        {"start": "12.657","text": "Arthurius" },
        {"start": "14.254","text": "I'm" },
        {"start": "14.463","text": "going" },
        {"start": "14.734","text": "to" },
        {"start": "14.891","text": "help" },
        {"start": "15.139","text": "you" }
]
    
var pistaEN5 = [
        {"start": "0.598","text": "Theffanie" },
        {"start": "1.099","text": "used" },
        {"start": "1.325","text": "her" },
        {"start": "1.471","text": "gem" },
        {"start": "1.722","text": "again" },
        {"start": "2.311","text": "to" },
        {"start": "2.432","text": "help" },
        {"start": "2.654","text": "Arthurius" },
        {"start": "3.414","text": "remember" },
        {"start": "3.957","text": "all" },
        {"start": "4.296","text": "the" },
        {"start": "4.522","text": "special" },
        {"start": "4.735","text": "moments" },
        {"start": "5.437","text": "he" },
        {"start": "5.554","text": "had" },
        {"start": "5.767","text": "spent" },
        {"start": "5.980","text": "with" },
        {"start": "6.139","text": "the" },
        {"start": "6.244","text": "Yogotars" },
        {"start": "8.258","text": "It's" },
        {"start": "8.400","text": "important" },
        {"start": "9.152","text": "to" },
        {"start": "9.215","text": "enjoy" },
        {"start": "9.777","text": "every" },
        {"start": "10.184","text": "moment" },
        {"start": "10.727","text": "you" },
        {"start": "10.928","text": "live" },
        {"start": "11.442","text": "said" },
        {"start": "11.726","text": "Theffanie" }
]

var pistaEN6 = [
        {"start": "0.547","text": "My" },
        {"start": "0.839","text": "friends" },
        {"start": "1.981","text": "That's" },
        {"start": "2.288","text": "what" },
        {"start": "2.393","text": "I've" },
        {"start": "2.537","text": "enjoyed" },
        {"start": "2.935","text": "the" },
        {"start": "3.175","text": "most" },
        {"start": "3.401","text": "of" },
        {"start": "3.617","text": "Ignos" },
        {"start": "4.120","text": "Galaxy" },
        {"start": "5.100","text": "Said" },
        {"start": "5.310","text": "Arthurius" },
        {"start": "6.696","text": "In" },
        {"start": "6.860","text": "the" },
        {"start": "7.000","text": "end" },
        {"start": "7.722","text": "Arthurius" },
        {"start": "8.370","text": "understood" },
        {"start": "9.000","text": "that" },
        {"start": "9.200","text": "it" },
        {"start": "9.315","text": "is" },
        {"start": "9.454","text": "important" },
        {"start": "10.154","text": "to" },
        {"start": "10.485","text": "appreciate" },
        {"start": "10.941","text": "the" },
        {"start": "11.123","text": "people" },
        {"start": "11.500","text": "that" },
        {"start": "11.612","text": "surround" },
        {"start": "12.073","text": "you" },
        {"start": "12.691","text": "even" },
        {"start": "13.000","text": "when" },
        {"start": "13.243","text": "you" },
        {"start": "13.500","text": "are" },
        {"start": "13.694","text": "sad" }
]


/*--------------------------------Korean--------------------------------*/


var pistaKO1 = [
        { "start": "0.000","text": "너희들은" },
        { "start": "1.365","text": "이그노스" },
        { "start": "2.406","text": "은하에서" },
        { "start": "3.962","text": "무엇을" },
        { "start": "4.971","text": "제일" },
        { "start": "5.767","text": "좋아하니?" },
        { "start": "7.872","text": "샤프" },
        { "start": "8.625","text": "대장이" },
        { "start": "9.907","text": "요고타들에게" },
        { "start": "11.400","text": "물었어요." }
]

var pistaKO2 = [
        { "start": "0.000","text": "음식이요." },
        { "start": "1.816","text": "다이나미타가" },
        { "start": "3.292","text": "말했어요." },
        { "start": "5.192","text": "책이요." },
        { "start": "6.770","text": "우나가" },
        { "start": "7.780","text": "말했어요." },
        { "start": "9.538","text": "알투리우스야," },
        { "start": "11.303","text": "너는" },
        { "start": "12.016","text": "뭐를" },
        { "start": "12.587","text": "제일" },
        { "start": "13.126","text": "좋아하니?" },
        { "start": "15.220","text": "대장이" },
        { "start": "16.162","text": "물었어요." }

]

var pistaKO3 = [
        { "start": "0.000","text": "알투리우스는" },
        { "start": "2.017","text": "대답" },
        { "start": "2.635","text": "없이" },
        { "start": "3.818","text": "조용히" },
        { "start": "4.600","text": "있었어요." },
        { "start": "7.269","text": "듣지" },
        { "start": "8.060","text": "못했나" },
        { "start": "8.767","text": "봐요." },
        { "start": "10.673","text": "티파니는" },
        { "start": "12.213","text": "알투리우스에게" },
        { "start": "14.308","text": "문제가" },
        { "start": "15.167","text": "있다고" },
        { "start": "16.335","text": "생각했어요." },
        { "start": "18.816","text": "그래서" },
        { "start": "20.094","text": "보석" },
        { "start": "20.792","text": "파워를" },
        { "start": "21.457","text": "써서" },
        { "start": "22.817","text": "알투리우스의" },
        { "start": "24.512","text": "마음을" },
        { "start": "25.894","text": "들여다봤어요." }
]

var pistaKO4 = [
        { "start": "0.000","text": "이런," },
        { "start": "1.324","text": "알투리우스는" },
        { "start": "3.320","text": "집을" },
        { "start": "4.107","text": "그리워하고" },
        { "start": "5.281","text": "있었어요." },
        { "start": "7.863","text": "알투리우스야," },
        { "start": "9.920","text": "나도" },
        { "start": "10.703","text": "집이" },
        { "start": "11.428","text": "그리워." },
        { "start": "13.363","text": "그렇게" },
        { "start": "14.319","text": "느끼는" },
        { "start": "14.979","text": "건" },
        { "start": "15.887","text": "당연한" },
        { "start": "16.567","text": "거야." },
        { "start": "18.676","text": "티파니가" },
        { "start": "19.846","text": "말했어요." },
        { "start": "22.741","text": "하지만" },
        { "start": "23.903","text": "집이" },
        { "start": "24.622","text": "그리워서" },
        { "start": "26.283","text": "아주" },
        { "start": "26.926","text": "슬픈걸." },
        { "start": "29.102","text": "알투리우스가" },
        { "start": "30.821","text": "대답했어요." },
        { "start": "33.757","text": "내가" },
        { "start": "34.510","text": "도와줄게." }
]

var pistaKO5 = [
        { "start": "0.020","text": "티파니는" },
        { "start": "1.490","text": "다시" },
        { "start": "2.269","text": "보석을" },
        { "start": "3.025","text": "써서" },
        { "start": "4.352","text": "알투리우스가" },
        { "start": "6.345","text": "요고타들과" },
        { "start": "7.700","text": "함께" },
        { "start": "8.400","text": "한" },
        { "start": "9.492","text": "특별한" },
        { "start": "10.350","text": "시간을" },
        { "start": "11.754","text": "기억할" },
        { "start": "12.559","text": "수" },
        { "start": "13.079","text": "있게" },
        { "start": "14.203","text": "도와줬어요." },
        { "start": "17.275","text": "우리는" },
        { "start": "18.426","text": "살아" },
        { "start": "19.064","text": "있는" },
        { "start": "20.183","text": "모든" },
        { "start": "20.800","text": "순간을" },
        { "start": "22.139","text": "즐겨보자." },
        { "start": "24.496","text": "티파니가" },
        { "start": "25.823","text": "말했어요." }
]

var pistaKO6 = [
       { "start": "0.000","text": "친구들아," },
        { "start": "1.446","text": "내가" },
        { "start": "2.465","text": "이그노스" },
        { "start": "3.556","text": "은하에서" },
        { "start": "4.655","text": "가장" },
        { "start": "5.468","text": "좋아하는" },
        { "start": "6.365","text": "건" },
        { "start": "7.341","text": "바로" },
        { "start": "8.510","text": "너희와" },
        { "start": "9.437","text": "함께" },
        { "start": "10.150","text": "하는" },
        { "start": "11.352","text": "모든" },
        { "start": "12.016","text": "시간이야." },
        { "start": "14.416","text": "알투리우스가" },
        { "start": "16.121","text": "말했어요." },
        { "start": "18.818","text": "마침내," },
        { "start": "20.156","text": "알투리우스는" },
        { "start": "22.138","text": "슬프더라도" },
        { "start": "24.016","text": "옆에" },
        { "start": "24.800","text": "있는" },
        { "start": "25.420","text": "사람들을" },
        { "start": "26.995","text": "감사하게" },
        { "start": "28.138","text": "생각해야" },
        { "start": "29.188","text": "한다고" },
        { "start": "30.554","text": "배웠어요" }
]


