 var pistaES0 = [{ "start": "0.000","text": "empty" }]
 var pistaEN0 = [{ "start": "0.000","text": "empty" }]
 var pistaPT0 = [{ "start": "0.000","text": "empty" }]
 var pistaZH0 = [{ "start": "0.000","text": "empty" }]
 var pistaJA0 = [{ "start": "0.000","text": "empty" }]
 var pistaKO0 = [{ "start": "0.000","text": "empty" }]
 
 
 /*--------------------------------Spanish--------------------------------*/
  
  
  var pistaES1 = [
            {"start": "0.289","text": "En" },
            {"start": "0.640","text": "Nova" },
            {"start": "1.073","text": "Cali" },
            {"start": "1.815","text": "hay" },
            {"start": "2.070","text": "dos" },
            {"start": "2.352","text": "regiones" },
            {"start": "3.204","text": "lejos" },
            {"start": "3.851","text": "de" },
            {"start": "3.975","text": "Yogopolis" },
            {"start": "5.556","text": "la" },
            {"start": "5.783","text": "region" },
            {"start": "6.285","text": "de" },
            {"start": "6.416","text": "hielo" },
            {"start": "7.413","text": "y" },
            {"start": "7.502","text": "la" },
            {"start": "7.674","text": "de" },
            {"start": "7.887","text": "fuego" },
            {"start": "9.221","text": "sus" },
            {"start": "9.538","text": "habitantes" },
            {"start": "10.686","text": "no" },
            {"start": "10.982","text": "parecen" },
            {"start": "11.594","text": "llevarse" },
            {"start": "12.330","text": "nada" },
            {"start": "12.900","text": "bien" }
  ]
             
  var pistaES2 = [
            {"start": "0.433","text": "Viven" },
            {"start": "1.093","text": "en" },
            {"start": "1.293","text": "una" },
            {"start": "1.533","text": "eterna" },
            {"start": "2.290","text": "batalla" },
            {"start": "3.782","text": "Todo" },
            {"start": "4.312","text": "es" },
            {"start": "4.587","text": "motivo" },
            {"start": "5.123","text": "para" },
            {"start": "5.295","text": "iniciar" },
            {"start": "5.769","text": "una" },
            {"start": "6.086","text": "pelea" },
            {"start": "8.334","text": "No" },
            {"start": "8.651","text": "me" },
            {"start": "8.809","text": "vuelvas" },
            {"start": "9.111","text": "a" },
            {"start": "9.386","text": "decir" },
            {"start": "9.950","text": "eso" },
            {"start": "11.683","text": "dijo" },
            {"start": "12.330","text": "Icebro" },
            {"start": "14.571","text": "Por" },
            {"start": "14.826","text": "que" },
            {"start": "15.940","text": "que" },
            {"start": "16.173","text": "piensas" },
            {"start": "16.620","text": "hacer" },
            {"start": "18.511","text": "dijo" },
            {"start": "19.096","text": "firebro" }
 ];
      
 var pistaES3 = [
             {"start": "0.275","text": "Oof" },
             {"start": "1.004","text": "y" },
             {"start": "1.162","text": "Oona" },
             {"start": "1.774","text": "visitaban" },
             {"start": "2.441","text": "el" },
             {"start": "2.558","text": "lugar" },
             {"start": "3.060","text": "tranquilamente" },
             {"start": "5.047","text": "hasta" },
             {"start": "5.453","text": "que" },
             {"start": "5.487","text": "encontraron" },
             {"start": "6.264","text": "peleando" },
             {"start": "7.127","text": "a" },
             {"start": "7.137","text": "Icebro" },
             {"start": "8.190","text": "y" },
             {"start": "8.355","text": "Firebro" },
             {"start": "10.837","text": "Calmados" },
             {"start": "12.735","text": "dijeron" },
             {"start": "13.237","text": "al" },
             {"start": "13.395","text": "mismo" },
             {"start": "13.794","text": "tiempo" },
             {"start": "15.286","text": "Oof" },
             {"start": "15.369","text": "y" },
             {"start": "15.589","text": "Oona" },
             {"start": "18.023","text": "El" },
             {"start": "18.257","text": "empezo" },
             {"start": "19.213","text": "me" },
             {"start": "19.364","text": "insulto" },
             {"start": "21.207","text": "dijo" },
             {"start": "21.182","text": "Icebro" },
             {"start": "23.992","text": "El" },
             {"start": "24.412","text": "se" },
             {"start": "24.570","text": "enoja" },
             {"start": "24.982","text": "de" },
             {"start": "25.182","text": "todo" },
             {"start": "26.048","text": "yo" },
             {"start": "26.371","text": "no" },
             {"start": "26.509","text": "le" },
             {"start": "26.640","text": "dije" },
             {"start": "26.915","text": "nada" },
             {"start": "27.355","text": "malo" },
             {"start": "29.088","text": "dijo" },
             {"start": "29.651","text": "Firebro" }
 ]
  
 var pistaES4 = [
             { "start": "0.289","text": "Respiren" },
             { "start": "1.561","text": "hondo" },
             { "start": "3.576","text": "dijo" },
             { "start": "4.140","text": "Oona"},
             { "start": "6.271","text": "Luego"},
             { "start": "7.427","text": "saquen"},
             { "start": "8.348","text": "toooodo"},
             { "start": "9.510","text": "el"},
             { "start": "9.909","text": "aire"},
             { "start": "12.144","text": "dijo"},
             { "start": "12.921","text": "Oof"}
             
 ]
       
 var pistaES5 = [
             { "start": "0.261","text": "Cual" },
             { "start": "0.564","text": "es" },
             { "start": "0.729","text": "el" },
             { "start": "0.887","text": "problema" },
             { "start": "2.751","text": "dijo" },
             { "start": "3.280","text": "Oof" },
             { "start": "4.779","text": "el" },
             { "start": "5.082","text": "me" },
             { "start": "5.233","text": "dijo" },
             { "start": "5.426","text": "una" },
             { "start": "5.646","text": "mala" },
             { "start": "6.017","text": "palabra" },
             { "start": "7.165","text": "me" },
             { "start": "7.365","text": "dijo" },
             { "start": "8.630","text": "Hola" },
             { "start": "8.953","text": "camarada" },
             { "start": "10.383","text": "dijo" },
             { "start": "10.934","text": "icebro" },
             { "start": "14.111","text": "Eso" },
             { "start": "14.489","text": "no" },
             { "start": "14.558","text": "es" },
             { "start": "14.812","text": "una" },
             { "start": "14.998","text": "mala" },
             { "start": "15.348","text": "palabra" },
             { "start": "17.590","text": "dijo" },
             { "start": "18.133","text": "Firebro" },
             { "start": "21.035","text": "Por" },
             { "start": "21.324","text": "que" },
             { "start": "21.441","text": "se" },
             { "start": "21.633","text": "rie" },
             { "start": "22.012","text": "tu" },
             { "start": "22.067","text": "amiga" },
             { "start": "24.157","text": "dijo" },
             { "start": "24.838","text": "Icebro" }
 ]
      
 var pistaES6 = [
             { "start": "0.179","text": "Oona" },
             { "start": "0.543","text": "le" },
             { "start": "0.715","text": "explica" },
             { "start": "1.375","text": "a" },
             { "start": "1.643","text": "Icebro" },
             { "start": "2.668","text": "que" },
             { "start": "2.868","text": "camarada" },
             { "start": "3.596","text": "no" },
             { "start": "4.009","text": "es" },
             { "start": "4.263","text": "una" },
             { "start": "4.532","text": "mala" },
             { "start": "4.834","text": "palabra" },
             { "start": "5.921","text": "sino" },
             { "start": "6.361","text": "un" },
             { "start": "6.608","text": "sinonimo" },
             { "start": "7.832","text": "de" },
             { "start": "7.990","text": "amigo" },
             { "start": "8.926","text": "o" },
             { "start": "9.118","text": "compañero" },
             { "start": "11.477","text": "Todos" },
             { "start": "11.814","text": "se" },
             { "start": "11.938","text": "rien" },
             { "start": "12.419","text": "con" },
             { "start": "12.653","text": "ella" },
             { "start": "13.643","text": "y" },
             { "start": "13.643","text": "deciden" },
             { "start": "14.262","text": "hacer" },
             { "start": "14.771","text": "las" },
             { "start": "15.128","text": "pases" }
]


/*--------------------------------English--------------------------------*/


var pistaEN1 = [
             { "start":"0.591","text": "Far" },
             {"start": "0.949","text": "from" },
             {"start": "1.128","text": "yogopolis" },
             {"start": "2.118","text": "there" },
             {"start": "2.228","text": "are" },
             {"start": "2.434","text": "two" },
             {"start": "2.806","text": "regions" },
             {"start": "3.397","text": "in" },
             {"start": "3.562","text": "Nova" },
             {"start": "3.947","text": "Cali:" },
             {"start": "5.047","text": "The" },
             {"start": "5.185","text": "Land" },
             {"start": "5.487","text": "of" },
             {"start": "5.735","text": "Ice" },
             {"start": "6.533","text": "and" },
             {"start": "6.795","text": "the" },
             {"start": "7.055","text": "land" },
             {"start": "7.468","text": "of" },
             {"start": "7.798","text": "Fire" },
             {"start": "8.898","text": "Their" },
             {"start": "9.201","text": "inhabitants" },
             {"start": "10.026","text": "do" },
             {"start": "10.287","text": "not" },
             {"start": "10.659","text": "get" },
             {"start": "10.810","text": "along" }
]

var pistaEN2 = [
             {"start": "0.633","text": "They" },
             {"start": "0.990","text": "live" },
             {"start": "1.252","text": "an" },
             {"start": "1.582","text": "endless" },
             {"start": "2.200","text": "battle" },
             {"start": "3.246","text": "Everything" },
             {"start": "3.741","text": "is" },
             {"start": "3.975","text": "an" },
             {"start": "4.167","text": "excuse" },
             {"start": "4.690","text": "to" },
             {"start": "4.745","text": "start" },
             {"start": "5.061","text": "a" },
             {"start": "5.267","text": "fight" },
             {"start": "6.120","text": "Don't" },
             {"start": "6.546","text": "call" },
             {"start": "6.821","text": "me" },
             {"start": "7.124","text": "that" },
             {"start": "7.468","text": "again" },
             {"start": "8.403","text": "Exclaimed" },
             {"start": "9.049","text": "Icebro" },
             {"start": "10.328","text": "Why" },
             {"start": "11.085","text": "What" },
             {"start": "11.236","text": "are" },
             {"start": "11.539","text": "you" },
             {"start": "11.745","text": "going" },
             {"start": "12.061","text": "to" },
             {"start": "12.199","text": "do" },
             {"start": "12.900","text": "Asked" },
             {"start": "13.313","text": "Firebro" }
]

var pistaEN3 = [
             {"start": "0.674","text": "Oof" },
             {"start": "0.921","text": "and" },
             {"start": "1.183","text": "Oona" },
             {"start": "1.623","text": "were" },
             {"start": "1.760","text": "having" },
             {"start": "2.090","text": "a" },
             {"start": "2.310","text": "quiet" },
             {"start": "2.682","text": "visit" },
             {"start": "3.232","text": "until" },
             {"start": "3.603","text": "they" },
             {"start": "3.878","text": "found" },
             {"start": "4.208","text": "Icebro" },
             {"start": "4.910","text": "and" },
             {"start": "5.199","text": "Firebro" },
             {"start": "5.941","text": "arguing" },
             {"start": "7.234","text": "Easy" },
             {"start": "8.293","text": "said" },
             {"start": "8.582","text": "Oof" },
             {"start": "8.884","text": "and" },
             {"start": "9.118","text": "Oona" },
             {"start": "9.531","text": "at" },
             {"start": "9.627","text": "the" },
             {"start": "9.710","text": "same" },
             {"start": "10.040","text": "time" },
             {"start": "11.099","text": "He" },
             {"start": "11.374","text": "started" },
             {"start": "11.869","text": "it" },
             {"start": "12.323","text": "He" },
             {"start": "12.708","text": "insulted" },
             {"start": "13.533","text": "me" },
             {"start": "14.001","text": "said" },
             {"start": "14.221","text": "Icebro" },
             {"start": "15.610","text": "I" },
             {"start": "15.857","text": "didin't" },
             {"start": "16.132","text": "say" },
             {"start": "16.614","text": "anything" },
             {"start": "17.122","text": "bad" },
             {"start": "17.865","text": "He" },
             {"start": "18.195","text": "gets" },
             {"start": "18.374","text": "mad" },
             {"start": "18.580","text": "at" },
             {"start": "18.800","text": "everything" },
             {"start": "19.887","text": "Exclaimed" },
             {"start": "20.558","text": "Firebro" }
]

var pistaEN4 = [
            { "start": "0.674","text": "Take" },
            { "start": "0.935","text": "a" },
            { "start": "1.169","text": "deep" },
            { "start": "1.513","text": "breath"},
            { "start": "2.352","text": "said"},
            { "start": "2.668","text": "Oona"},
            { "start": "3.700","text": "Now" },
            { "start": "4.318","text": "exhale"},
            { "start": "5.350","text": "said"},
            { "start": "5.707","text": "Oof"}
            
]
 
var pistaEN5 = [
            { "start": "0.688","text": "What's" },
            { "start": "1.004","text": "the" },
            { "start": "1.128","text": "matter" },
            { "start": "2.008","text": "asked" },
            { "start": "2.352","text": "Oof" },
            { "start": "3.521","text": "He" },
            { "start": "3.645","text": "said" },
            { "start": "3.878","text": "a" },
            { "start": "4.085","text": "bad" },
            { "start": "4.456","text": "word" },
            { "start": "5.309","text": "he" },
            { "start": "5.515","text": "called" },
            { "start": "5.804","text": "me" },
            { "start": "6.216","text": "a" },
            { "start": "6.615","text": "fellow" },
            { "start": "7.427","text": "Icebro" },
            { "start": "7.990","text": "replied" },
            { "start": "9.187","text": "Thats" },
            { "start": "9.435","text": "not" },
            { "start": "9.696","text": "a" },
            { "start": "9.820","text": "bad" },
            { "start": "10.122","text": "word" },
            { "start": "10.961","text": "insisted" },
            { "start": "11.625","text": "Firebro" },
            { "start": "13.038","text": "Why" },
            { "start": "13.643","text": "is" },
            { "start": "13.835","text": "your" },
            { "start": "14.097","text": "friend" },
            { "start": "14.578","text": "laughing" },
            { "start": "15.816","text": "asked" },
            { "start": "16.173","text": "Icebro" },
            { "start": "16.999","text": "confused" }

]
  
var pistaEN6 = [
            { "start": "0.688","text": "Oona" },
            { "start": "0.990","text": "explained" },
            { "start": "1.692","text": "to" },
            { "start": "1.802","text": "Icebro" },
            { "start": "2.503","text": "that" },
            { "start": "2.806","text": "fellow" },
            { "start": "3.369","text": "is" },
            { "start": "3.617","text": "not" },
            { "start": "3.878","text": "a" },
            { "start": "3.961","text": "bad" },
            { "start": "4.208","text": "word" },
            { "start": "5.020","text": "but" },
            { "start": "5.130","text": "another" },
            { "start": "5.597","text": "term" },
            { "start": "6.038","text": "for" },
            { "start": "6.326","text": "friend" },
            { "start": "6.931","text": "or" },
            { "start": "7.138","text": "peer" },
            { "start": "8.142","text": "Everyone" },
            { "start": "8.664","text": "laughed" },
            { "start": "9.036","text": "with" },
            { "start": "9.242","text": "Oona" },
            { "start": "9.792","text": "and" },
            { "start": "9.943","text": "they" },
            { "start": "10.108","text": "decided" },
            { "start": "10.714","text": "to" },
            { "start": "10.837","text": "make" },
            { "start": "11.236","text": "peace" }
]


/*--------------------------------Corean--------------------------------*/


var pistaKO1 = [
            
    { "start": "0.001","text": "요고폴리스에서"},
    { "start": "2.258","text": "멀리" },
    { "start": "2.990","text": "떨어진" },
    { "start": "4.321","text": "노바칼리에는" },
    { "start": "7.029","text": "얼음의" },
    { "start": "7.863","text": "땅과" },
    { "start": "9.094","text": "불의" },
    { "start": "9.724","text": "땅이라는" },
    { "start": "11.379","text": "두" },
    { "start": "11.786","text": "지역이" },
    { "start": "13.056","text": "있어요." },
    { "start": "15.157","text": "두" },
    { "start": "15.513","text": "지역은" },
    { "start": "16.879","text": "사이가" },
    { "start": "17.793","text": "좋지" },
    { "start": "18.750","text": "않아요" }

]

var pistaKO2 = [
           
    { "start": "0.001","text": "두" },
    { "start": "0.350","text": "지역은" },
    { "start": "1.788","text": "끊임없이" },
    { "start": "3.267","text": "싸움을" },
    { "start": "4.385","text": "이어가요." },
    { "start": "6.385","text": "아주" },
    { "start": "7.171","text": "사소한" },
    { "start": "8.006","text": "것으로" },
    { "start": "9.391","text": "트집을" },
    { "start": "10.271","text": "잡아서" },
    { "start": "11.722","text": "싸움을" },
    { "start": "12.808","text": "시작해요." },
    { "start": "15.161","text": "나를" },
    { "start": "16.114","text": "다시는" },
    { "start": "16.753","text": "그렇게" },
    { "start": "17.275","text": "부르지마!"},
    { "start": "19.174","text": "아이스브로가" },
    { "start": "20.872","text": "소리쳤어요." },
    { "start": "22.739","text": "왜?" },
    { "start": "23.516","text": "내가" },
    { "start": "23.935","text": "그렇게" },
    { "start": "24.417","text": "부르면" },
    { "start": "25.100","text": "어찌할" },
    { "start": "25.700","text": "건데?" },
    { "start": "27.153","text": "파이어브로가" },
    { "start": "28.593","text": "물었어요." },
]

var pistaKO3 = [
    
        { "start": "0.001","text": "우프와" },
        { "start": "0.965","text": "우나는" },
        { "start": "2.118","text": "평화로운" },
        { "start": "3.049","text": "시간을" },
        { "start": "4.189","text": "보내고" },
        { "start": "5.037","text": "있었어요." },
        { "start": "7.304","text": "아이스브로와" },
        { "start": "9.183","text": "파이어브로가" },
        { "start": "11.215","text": "싸우는" },
        { "start": "11.929","text": "걸" },
        { "start": "12.669","text": "보기" },
        { "start": "13.279","text": "전까지는요." },
        { "start": "16.328","text": "진정해!" },
        { "start": "18.471","text": "우프와" },
        { "start": "19.373","text": "우나가" },
        { "start": "20.650","text": "동시에" },
        { "start": "21.537","text": "말했어요." },
        { "start": "23.878","text": "쟤가" },
        { "start": "24.338","text": "먼저" },
        { "start": "24.750","text": "시작했어!" },
        { "start": "26.444","text": "쟤가" },
        { "start": "27.163","text": "나를" },
        { "start": "27.618","text": "놀렸단" },
        { "start": "28.213","text": "말이야." },
        { "start": "30.007","text": "아이스브로가" },
        { "start": "31.600","text": "말했어요." },
        { "start": "34.009","text": "나는" },
        { "start": "34.819","text": "나쁜" },
        { "start": "35.358","text": "짓을" },
        { "start": "35.753","text": "하지" },
        { "start": "36.187","text": "않았어." },
        { "start": "37.813","text": "쟤는" },
        { "start": "38.804","text": "그냥" },
        { "start": "39.276","text": "모든" },
        { "start": "39.739","text": "것에" },
        { "start": "40.362","text": "화를" },
        { "start": "40.187","text": "내." },
        { "start": "42.444","text": "파이어브로가" },
        { "start": "43.985","text": "소리쳤어요." },
]

var pistaKO4 = [
            { "start": "0.001","text": "자," },
            { "start": "0.950","text": "숨을" },
            { "start": "2.203","text": "크게" },
            { "start": "2.948","text": "들이쉬어." },
            { "start": "5.086","text": "우나가" },
            { "start": "6.027","text": "말했어요." },
            { "start": "8.306","text": "이제" },
            { "start": "9.140","text": "내쉬어." },
            { "start": "11.251","text": "우프가" },
            { "start": "12.307","text": "말했어요." },
]

var pistaKO5 = [
    
        { "start": "0.003","text": "도대체" },
        { "start": "0.860","text": "무슨" },
        { "start": "1.245","text": "일이야?" },
        { "start": "2.772","text": "우프가" },
        { "start": "3.734","text": "물었어요." },
        { "start": "6.502","text": "쟤가" },
        { "start": "7.261","text": "나쁜" },
        { "start": "7.824","text": "말을" },
        { "start": "8.128","text": "했어." },
        { "start": "9.309","text": "나를" },
        { "start": "10.429","text": "'이 녀석'이라고" },
        { "start": "12.025","text": "불렀어." },
        { "start": "14.259","text": "아이스브로가" },
        { "start": "16.103","text": "대답했어요." },
        { "start": "19.060","text": "그건" },
        { "start": "19.923","text": "나쁜" },
        { "start": "20.579","text": "말이" },
        { "start": "21.136","text": "아니야." },
        { "start": "23.155","text": "파이어브로가" },
        { "start": "24.790","text": "주장했어요." },
        { "start": "27.796","text": "네" },
        { "start": "28.080","text": "친구는" },
        { "start": "29.290","text": "왜" },
        { "start": "29.743","text": "웃고" },
        { "start": "30.286","text": "있는" },
        { "start": "30.559","text": "거야?" },
        { "start": "31.859","text": "아이스브로가" },
        { "start": "33.621","text": "혼란스러워서" },
        { "start": "35.443","text": "물었어요." },
]

var pistaKO6 = [
    
        { "start": "0.002","text": "우나는" },
        { "start": "1.337","text": "'녀석'이" },
        { "start": "2.765","text": "나쁜" },
        { "start": "3.611","text": "말이" },
        { "start": "4.058","text": "아니고," },
        { "start": "5.356","text": "'친구'" },
        { "start": "6.658","text": "아니면" },
        { "start": "7.895","text": "'또래'라는" },
        { "start": "8.841","text": "말과" },
        { "start": "10.145","text": "비슷한" },
        { "start": "11.100","text": "단어라고" },
        { "start": "12.500","text": "설명했어요." },
        { "start": "15.447","text": "모두" },
        { "start": "16.474","text": "우나와" },
        { "start": "17.306","text": "같이" },
        { "start": "18.059","text": "웃었고," },
        { "start": "19.540","text": "사이좋게" },
        { "start": "20.709","text": "지내기로" },
        { "start": "22.047","text": "했어요." },
]


