var pistaES0 = [{ "start": "0.000","text": "empty" }]
 var pistaEN0 = [{ "start": "0.000","text": "empty" }]
 var pistaPT0 = [{ "start": "0.000","text": "empty" }]
 var pistaZH0 = [{ "start": "0.000","text": "empty" }]
 var pistaJA0 = [{ "start": "0.000","text": "empty" }]
 var pistaKO0 = [{ "start": "0.000","text": "empty" }]
 
 
 /*--------------------------------Spanish--------------------------------*/
  
  
  var pistaES1 = [
            {"start": "0.100","text": "En" },
            {"start": "0.496","text": "su" },
            {"start": "0.500","text": "laboratorio" },
            {"start": "1.943","text": "Eagle" },
            {"start": "2.283","text": "se" },
            {"start": "2.366","text": "encontraba," },
            {"start": "3.187","text": "pensando" },
            {"start": "3.986","text": "qué" },
            {"start": "4.150","text": "regalar," },
            {"start": "5.356","text": "mientras" },
            {"start": "5.967","text": "los" },
            {"start": "6.222","text": "otros" },
            {"start": "6.779","text": "la" },
            {"start": "7.056","text": "casa" },
            {"start": "7.332","text": "decoraban" },
            {"start": "9.078","text": "Era" },
            {"start": "9.413","text": "navidad" },
            {"start": "10.121","text": "y" },
            {"start": "10.247","text": "a" },
            {"start": "10.355","text": "Eagle" },
            {"start": "11.2443","text": "no" },
            {"start": "11.538","text": "le" },
            {"start": "11.561","text": "emocionaba" }
  ]
             
  var pistaES2 = [
            {"start": "0.070","text": "¡JO-JO-JO!" },
            {"start": "1.915","text": "Sonó" },
            {"start": "2.996","text": "e" },
            {"start": "3.112","text": "Eagle" },
            {"start": "3.606","text": "volteó," },
            {"start": "5.613","text": "Era" },
            {"start": "5.863","text": "un" },
            {"start": "6.074","text": "viejo" },
            {"start": "6.486","text": "barbón" },
            {"start": "7.113","text": "que" },
            {"start": "7.170","text": "a" },
            {"start": "7.315","text": "Eagle" },
            {"start": "7.756","text": "preguntó:" },
            {"start": "9.937","text": "¿Qué" },
            {"start": "10.194","text": "pasa " },
            {"start": "10.768","text": "Yogotar?" },
            {"start": "12.162","text": "¿Por" },
            {"start": "12.452","text": "qué" },
            {"start": "12.625","text": "no" },
            {"start": "12.480","text": "sales" },
            {"start": "13.165","text": "a" },
            {"start": "13.291","text": "decorar?" }
 ];
      
 var pistaES3 = [
             {"start": "0.171","text": "¿Con" },
             {"start": "0.479","text": "qué" },
             {"start": "0.797","text": "he" },
             {"start": "0.955","text": "de" },
             {"start": "1.094","text": "decorar" },
             {"start": "2.059","text": "si" },
             {"start": "2.300","text": "no" },
             {"start": "2.744","text": "tengo" },
             {"start": "3.140","text": "que" },
             {"start": "3.269","text": "regalar?" },
             {"start": "4.912","text": "No" },
             {"start": "5.200","text": "dejo" },
             {"start": "5.509","text": "de" },
             {"start": "5.647","text": "pensar" },
             {"start": "6.437","text": "pero " },
             {"start": "6.605","text": "nada" },
             {"start": "7.070","text": "puedo" },
             {"start": "7.415","text": "crear" }
 ]
  
 var pistaES4 = [
             { "start": "0.170","text": "¡JO-JO-JO!" },
             { "start": "1.821","text": "Mi" },
             { "start": "2.088","text": "querido" },
             { "start": "2.604","text": "Yogotar"},
             { "start": "3.816","text": "la"},
             { "start": "4.045","text": "navidad"},
             { "start": "4.607","text": "no"},
             { "start": "4.982","text": "se"},
             { "start": "5.327","text": "trata"},
             { "start": "5.666","text": "de"},
             { "start": "5.858","text": "regalar"},
             { "start": "6.953","text": "se"},
             { "start": "7.288","text": "trata"},
             { "start": "7.664","text": "de"},
             { "start": "7.788","text": "hornear"},
             { "start": "8.774","text": "cenar"},
             { "start": "9.777","text": "y"},
             { "start": "9.924","text": "en"},
             { "start": "10.087","text": "familia"},
             { "start": "10.540","text": "disfrutar"}
             
 ]
       
 var pistaES5 = [
             { "start": "0.139","text": "-" },
             { "start": "0.139","text": "¡Lo" },
             { "start": "0.388","text": "tengo!" },
             { "start": "1.761","text": "Ya" },
             { "start": "2.088","text": "sé" },
             { "start": "2.541","text": "que" },
             { "start": "2.619","text": "les" },
             { "start": "2.895","text": "voy" },
             { "start": "3.079","text": "a" },
             { "start": "3.185","text": "regalar" },
             { "start": "4.823","text": "dijo" },
             { "start": "5.428","text": "Eagle" },
             { "start": "6.774","text": "antes" },
             { "start": "7.177","text": "de" },
             { "start": "7.318","text": "ponerse" },
             { "start": "7.695","text": "a" },
             { "start": "7.814","text": "trabajar" },
             { "start": "8.623","text": "en" },
             { "start": "8.770","text": "una" },
             { "start": "9.122","text": "gran" },
             { "start": "9.461","text": "estrella" },
             { "start": "10.729","text": "para" },
             { "start": "10.872","text": "el" },
             { "start": "11.069","text": "árbol" },
             { "start": "11.526","text": "adornar" }
 ]
      
 var pistaES6 = [
             { "start": "0.260","text": "Entonces" },
             { "start": "1.228","text": "nuestro" },
             { "start": "1.714","text": "querido" },
             { "start": "2.265","text": "Yogotar" },
             { "start": "2.896","text": "la" },
             { "start": "3.116","text": "estrella" },
             { "start": "3.640","text": "colocó" },
             { "start": "4.670","text": "y" },
             { "start": "4.781","text": "a" },
             { "start": "5.035","text": "todos" },
             { "start": "5.525","text": "juntó" },
             { "start": "6.731","text": "para" },
             { "start": "7.000","text": "cantar" },
             { "start": "7.915","text": "disfrutar" },
             { "start": "8.826","text": "y" },
             { "start": "8.986","text": "con" },
             { "start": "9.171","text": "sus" },
             { "start": "9.371","text": "sonrisas" },
             { "start": "10.224","text": "a" },
             { "start": "10.317","text": "la" },
             { "start": "10.456","text": "navidad" },
             { "start": "11.030","text": "iluminar" }
]


/*--------------------------------English--------------------------------*/


var pistaEN1 = [
             { "start":"0.526","text": "Eagle" },
             {"start": "0.781","text": "was" },
             {"start": "1.277","text": "in" },
             {"start": "1.547","text": "his" },
             {"start": "1.943","text": "laboratory," },
             {"start": "2.509","text": "thinking" },
             {"start": "2.719","text": "of" },
             {"start": "2.800","text": "the" },
             {"start": "3.080","text": "presents" },
             {"start": "3.733","text": "he," },
             {"start": "3.839","text": "would" },
             {"start": "4.056","text": "give" },
             {"start": "4.406","text": "on" },
             {"start": "4.640","text": "Christmas" },
             {"start": "5.536","text": "while" },
             {"start": "5.600","text": "the" },
             {"start": "5.822","text": "rest" },
             {"start": "6.152","text": "of" },
             {"start": "6.360","text": "his" },
             {"start": "6.479","text": "friends" },
             {"start": "6.911","text": "were" },
             {"start": "7.110","text": "decorating" },
             {"start": "7.752","text": "the" },
             {"start": "8.000","text": "house" },
             {"start": "8.905","text": "Eagle" },
             {"start": "9.581","text": "was" },
             {"start": "9.807","text": "not" },
             {"start": "10.363","text": "excited" }
]

var pistaEN2 = [
             {"start": "0.711","text": "HO-HO-HO!" },
             {"start": "2.876","text": "Eagle" },
             {"start": "3.301","text": "turned" },
             {"start": "3.549","text": "to" },
             {"start": "3.943","text": "find" },
             {"start": "4.245","text": "an" },
             {"start": "4.700","text": "old" },
             {"start": "4.894","text": "bearded" },
             {"start": "5.296","text": "man" },
             {"start": "5.745","text": "who" },
             {"start": "5.900","text": "asked" },
             {"start": "6.734","text": "What's" },
             {"start": "7.113","text": "wrong" },
             {"start": "7.484","text": "Yogotar?" },
             {"start": "8.783","text": "Why" },
             {"start": "9.232","text": "aren't" },
             {"start": "9.518","text": "you" },
             {"start": "9.754","text": "decorating" },
             {"start": "10.446","text": "the" },
             {"start": "10.519","text": "house?" },
]

var pistaEN3 = [
             {"start": "0.597","text": "How" },
             {"start": "0.839","text": "can" },
             {"start": "1.000","text": "I" },
             {"start": "1.436","text": "decorate" },
             {"start": "1.905","text": "if" },
             {"start": "1.943","text": "I" },
             {"start": "2.077","text": "have" },
             {"start": "2.462","text": "no" },
             {"start": "2.889","text": "presents" },
             {"start": "3.494","text": "to" },
             {"start": "3.645","text": "give?" },
             {"start": "4.544","text": "I" },
             {"start": "4.716","text": "have" },
             {"start": "5.010","text": "no" },
             {"start": "5.271","text": "idea" },
             {"start": "5.933","text": "what" },
             {"start": "6.248","text": "to" },
             {"start": "6.441","text": "give" },
             {"start": "6.686","text": "my" },
             {"start": "6.972","text": "friends" }
]

var pistaEN4 = [
            { "start": "0.899","text": "HO-HO-HO!" },
            { "start": "2.353","text": "My" },
            { "start": "2.803","text": "dear" },
            { "start": "3.209","text": "Yogotar"},
            { "start": "4.525","text": "Christmas"},
            { "start": "4.955","text": "is"},
            { "start": "5.000","text": "not" },
            { "start": "5.377","text": "about"},
            { "start": "5.826","text": "giving"},
            { "start": "6.335","text": "presents"},
            { "start": "7.541","text": "it's"},
            { "start": "7.719","text": "about"},
            { "start": "8.101","text": "enjoying"},
            { "start": "8.692","text": "some"},
            { "start": "8.921","text": "time"},
            { "start": "9.307","text": "together"},
            { "start": "9.875","text": "with"},
            { "start": "10.017","text": "your"},
            { "start": "10.324","text": "friends"},
            { "start": "10.715","text": "and"},
            { "start": "10.994","text": "family"},
            
]
 
var pistaEN5 = [
            { "start": "0.645","text": "I've" },
            { "start": "0.923","text": "got" },
            { "start": "1.000","text": "it!" },
            { "start": "1.943","text": "I" },
            { "start": "2.000","text": "know" },
            { "start": "2.138","text": "what" },
            { "start": "2.239","text": "I'll" },
            { "start": "2.466","text": "give" },
            { "start": "2.663","text": "my" },
            { "start": "3.000","text": "friends" },
            { "start": "3.836","text": "said" },
            { "start": "3.992","text": "Eagle" },
            { "start": "5.080","text": "Eagle" },
            { "start": "5.485","text": "began" },
            { "start": "5.945","text": "working" },
            { "start": "6.282","text": "on" },
            { "start": "6.600","text": "a" },
            { "start": "6.801","text": "big" },
            { "start": "7.009","text": "star" },
            { "start": "7.705","text": "to" },
            { "start": "7.896","text": "decorate" },
            { "start": "8.427","text": "the" },
            { "start": "8.547","text": "Christmas" },
            { "start": "9.052","text": "Tree" },

]
  
var pistaEN6 = [
            { "start": "0.681","text": "Then" },
            { "start": "1.340","text": "our" },
            { "start": "1.715","text": "dear" },
            { "start": "2.114","text": "Yogotar" },
            { "start": "2.907","text": "put" },
            { "start": "3.000","text": "the" },
            { "start": "3.194","text": "star" },
            { "start": "3.704","text": "on" },
            { "start": "3.973","text": "top" },
            { "start": "4.219","text": "of" },
            { "start": "4.300","text": "the" },
            { "start": "4.478","text": "tree" },
            { "start": "5.809","text": "His" },
            { "start": "6.080","text": "friends" },
            { "start": "6.458","text": "gathered" },
            { "start": "6.926","text": "around" },
            { "start": "7.338","text": "to" },
            { "start": "7.500","text": "sing" },
            { "start": "8.000","text": "and" },
            { "start": "8.140","text": "enjoy" },
            { "start": "8.613","text": "their" },
            { "start": "8.891","text": "time" },
            { "start": "9.193","text": "together" },
            { "start": "10.467","text": "The" },
            { "start": "10.676","text": "bright" },
            { "start": "11.107","text": "smiles" },
            { "start": "11.548","text": "on" },
            { "start": "11.800","text": "their" },
            { "start": "11.951","text": "faces" },
            { "start": "12.456","text": "lit" },
            { "start": "12.943","text": "up" },
            { "start": "13.179","text": "Christmas" },
]


/*--------------------------------Corean--------------------------------*/


var pistaKO1 = [
            { "start": "0.411","text": "이글이는" },
            { "start": "1.883","text": "실험실에서" },
            { "start": "3.910","text": "친구들에게" },
            { "start": "5.236","text": "줄" },
            { "start": "6.335","text": "크리스마스" },
            { "start": "7.821","text": "선물을" },
            { "start": "9.335","text": "곰곰히" },
            { "start": "10.329","text": "생각하고" },
            { "start": "11.524","text": "있었어요." },
            { "start": "14.020","text": "이글이" },
            { "start": "14.886","text": "친구들은" },
            { "start": "16.503","text": "집을" },
            { "start": "17.735","text": "예쁘게" },
            { "start": "18.777","text": "꾸미고" },
            { "start": "19.671","text": "있었지만" },
            { "start": "21.334","text": "이글이는" },
            { "start": "23.013","text": "전혀" },
            { "start": "23.715","text": "관심이" },
            { "start": "24.580","text": "없었어요." }

]

var pistaKO2 = [
            { "start": "0.016","text": "호-호-호!" },
            { "start": "4.151","text": "이글이는" },
            { "start": "5.360","text": "고개를" },
            { "start": "6.258","text": "돌려" },
            { "start": "7.393","text": "수염이" },
            { "start": "8.366 ","text": "긴" },
            { "start": "9.206","text": "할아버지를" },
            { "start": "10.493","text": "보았어요." },
            { "start": "13.074","text": "할아버지는" },
            { "start": "14.749","text": "이렇게" },
            { "start": "15.600","text": "물으셨어요." },
            { "start": "18.393","text": "무슨" },
            { "start": "19.000","text": "일이" },
            { "start": "19.502","text": "있니" },
            { "start": "19.967","text": "요고타야?" },
            { "start": "21.738","text": "왜" },
            { "start": "22.186","text": "친구들과" },
            { "start": "23.031","text": "함께" },
            { "start": "24.258","text": "집을" },
            { "start": "25.074","text": "꾸미지" },
            { "start": "26.043","text": "않는거니?" }
]

var pistaKO3 = [
            { "start": "0.001","text": "친구들에게" },
            { "start": "1.145","text": "줄" },
            { "start": "1.641","text": "선물이" },
            { "start": "2.200","text": "없는데" },
            { "start": "3.305","text": "어떻게" },
            { "start": "3.987","text": "집을" },
            { "start": "4.519","text": "꾸밀" },
            { "start": "4.900","text": "수" },
            { "start": "5.200","text": "있겠어요?" },
            { "start": "7.175","text": "친구들에게" },
            { "start": "8.821","text": "뭘" },
            { "start": "9.222","text": "선물할지" },
            { "start": "10.447","text": "전혀" },
            { "start": "11.058","text": "모르겠어요." }
]

var pistaKO4 = [
            { "start": "0.046","text": "호-호-호!" },
            { "start": "3.318","text": "우리" },
            { "start": "3.993","text": "사랑스러운" },
            { "start": "5.257","text": "요고타야," },
            { "start": "7.171","text": "크리스마스" },
            { "start": "8.584","text": "선물을" },
            { "start": "9.478","text": "주는" },
            { "start": "9.976","text": "게" },
            { "start": "10.989 ","text": "중요한" },
            { "start": "11.700","text": "게" },
            { "start": "12.106","text": "아니란다." },
            { "start": "14.206","text": "크리스마스는" },
            { "start": "16.155","text": "가족과" },
            { "start": "17.700","text": "친구들과" },
            { "start": "19.061","text": "함께" },
            { "start": "19.881","text": "모여서" },
            { "start": "21.426","text": "즐거운" },
            { "start": "22.300","text": "시간을" },
            { "start": "23.207","text": "갖는" },
            { "start": "23.693","text": "게" },
            { "start": "24.193","text": "중요한" },
            { "start": "24.716","text": "거란다." }
]

var pistaKO5 = [
            { "start": "0.006","text": "아!" },
            { "start": "0.714","text": "알겠어요!" },
            { "start": "2.318","text": "이제" },
            { "start": "3.257","text": "친구들에게" },
            { "start": "4.356","text": "뭘" },
            { "start": "4.722","text": "선물할지" },
            { "start": "6.158","text": "생각이" },
            { "start": "6.859","text": "났어요!" },
            { "start": "9.162","text": "이글이가" },
            { "start": "10.146","text": "말했어요" },
            { "start": "11.816","text": "이글이는" },
            { "start": "13.192","text": "크리스마스트리에" },
            { "start": "15.213","text": "장식할" },
            { "start": "16.676","text": "큰" },
            { "start": "17.133","text": "별을" },
            { "start": "18.052","text": "만들기" },
            { "start": "18.891","text": "시작했어요." }
]

var pistaKO6 = [
            { "start": "0.029","text": "마침내" },
            { "start": "1.083","text": "우리의" },
            { "start": "1.733","text": "사랑스러운" },
            { "start": "2.817","text": "요고타는" },
            { "start": "4.579","text": "큰" },
            { "start": "5.043","text": "별을" },
            { "start": "6.173","text": "트리" },
            { "start": "6.673","text": "맨" },
            { "start": "7.194","text": "꼭대기에" },
            { "start": "8.209","text": "달았어요." },
            { "start": "10.603","text": "그리고" },
            { "start": "11.807","text": "친구들과" },
            { "start": "12.946","text": "함께" },
            { "start": "13.650","text": "모여서" },
            { "start": "15.163","text": "같이" },
            { "start": "15.884","text": "노래를" },
            { "start": "16.704","text": "부르고" },
            { "start": "17.888","text": "즐거운" },
            { "start": "18.635","text": "시간을" },
            { "start": "19.502","text": "보냈어요." },
            { "start": "21.892","text": "모두의" },
            { "start": "22.840","text": "얼굴에" },
            { "start": "24.012","text": "웃음꽃이" },
            { "start": "25.107","text": "활짝" },
            { "start": "26.000","text": "피었어요." },
]


